print("Exercise 2")

print("Operations")
print("3 + 4", 3 + 4)
print("3 - 4", 3 - 4)
print("3 * 4", 3 * 4)
print("3 % 4", 3 % 4)
print("3 / 4", 3 / 4)
print("3 ** 4", 3 ** 4)
print("3 // 4", 3 // 4)

print("\nString")
print("Carlos")
print("Ayala")
print("Perú")
print("I am enjoying 30 days of python")

print("\nData types")
print("type(10)", type(10))
print("type(9.8)", type(9.8))
print("type(3.14)", type(3.14))
print("type(4-4j)", type(4 - 4j))
print("type(['Asabeneh', 'Python', 'Finland'])", type(['Asabeneh', 'Python', 'Finland']))
print("Carlos", type("Carlos"))
print("Ayala", type("Ayala"))
print("Perú", type("Perú"))

print("\nExercise 3")
print("type(5)", type(5))
print("type(2.8)", type(2.8))
print("type(1 - 1j)", type(1 - 1j))
print("type('some string')", type('some string'))
print("type(True)", type(True))
print("type([1, 2.8, 3, 'string', True, [1, 2, 3]])", type([1, 2.8, 3, 'string', True, [1, 2, 3]]))
print("type((1, 2, 3))", type((1, 2, 3)))
print("type({1, 2, 3, 4, 5})", type({1, 2, 3, 4, 5}))
print("type({'data1': 1, 'data2': [1, 2, 3], 'data3': True})", type({ 'data1': 1, 'data2': [1, 2, 3], 'data3': True }))

print("\nExercise 3: Euclidian distance")
print("Euclidean distance d(p, q) = d((3,9), (4, 14)) = ", ((3 - 4) ** 2 + (9 - 14) ** 2) ** 0.5)
