"""Author dense teaching chapters for Days 21–40."""

from __future__ import annotations

# ruff: noqa: E501
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRS = {
    21: "day_21_virtual_environments",
    22: "day_22_cli_design",
    23: "day_23_configuration_and_secrets",
    24: "day_24_json__csv__and_sqlite",
    25: "day_25_type_hints_and_static_checks",
    26: "day_26_structured_logging",
    27: "day_27_git_and_code_review",
    28: "day_28_dependency_hygiene_and_sboms",
    29: "day_29_threat_modeling",
    30: "day_30_project__secure_evidence_journal",
    31: "day_31_processes_and_system_calls",
    32: "day_32_linux_command_line",
    33: "day_33_paths_and_file_metadata",
    34: "day_34_safe_subprocesses",
    35: "day_35_users_and_permissions",
    36: "day_36_timeouts_and_resource_limits",
    37: "day_37_processes__threads__and_queues",
    38: "day_38_async_i_o",
    39: "day_39_host_inventories",
    40: "day_40_project__host_baseline_auditor",
    41: "day_41_addresses__ports__and_sockets",
}


@dataclass(frozen=True)
class Spec:
    day: int
    title: str
    why: str
    problem: str
    vocabulary: str
    examples: tuple[tuple[str, str, str, str], ...]
    trace: str
    mistakes: str
    security: str
    mental: str
    limits: str


def ex(
    title: str, explanation: str, code: str, output: str
) -> tuple[str, str, str, str]:
    return title, explanation, code, output


SPECS = [
    Spec(
        21,
        "Virtual Environments and Reproducible Setup",
        "A script that works only on its author’s machine is not a reliable security tool. Virtual environments give a project an isolated interpreter and make its dependency assumptions visible.",
        "A new learner must install the course without confusing the system Python, a global package, and the repository environment.",
        "A **virtual environment** is an isolated Python installation for one project. The **interpreter** is the executable that runs code. A **dependency** is a package or tool the project needs.",
        (
            ex(
                "Create an environment",
                "Use Python’s built-in module to create a `.venv` directory.",
                "python -m venv .venv\n# macOS/Linux\nsource .venv/bin/activate\n# Windows PowerShell\n.venv\\Scripts\\Activate.ps1",
                "The prompt usually shows `(.venv)` after activation.",
            ),
            ex(
                "Prove the interpreter",
                "Do not trust the prompt alone; ask the selected interpreter where it lives.",
                'python -c "import sys; print(sys.executable)"',
                "The printed path should point inside the repository’s `.venv`.",
            ),
            ex(
                "Install through the interpreter",
                "`python -m pip` makes it less likely that pip belongs to another Python.",
                "python -m pip install -r requirements-dev.txt\npython -m pip list",
                "The installed tools are associated with the active interpreter.",
            ),
            ex(
                "Freeze a small environment",
                "A project record makes a setup reviewable.",
                "python -m pip freeze > local-environment.txt",
                "The file records versions; do not commit private paths or unrelated global packages.",
            ),
            ex(
                "Deactivate and compare",
                "Seeing the interpreter change makes environment isolation concrete.",
                'deactivate\npython -c "import sys; print(sys.executable)"',
                "The executable path changes away from `.venv`.",
            ),
        ),
        "Activation changes the shell’s command lookup; it does not change Python itself. `python -m pip` uses the interpreter selected by `python`, so the package and runtime stay aligned.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| global install | one project breaks another | activate `.venv` |\n| wrong interpreter in VS Code | imports appear missing | select the repository interpreter |\n| commit `.venv` | huge machine-specific diff | ignore it and recreate it |\n| trust activation blindly | shell and editor disagree | print `sys.executable` |\n| install without a record | setup cannot be reproduced | document dependencies and versions |",
        "Create and remove a disposable environment for the course only. Never install unknown packages into the system interpreter, and never place credentials in environment snapshots.",
        "An environment is a reproducible boundary around the interpreter and its dependencies.",
        "Virtual environments do not sandbox malicious code, prove package provenance, or protect a host from a dangerous dependency. Use trusted sources and review the dependency list.",
    ),
    Spec(
        22,
        "Command-Line Interfaces and Explicit Input",
        "A CLI is the first trust boundary for many security utilities. Clear options, help text, validation, and exit statuses make a tool safer to automate and easier to review.",
        "Turn the log triage function into a command that accepts a fixture path, a finite limit, and an output mode without relying on ambiguous positional input.",
        "An **argument parser** turns shell text into values. An **exit status** communicates success or failure. A **flag** is an explicit named option.",
        (
            ex(
                "Parse a flag",
                "`argparse` converts a command into a namespace.",
                'import argparse\nparser = argparse.ArgumentParser()\nparser.add_argument("--limit", type=int, default=100)\nargs = parser.parse_args(["--limit", "5"])\nprint(args.limit)',
                "`5` as an integer.",
            ),
            ex(
                "Show help",
                "Help is part of the public contract.",
                'parser = argparse.ArgumentParser(description="Review a local training fixture")\nparser.add_argument("--input", required=True)\nprint(parser.format_help())',
                "The help names the required input and its purpose.",
            ),
            ex(
                "Reject a bound",
                "Type conversion is not enough; enforce a safe domain.",
                'def positive_limit(value):\n    number = int(value)\n    if not 1 <= number <= 10_000:\n        raise argparse.ArgumentTypeError("limit must be 1..10000")\n    return number',
                "Bad limits are rejected before processing begins.",
            ),
            ex(
                "Return a status",
                "Shell automation needs a stable result.",
                "def main():\n    return 0\n\nraise SystemExit(main())",
                "Zero conventionally means success; document non-zero meanings.",
            ),
            ex(
                "Keep paths as data",
                "An input path is not a shell command.",
                'parser.add_argument("--input", type=Path)\nprint(args.input)',
                "The value remains a path object until a bounded file function accepts it.",
            ),
        ),
        "The shell provides tokens, argparse converts them, the custom validator checks policy, and only then does the tool resolve a path or process a fixture.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| `shell=True` for convenience | input becomes command syntax | pass data as arguments |\n| no help | users guess the interface | describe every option |\n| unlimited default | automation consumes too much | choose a finite bound |\n| print errors and return 0 | scripts treat failure as success | use documented exit statuses |\n| positional secrets | shell history stores them | use safer secret mechanisms and never echo values |",
        "Build a local CLI that accepts only the course fixture root, a finite line limit, and a report path beneath a dedicated output directory. Test invalid paths and limits.",
        "A CLI makes program assumptions visible at the point where human or automation input enters.",
        "A well-designed CLI cannot authorize the target. Its caller still needs permission, and its path and output policy need defense in depth.",
    ),
    Spec(
        23,
        "Configuration, Environment Variables, and Secrets",
        "Configuration changes between development, testing, and deployment. Secrets must be supplied through a controlled mechanism, not copied into source code or printed while debugging.",
        "The tool needs a timeout and a case identifier, while an optional API token must be present without ever appearing in a report.",
        "Configuration is non-code input that controls behavior. A **secret** is sensitive authentication material. A **default** is a fallback, not proof that a value is valid.",
        (
            ex(
                "Read a default",
                "A harmless setting can use an explicit fallback.",
                'import os\ntimeout = int(os.getenv("APP_TIMEOUT", "3"))\nprint(timeout)',
                "`3` when the variable is absent.",
            ),
            ex(
                "Validate configuration",
                "Reject values outside the operational policy.",
                'def read_timeout(raw):\n    value = int(raw)\n    if not 1 <= value <= 60:\n        raise ValueError("timeout must be 1..60 seconds")\n    return value',
                "A timeout of `0` or `61` fails early.",
            ),
            ex(
                "Detect a secret without printing it",
                "Presence is often enough for diagnostics.",
                'token = os.getenv("TRAINING_TOKEN")\nprint({"token_present": token is not None})',
                "`{'token_present': False}` or `True`; the token value is never printed.",
            ),
            ex(
                "Separate config from code",
                "A dictionary makes the final configuration inspectable.",
                'config = {"timeout": read_timeout(os.getenv("APP_TIMEOUT", "3")), "case_id": os.getenv("CASE_ID", "training")}\nprint(config)',
                "Only non-sensitive configuration appears.",
            ),
            ex(
                "Fail closed for required secrets",
                "A tool that requires authentication should not silently continue without it.",
                'if token is None and require_token:\n    raise RuntimeError("required token is missing")',
                "The caller receives an explicit setup failure.",
            ),
        ),
        "The program reads environment text, converts it, enforces bounds, and stores a safe configuration object. Secret values remain outside logs, reports, and source control.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| secret in source | it enters Git history | use an external secret mechanism |\n| `print(os.environ)` | all environment secrets leak | print selected safe metadata |\n| default for a required token | authentication silently fails | fail closed |\n| no bounds | timeout or batch becomes abusive | validate limits |\n| configuration scattered | behavior is hard to audit | load once into a typed object |",
        "Use fake training values only. Add tests proving a token value is absent from output and that a timeout outside `1..60` is rejected.",
        "Configuration is input with policy; a secret’s presence is not permission to reveal or misuse it.",
        "Environment variables can leak through process listings, CI logs, crash reports, and shell history. Production secret management needs platform controls.",
    ),
    Spec(
        24,
        "JSON, CSV, and SQLite Data Boundaries",
        "Security engineering moves between text formats and databases. Each boundary needs a schema, encoding decision, and safe query or serialization method.",
        "Load synthetic event records, validate them, store them locally, and retrieve a summary without concatenating user input into SQL.",
        "JSON represents structured values. CSV represents rows and columns. SQLite is a local relational database. A **parameterized query** keeps data separate from SQL syntax.",
        (
            ex(
                "Round-trip JSON",
                "JSON maps common Python values to a text representation.",
                'import json\nrecord = {"source": "auth", "severity": 7}\ntext = json.dumps(record)\nprint(json.loads(text)["severity"])',
                "`7` after serialization and parsing.",
            ),
            ex(
                "Read CSV rows",
                "`csv.DictReader` maps column names to row values, which still arrive as strings.",
                'import csv\nfrom io import StringIO\nrows = csv.DictReader(StringIO("source,severity\\nauth,7\\n"))\nprint(next(rows))',
                "`{'source': 'auth', 'severity': '7'}`; validate and convert severity.",
            ),
            ex(
                "Create a table",
                "A schema makes stored fields visible.",
                'import sqlite3\nconnection = sqlite3.connect(":memory:")\nconnection.execute("CREATE TABLE events (source TEXT, severity INTEGER)")',
                "The database now has a table with two columns.",
            ),
            ex(
                "Parameterize data",
                "Never build SQL by concatenating input.",
                'connection.execute("INSERT INTO events VALUES (?, ?)", ("auth", 7))\nrow = connection.execute("SELECT source, severity FROM events WHERE severity >= ?", (7,)).fetchone()\nprint(row)',
                "`('auth', 7)`",
            ),
            ex(
                "Close the boundary",
                "A context manager commits or closes a short-lived database session.",
                'with sqlite3.connect("training.db") as db:\n    db.execute("CREATE TABLE IF NOT EXISTS notes (text TEXT)")',
                "The connection is cleaned up when the block exits.",
            ),
        ),
        "CSV values arrive as strings; validation converts them into an internal record; the parameterized query receives values separately from the SQL statement.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| trust JSON shape | missing or wrong fields reach policy | validate schema |\n| assume CSV types | severity compares as text | convert explicitly |\n| SQL concatenation | input becomes query syntax | use placeholders |\n| store raw secrets | local database becomes a leak | minimize and redact |\n| no migration note | schema changes silently break tools | document schema and version |",
        "Use a temporary SQLite file under training output, parameterized statements, synthetic rows, and cleanup after tests. Never import a private CSV.",
        "Serialization is a boundary transformation; a safe database call keeps data values separate from executable syntax.",
        "Parameterized SQL prevents one class of injection but does not authorize data access, validate business logic, or protect a database file’s permissions.",
    ),
    Spec(
        25,
        "Type Hints and Static Checks",
        "Type hints make a function’s intended data flow visible to humans and tools. They improve review, but they do not validate runtime JSON, CSV, or CLI input.",
        "A reviewer needs to see which functions accept raw text, which accept validated events, and which return reports or errors.",
        "A **type annotation** describes intended types. A **static checker** analyzes code without running it. A `TypedDict` describes dictionary keys but does not enforce them at runtime.",
        (
            ex(
                "Annotate a function",
                "Annotations document the contract at the call site.",
                'def label(severity: int) -> str:\n    return "high" if severity >= 7 else "normal"',
                "Readers can see the input and output relationship.",
            ),
            ex(
                "Use a TypedDict",
                "A typed dictionary documents required fields.",
                "from typing import TypedDict\nclass Event(TypedDict):\n    source: str\n    severity: int",
                "The checker can reason about `event['source']`.",
            ),
            ex(
                "Optional values",
                "`None` must be handled before using a value as text.",
                'def source_name(source: str | None) -> str:\n    return source or "unknown"',
                "Missing source becomes an explicit display value.",
            ),
            ex(
                "Protocols by behavior",
                "A protocol can describe the method a dependency must provide.",
                "from typing import Protocol\nclass Reader(Protocol):\n    def read(self, limit: int) -> list[str]: ...",
                "Tests can provide a small fake reader.",
            ),
            ex(
                "Runtime validation still matters",
                "A dictionary from JSON can violate the annotation.",
                'raw: Event = {"source": "auth", "severity": "7"}  # type checker warning; runtime may still create it',
                "The annotation does not convert the string or reject it.",
            ),
        ),
        "Static analysis reads the declared contract, but external data crosses into Python at runtime. Validate first, then construct the typed internal record.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| type hints as validation | malformed input still runs | validate at runtime |\n| `Any` everywhere | checker provides no signal | narrow types at boundaries |\n| ignore every error | real design gaps disappear | explain justified ignores |\n| wrong `Optional` handling | `None` reaches string methods | branch or validate |\n| annotations without tests | type shape is right but behavior wrong | keep behavioral tests |",
        "Run the checker on local course modules and add runtime tests for malformed synthetic data. Do not paste real data into a static-analysis service.",
        "Type hints are a review map; runtime validation is the gate that external data must pass.",
        "Static checks cannot prove correctness, security, authorization, or package safety. They are one layer of evidence.",
    ),
    Spec(
        26,
        "Structured Logging and Redaction",
        "Logs are evidence for operators and input for future tools. Unstructured messages are hard to query; unredacted messages can leak secrets.",
        "Emit a machine-readable event with a stable schema while ensuring token, password, and private message values do not appear.",
        "A **log record** has fields such as time, level, event, and context. **Structured logging** emits fields rather than only prose. **Redaction** removes or masks sensitive values.",
        (
            ex(
                "Use logging levels",
                "Levels communicate importance to operators.",
                'import logging\nlogging.basicConfig(level=logging.INFO)\nlogging.info("triage_started")',
                "The logger emits a timestamped informational record.",
            ),
            ex(
                "Log fields carefully",
                "A structured dictionary keeps safe context separate from a secret.",
                'record = {"event": "token_check", "case_id": "training", "token_present": True}\nprint(record)',
                "Only presence is logged.",
            ),
            ex(
                "Redact known keys",
                "A field policy is more reliable than searching for one literal secret.",
                'SENSITIVE = {"password", "token", "api_key"}\ndef redact(record):\n    return {k: "[REDACTED]" if k in SENSITIVE else v for k, v in record.items()}',
                "Sensitive keys receive the marker.",
            ),
            ex(
                "Prevent newline injection",
                "A user-controlled message can forge visual log lines.",
                'def one_line(text):\n    return text.replace("\\r", "\\\\r").replace("\\n", "\\\\n")',
                "Newlines are represented instead of creating new records.",
            ),
            ex(
                "Add correlation context",
                "A case identifier connects records without copying raw evidence.",
                'log_record = {"case_id": "training-026", "event": "record_rejected", "reason": "bad severity"}',
                "The record can be searched by case and event.",
            ),
        ),
        "A record is assembled, sensitive keys are transformed, free text is made single-line, and only then is it emitted. Redaction must happen before formatting or serialization.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| log full request | secrets enter retained logs | log selected safe fields |\n| redact after formatting | alternate representations leak | redact structured data first |\n| user newline unescaped | fake records appear | neutralize line breaks |\n| no retention rule | evidence remains forever | define retention and access |\n| use logs as truth | collection error is ignored | record source and confidence |",
        "Create structured logs only from synthetic events. Test that secret values and newline payloads never appear in output, and document retention and access assumptions.",
        "A log is a durable data boundary; make its schema, redaction, provenance, and retention explicit.",
        "Redaction is not perfect if secrets appear in exception traces, process arguments, memory, or nested fields. Minimize collection as well as masking.",
    ),
    Spec(
        27,
        "Git and Code Review for Security Changes",
        "Version control is part of engineering evidence. A small reviewable commit helps a team understand what changed, why it changed, and how to revert it.",
        "Review a change to a parser or security rule without trusting the author’s description alone.",
        "A **diff** is a line-level change. A **commit** is a recorded snapshot. A **review** checks behavior, tests, scope, and risk before integration.",
        (
            ex(
                "Inspect status",
                "Start with the repository state before modifying anything.",
                "git status --short\ngit branch --show-current",
                "You see changed files and the active branch.",
            ),
            ex(
                "Read a diff",
                "A diff shows additions, deletions, and context.",
                "git diff -- course_days/day027.py",
                "The reviewer can focus on the actual changed lines.",
            ),
            ex(
                "Make a focused commit",
                "A commit should tell one coherent story.",
                'git add course_days/day027.py tests/test_day027.py\ngit commit -m "Validate evidence source"',
                "The source and its tests move together.",
            ),
            ex(
                "Review security questions",
                "A checklist prevents “tests pass” from being the only question.",
                'questions = ["What input is new?", "What is the trust boundary?", "What can leak?", "What is the rollback?"]\nprint(len(questions))',
                "Four review questions are visible.",
            ),
            ex(
                "Compare before and after",
                "A reviewer should inspect behavior, not only formatting.",
                'before = {"accepted": ["443"], "rejected": ["70000"]}\nafter = {"accepted": ["443"], "rejected": ["70000", "abc"]}\nprint(after)',
                "The added rejection is an observable behavior change.",
            ),
        ),
        "The review moves from status to diff to tests to threat questions to a focused commit. The repository becomes a record of engineering decisions.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| review only the title | dangerous line is missed | inspect the diff |\n| giant mixed commit | rollback is risky | split coherent changes |\n| no negative test | security claim is unproved | add rejection tests |\n| commit secrets | history retains them | scan and remove before commit |\n| approve based on authority | reviewer skips evidence | require reproducible checks |",
        "Practice on the course branch and synthetic fixtures. Never commit tokens, private logs, or generated evidence. If a secret enters Git history, stop and follow the repository security policy.",
        "A code review is a structured challenge to the change’s assumptions, not a vote on the author.",
        "Git records changes but does not make secrets disappear from history or guarantee that a review found every flaw.",
    ),
    Spec(
        28,
        "Dependency Hygiene and SBOM Thinking",
        "Python packages expand what a tool can do and what it must trust. Dependency hygiene makes versions, origins, licenses, and update decisions visible.",
        "Produce a small inventory for the course tools without treating a package name as proof of safety.",
        "A **dependency** is code your project relies on. An **SBOM** is a machine-readable inventory of components. A **transitive dependency** is pulled in by another dependency.",
        (
            ex(
                "List dependencies",
                "The project configuration is the starting point for an inventory.",
                'dependencies = ["pytest", "ruff", "mypy"]\nfor name in dependencies:\n    print(name)',
                "Each package is named explicitly.",
            ),
            ex(
                "Record a version",
                "A version makes a test result more reproducible.",
                'package = {"name": "pytest", "version": "reviewed-version", "purpose": "tests"}\nprint(package)',
                "The record has name, version, and purpose.",
            ),
            ex(
                "Separate runtime and development",
                "A production tool should not ship every teaching utility.",
                'runtime = []\ndevelopment = ["pytest", "ruff", "mypy"]\nprint(runtime, development)',
                "The two sets have different deployment implications.",
            ),
            ex(
                "Check a lock-like record",
                "A review can compare the declared record to the installed environment.",
                'declared = {"pytest"}\ninstalled = {"pytest", "unexpected-package"}\nprint(installed - declared)',
                "The unexpected package is visible for investigation.",
            ),
            ex(
                "State provenance questions",
                "An inventory is a starting point for review.",
                'questions = ["Where was it obtained?", "Who maintains it?", "What license applies?", "When was it reviewed?"]\nprint(questions)',
                "The checklist prevents “it installed” from becoming “it is trusted.”",
            ),
        ),
        "The project declares components, the environment reports installed components, and a review compares the two while recording provenance and purpose.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| latest always | updates introduce surprises | review and test updates |\n| package name only | typosquatting or confusion | verify source and provenance |\n| ignore transitive packages | hidden code enters the build | inventory the full environment |\n| no license record | distribution risk appears late | review license context |\n| install into system | unrelated projects change | use the project environment |",
        "Create an SBOM-like table for the course environment only. Do not upload private dependency reports or install packages from unverified commands.",
        "A dependency is part of the system’s trust boundary even when your code did not write it.",
        "An inventory does not prove a package is secure. Vulnerabilities, maintainer compromise, build tampering, and configuration risk remain possible.",
    ),
    Spec(
        29,
        "Threat Modeling Before Automation",
        "Threat modeling turns “make it secure” into explicit assets, threats, controls, assumptions, and residual risk before code makes the decision harder to change.",
        "Threat-model the log triage tool and identify what can be harmed, how, and which control reduces the risk.",
        "An **asset** is something worth protecting. A **threat** is a potential harmful action or condition. A **control** reduces likelihood or impact. **Residual risk** remains after controls.",
        (
            ex(
                "Name an asset",
                "Start with what the tool must protect.",
                'assets = ["synthetic evidence", "report integrity", "developer credentials"]\nprint(assets)',
                "The list makes scope concrete.",
            ),
            ex(
                "Draw a trust boundary",
                "Mark where data changes trust level.",
                'boundary = {"outside": "CLI path and fixture text", "inside": "validated event and report writer"}\nprint(boundary)',
                "The boundary identifies where validation belongs.",
            ),
            ex(
                "Describe a threat",
                "A threat statement names actor, action, asset, and impact.",
                'threat = {"actor": "malformed fixture", "action": "exhausts line processing", "asset": "tool availability", "impact": "slow or incomplete report"}',
                "The threat is specific enough to select a control.",
            ),
            ex(
                "Choose a control",
                "A control should connect directly to the threat.",
                'control = {"threat": threat, "measure": "line limit and truncation flag"}\nprint(control["measure"])',
                "The control is bounded processing plus honest reporting.",
            ),
            ex(
                "Record residual risk",
                "Controls change risk; they do not erase it.",
                'residual = "a maliciously shaped line may still be rejected and require review"\nprint(residual)',
                "The remaining uncertainty is visible.",
            ),
        ),
        "The model starts at asset, crosses a trust boundary, names a threat, chooses a control, and records what remains. It is a reasoning process, not a decorative table.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| list tools instead of threats | controls have no rationale | describe harmful conditions |\n| “secure” as a control | no testable behavior | name mechanism and evidence |\n| ignore availability | only confidentiality is discussed | include resource abuse and failure |\n| no owner | nobody maintains the control | identify responsibility |\n| residual risk omitted | report implies certainty | state limits and follow-up |",
        "Create a threat model for local synthetic evidence. Do not model or test a public target. Every proposed control needs one local test or inspection method.",
        "Threat modeling is disciplined uncertainty reduction: identify what matters, what can go wrong, and what evidence supports the chosen control.",
        "Threat models are hypotheses. They can miss threats, misunderstand assets, or become stale as the system changes.",
    ),
    Spec(
        30,
        "Project: Secure Evidence Journal",
        "A project makes the engineering habits visible in one artifact. The Secure Evidence Journal stores synthetic observations, preserves provenance, redacts sensitive fields, and records confidence without pretending to be a case-management system.",
        "Build a local JSON Lines journal that accepts synthetic entries, validates them, assigns an identifier, and exports a safe report.",
        "A **journal entry** is one immutable observation. **Provenance** says where and when it came from. **Confidence** describes the strength of an interpretation, not the guilt of a person.",
        (
            ex(
                "Define a record",
                "Start with fields that make an observation reviewable.",
                'entry = {"case_id": "training-030", "source": "fixture-a", "observed_at": "2026-08-20T10:00:00+00:00", "note": "login_failed"}',
                "The entry contains synthetic provenance and a neutral note.",
            ),
            ex(
                "Validate required fields",
                "Missing source or timezone makes later review weaker.",
                'required = {"case_id", "source", "observed_at", "note"}\nmissing = required - entry.keys()\nprint(missing)',
                "An empty set means the required keys exist.",
            ),
            ex(
                "Redact before export",
                "A report should contain only the fields it needs.",
                'safe = {key: entry[key] for key in ["case_id", "source", "observed_at"]}\nprint(safe)',
                "The note is omitted from this summary view.",
            ),
            ex(
                "Write JSON Lines",
                "One JSON object per line is easy to append and process incrementally.",
                "import json\nline = json.dumps(entry, sort_keys=True)\nprint(line)",
                "The record has a stable text representation.",
            ),
            ex(
                "State limitations",
                "A journal records observations; it does not establish truth.",
                'limitations = ["synthetic only", "no identity proof", "no chain of custody"]\nprint("; ".join(limitations))',
                "The report communicates scope honestly.",
            ),
        ),
        "The project pipeline is validate → preserve raw safe fields → derive an identifier → append JSON Lines → export a redacted report → test and reset. Every step should be inspectable.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| edit raw evidence | provenance is lost | append corrections as new entries |\n| store secrets | journal becomes sensitive | redact and minimize |\n| claim confidence is truth | interpretation becomes accusation | describe confidence and basis |\n| no reset | fixtures accumulate | document cleanup |\n| no schema version | future readers guess | include a version field |",
        "The journal uses only local synthetic entries, a dedicated output path, and a reset command. The README must include setup, schema, threat model, sample report, limitations, and tests.",
        "An evidence journal preserves what was observed and how it was transformed; it does not manufacture certainty.",
        "This project is not a forensic evidence system, legal record, or production case-management platform. Real evidence requires policy, access control, retention, and chain of custody.",
    ),
    Spec(
        31,
        "Processes and Safe System Calls",
        "Operating-system automation is powerful because it crosses from Python into another process. It is dangerous when arguments, environment, working directory, output, and lifetime are implicit.",
        "Run a harmless local command and capture its result without turning user input into shell syntax.",
        "A **process** is a running program. `subprocess.run` starts and waits for one. `argv` is the list of arguments. A **return code** reports process completion.",
        (
            ex(
                "Run an argument list",
                "Pass the program and each argument as separate data values.",
                'import subprocess\nresult = subprocess.run(["python", "--version"], capture_output=True, text=True, check=False)\nprint(result.returncode)',
                "Usually `0` for a successful local interpreter call.",
            ),
            ex(
                "Capture output",
                "Captured output can be tested instead of printed blindly.",
                'result = subprocess.run(["python", "-c", "print(\'training\')"], capture_output=True, text=True)\nprint(result.stdout.strip())',
                "`training`",
            ),
            ex(
                "Check failure explicitly",
                "A non-zero return code is data the caller must handle.",
                'result = subprocess.run(["python", "-c", "raise SystemExit(2)"], capture_output=True, text=True)\nprint(result.returncode)',
                "`2`",
            ),
            ex(
                "Set a working directory",
                "The current directory affects relative paths and should be explicit.",
                'result = subprocess.run(["python", "-c", "import pathlib; print(pathlib.Path.cwd())"], cwd="shared/fixtures", capture_output=True, text=True)',
                "The child prints the approved fixture directory.",
            ),
            ex(
                "Use a timeout",
                "A child process must not run forever.",
                'subprocess.run(["python", "-c", "import time; time.sleep(1)"], timeout=2)',
                "The process finishes within the bound.",
            ),
        ),
        "Python creates the child with the chosen argv, cwd, environment, capture settings, and timeout; it returns a result or raises a timeout/OS error. Each option changes the trust boundary.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| `shell=True` with input | input becomes shell syntax | use argv lists |\n| inherit current directory | relative path escapes scope | set `cwd` |\n| ignore return code | failure looks successful | inspect or use `check=True` deliberately |\n| capture unlimited output | memory grows | cap or stream output |\n| no timeout | process hangs | set a finite timeout |",
        "Run only interpreters or harmless commands against the course fixture. Never turn this lesson into a scanner or remote command runner.",
        "A subprocess call is an operating-system trust boundary whose command, arguments, directory, environment, output, and lifetime must be explicit.",
        "Even `shell=False` does not make a command safe if the executable, arguments, privileges, or working directory are unsafe.",
    ),
    Spec(
        32,
        "Linux Command-Line Concepts",
        "Security engineers need a shell mental model before automating it. Understanding paths, streams, exit statuses, and pipes helps a learner inspect a local system without treating commands as magic incantations.",
        "Use harmless commands to inspect the repository and connect their outputs to Python’s process model.",
        "A **shell** starts programs and connects streams. `stdout` is normal output. `stderr` is diagnostic output. A **pipe** sends one process’s output to another.",
        (
            ex(
                "Print the current directory",
                "A relative path has meaning only relative to the current working directory.",
                "pwd",
                "The shell prints the absolute working directory.",
            ),
            ex(
                "List deliberately",
                "Start with visible, bounded directory contents.",
                "ls -la shared/fixtures",
                "The command lists the fixture directory; inspect before acting.",
            ),
            ex(
                "Search text",
                "`grep` filters text but should be used on authorized local fixtures.",
                'grep -n "severity" shared/fixtures/events.log',
                "Matching lines appear with line numbers.",
            ),
            ex(
                "Inspect exit status",
                "A command can fail even when the shell displays output.",
                'grep -q "missing" shared/fixtures/events.log\necho $?',
                "A non-zero status means the pattern was not found.",
            ),
            ex(
                "Connect streams conceptually",
                "Pipelines transform output, but each stage needs bounded inputs.",
                'printf "ok\\nfailed\\n" | grep failed',
                "`failed` is selected from synthetic text.",
            ),
        ),
        "The shell resolves a command, opens streams, runs it in the current directory, and stores an exit status. Python can reproduce the process while making argv and cwd more explicit.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| wrong directory | command sees wrong files | run `pwd` first |\n| `rm` while learning | data is destroyed | inspect with `ls` and use resettable fixtures |\n| pipe hides failure | final output looks fine | inspect each status or use Python stages |\n| quote confusion | arguments split unexpectedly | understand shell quoting and prefer argv lists in Python |\n| public target | unauthorized activity | restrict to local fixtures |",
        "Use only repository fixtures. Do not run enumeration, scanning, or destructive commands; the goal is streams and process reasoning.",
        "The shell is a language that creates processes and connects streams; Python automation should make that implicit behavior visible.",
        "Shell behavior differs by platform and shell implementation. Production automation needs a supported command set and explicit error handling.",
    ),
    Spec(
        33,
        "Paths, File Metadata, and Symlinks",
        "A file’s content is not its only property. Size, mode, owner, modification time, and link status affect how a security tool should handle it.",
        "Inspect metadata of local fixture files without following an unexpected link or assuming that a name identifies one object.",
        "Metadata describes a file object. A **symlink** points to another path. A **mode** describes permission bits. `stat` reports file metadata.",
        (
            ex(
                "Read basic metadata",
                "`Path.stat` returns size and timestamps.",
                'from pathlib import Path\npath = Path("shared/fixtures/events.log")\ninfo = path.stat()\nprint(info.st_size)',
                "A non-negative byte count.",
            ),
            ex(
                "Check a regular file",
                "A tool should decide whether directories, devices, and links are allowed.",
                "print(path.is_file(), path.is_dir())",
                "The fixture is a regular file and not a directory.",
            ),
            ex(
                "Inspect without following",
                "`lstat` describes the link itself when the path is a symlink.",
                "info = path.lstat()\nprint(info.st_mode)",
                "The mode can be inspected before opening.",
            ),
            ex(
                "Hash a fixture",
                "A digest identifies content changes but is not secrecy or authenticity.",
                "import hashlib\ndigest = hashlib.sha256(path.read_bytes()).hexdigest()\nprint(digest[:12])",
                "A short display prefix for a synthetic file.",
            ),
            ex(
                "Compare before and after",
                "Metadata and hashes can support a local baseline.",
                "before = path.stat().st_size\n# change a local fixture deliberately, then measure again\nafter = path.stat().st_size\nprint(before, after)",
                "A change is observable and should be explained.",
            ),
        ),
        "A path lookup returns an object whose metadata can be inspected; a link may redirect the lookup, so the tool must choose follow or no-follow behavior before reading.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| name equals object | symlink or replacement is missed | inspect link and resolved target |\n| hash proves integrity | digest is treated as authenticity | compare against a trusted reference |\n| timestamps equal causation | order is overclaimed | state clock limitations |\n| read everything for metadata | unnecessary data exposure | inspect metadata first |\n| assume POSIX permissions | Windows behavior differs | document platform scope |",
        "Inspect only local fixture metadata. Do not change permissions or follow links outside the repository. Record what the baseline can and cannot show.",
        "File metadata is context for a decision, not a verdict; inspect the object, the path resolution, and the source of the baseline.",
        "Metadata can be changed, clocks can be wrong, and a hash without trusted provenance is only a fingerprint.",
    ),
    Spec(
        34,
        "Safe Subprocess Allowlisting",
        "Day 31 showed how to start a process; this day turns that knowledge into a safer design. A command runner should allow a small set of known operations instead of accepting arbitrary executable input.",
        "Build a local command adapter that supports one or two harmless inventory commands and rejects everything else.",
        "An **allowlist** permits named safe cases. A **denylist** tries to enumerate unsafe cases. An **argv list** keeps arguments separate from shell parsing.",
        (
            ex(
                "Allow one command",
                "Map a friendly operation to a fixed argv list.",
                'COMMANDS = {"python-version": ["python", "--version"]}\nprint(COMMANDS["python-version"])',
                "The user chooses a key, not an executable string.",
            ),
            ex(
                "Reject unknown keys",
                "Fail before starting a process.",
                'def command_for(name):\n    try:\n        return COMMANDS[name].copy()\n    except KeyError as error:\n        raise ValueError("operation is not allowed") from error',
                "An unknown operation is rejected.",
            ),
            ex(
                "Constrain arguments",
                "Even an allowed executable may accept unsafe arguments.",
                'def python_check(script):\n    if script != "import sys; print(sys.version_info[:2])":\n        raise ValueError("script is not allowed")\n    return ["python", "-c", script]',
                "Only the exact local check is accepted.",
            ),
            ex(
                "Set environment",
                "Do not inherit more environment than necessary.",
                'safe_env = {"PATH": "/usr/bin:/bin"}\nprint(sorted(safe_env))',
                "The child receives a deliberately small environment.",
            ),
            ex(
                "Bound output",
                "Capture only a limited amount of output before reporting truncation.",
                "def preview(text, limit=4096):\n    return text[:limit], len(text) > limit",
                "The caller can display `truncated=True`.",
            ),
        ),
        "The friendly operation maps to fixed data, the adapter validates the key and arguments, starts with an explicit cwd/environment, and caps output and lifetime.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| denylist | a new dangerous command bypasses it | allowlist |\n| executable from input | arbitrary code runs | map names to fixed argv |\n| inherited environment | secrets enter child | pass a minimal environment |\n| inherited privileges | child can do too much | drop privilege or refuse |\n| output stored forever | sensitive output persists | cap, redact, and clean up |",
        "The adapter may run only harmless local inventory commands. It must reject shell metacharacters, remote destinations, arbitrary scripts, and unknown operation names.",
        "Safe automation narrows the language accepted at the process boundary until only the intended operation remains.",
        "Allowlisting is a design control, not proof that the allowed command is safe on every platform or with every dependency.",
    ),
    Spec(
        35,
        "Users, Permissions, and Least Privilege",
        "A process runs with an identity and permissions. Security automation must understand the difference between needing access and being entitled to broaden access.",
        "Inspect the current local user and a fixture’s permission metadata without changing the machine’s security settings.",
        "An **identity** is the account associated with a process. **Permission** controls an operation. **Least privilege** grants only what the task needs.",
        (
            ex(
                "Read the current user",
                "A diagnostic can identify context without exposing credentials.",
                "import getpass\nprint(getpass.getuser())",
                "A username, not a password.",
            ),
            ex(
                "Inspect a mode",
                "POSIX mode bits can be displayed as metadata.",
                'from pathlib import Path\nprint(oct(Path("shared/fixtures/events.log").stat().st_mode))',
                "An octal mode representation.",
            ),
            ex(
                "Check readability",
                "The program can test a capability before attempting work.",
                'path = Path("shared/fixtures/events.log")\nprint(path.is_file())',
                "The fixture exists as a file; actual access can still fail.",
            ),
            ex(
                "Avoid privilege escalation",
                "A tool should report insufficient access rather than silently asking for more.",
                'def require_readable(path):\n    if not path.is_file():\n        raise PermissionError("fixture is not a readable regular file")\n    return path',
                "The caller receives a clear failure path.",
            ),
            ex(
                "Document permissions",
                "A README should say what permissions the tool expects.",
                'requirements = {"read": "fixture files", "write": "training-output", "admin": "none"}\nprint(requirements)',
                "The tool explicitly needs no administrator access.",
            ),
        ),
        "The process identity is inherited from the launcher; the tool inspects capability, performs only the required operation, and reports a permission error instead of escalating.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| run as administrator | a bug has greater impact | use ordinary user privileges |\n| chmod broadly | unrelated files become exposed | change only a disposable fixture if authorized |\n| log username plus secrets | identity data leaks | minimize context |\n| assume platform mode | Windows and POSIX differ | state platform assumptions |\n| permission equals legitimacy | access is treated as authorization | require explicit scope |",
        "Use the current sandbox and synthetic fixture only. Do not alter system users, groups, ACLs, or permissions as part of the exercise.",
        "Identity and capability describe what a process can do; authorization describes what it is allowed to do.",
        "Permission APIs vary by operating system, containers, filesystems, and ACLs. A local check is not a complete access-control review.",
    ),
    Spec(
        36,
        "Timeouts, Resource Limits, and Backpressure",
        "A security tool can fail by doing too much work. Timeouts, maximum sizes, and backpressure turn resource behavior into an explicit contract.",
        "Run a bounded local task and show how the caller reacts when the task exceeds the allowed time or output budget.",
        "A **timeout** limits elapsed time. A **resource limit** bounds work or memory. **Backpressure** slows producers when consumers cannot keep up.",
        (
            ex(
                "Set a timeout",
                "The caller should not wait forever for a child.",
                'import subprocess\nsubprocess.run(["python", "-c", "print(\'ok\')"], timeout=2)',
                "The task completes within two seconds.",
            ),
            ex(
                "Handle timeout",
                "A timeout is a distinct result that should be reported.",
                'try:\n    subprocess.run(["python", "-c", "import time; time.sleep(2)"], timeout=0.1)\nexcept subprocess.TimeoutExpired:\n    print("timed out")',
                "`timed out`",
            ),
            ex(
                "Bound bytes",
                "A byte budget prevents a large result from filling memory.",
                "def bounded_bytes(data, limit):\n    return data[:limit], len(data) > limit",
                "The result includes both a preview and a truncation signal.",
            ),
            ex(
                "Use a queue bound",
                "A bounded queue applies backpressure to producers.",
                'from queue import Queue\nqueue = Queue(maxsize=2)\nqueue.put("event")\nprint(queue.qsize())',
                "The queue reports one pending event.",
            ),
            ex(
                "Choose a policy",
                "A timeout should lead to an explicit status, not a silent empty result.",
                'result = {"status": "timed_out", "complete": False}\nprint(result)',
                "The report says work was incomplete.",
            ),
        ),
        "The operation starts with finite time and output budgets; when a budget is reached, the tool records incomplete work and releases resources.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| timeout only the parent | child continues | terminate and clean up the child |\n| no output cap | memory grows | stream or truncate |\n| unbounded queue | producer overwhelms consumer | set `maxsize` |\n| retry immediately | overload worsens | use bounded retries and backoff |\n| report empty success | missing data is hidden | state timeout/truncation |",
        "Use short local sleeps and small synthetic outputs. Do not create load against another system or use resource experiments that could affect the host.",
        "A limit is part of correctness: incomplete work must be visible, and cleanup must happen when the limit is reached.",
        "Limits can create false negatives. Production systems need capacity planning, cancellation semantics, and monitoring in addition to a number in code.",
    ),
    Spec(
        37,
        "Processes, Threads, and Queues",
        "Concurrency can reduce waiting time, but it also creates shared state, ordering, cancellation, and resource problems. A security tool should prefer predictable bounded concurrency over maximum parallelism.",
        "Process several local fixture items with a small worker pool and preserve a safe result for each item.",
        "A **thread** shares memory within one process. A **process** has a separate memory space. A **queue** coordinates producers and consumers. A **race condition** occurs when outcome depends on timing.",
        (
            ex(
                "Use a thread pool",
                "Threads suit small I/O waits in a local fixture.",
                'from concurrent.futures import ThreadPoolExecutor\nwith ThreadPoolExecutor(max_workers=2) as pool:\n    results = list(pool.map(str.upper, ["a", "b"]))\nprint(results)',
                "`['A', 'B']`",
            ),
            ex(
                "Use a process pool carefully",
                "Separate processes have higher overhead and clearer memory boundaries.",
                "from concurrent.futures import ProcessPoolExecutor\nwith ProcessPoolExecutor(max_workers=2) as pool:\n    results = list(pool.map(abs, [-2, 3]))\nprint(results)",
                "`[2, 3]`",
            ),
            ex(
                "Bound work",
                "The worker count is an explicit resource choice.",
                "max_workers = min(4, 2)\nprint(max_workers)",
                "The tool never creates an unbounded number of workers.",
            ),
            ex(
                "Queue a result",
                "A queue can separate collection from processing.",
                'from queue import Queue\nqueue = Queue()\nqueue.put({"status": "accepted"})\nprint(queue.get())',
                "The result moves through the queue.",
            ),
            ex(
                "Preserve errors",
                "A worker failure must be returned or raised, not silently discarded.",
                'def safe_call(function, value):\n    try:\n        return {"ok": True, "value": function(value)}\n    except Exception as error:\n        return {"ok": False, "error": type(error).__name__}',
                "The caller can count failed work.",
            ),
        ),
        "The coordinator creates a bounded set of workers, submits local work, collects results, and shuts down the pool. Ordering and failure behavior are part of the report contract.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| one worker per item | resource exhaustion | cap workers |\n| shared mutable state | results depend on timing | return values or protect state |\n| swallow worker errors | incomplete report looks successful | preserve error records |\n| assume order | output changes run to run | attach identifiers and sort explicitly |\n| no shutdown | threads/processes remain | use a context manager |",
        "Run concurrency only over local synthetic records. Do not use it to increase scanning, guessing, or request volume against another system.",
        "Concurrency is a coordination problem with a resource budget, not a magic speed switch.",
        "Concurrency bugs can be nondeterministic and platform-dependent. Tests should use small deterministic fixtures and explicit synchronization.",
    ),
    Spec(
        38,
        "Async I/O and Bounded Awaiting",
        "Asynchronous code lets one task wait while another makes progress, but it introduces cancellation, ordering, and concurrency limits. It is useful for cooperative local I/O, not a reason to remove authorization.",
        "Run several local coroutines with a semaphore and collect successes, failures, and cancellation cleanly.",
        "A **coroutine** is an awaitable computation. `await` yields control. A **task** schedules a coroutine. A **semaphore** limits concurrent entry.",
        (
            ex(
                "Define a coroutine",
                "Calling an async function creates a coroutine; awaiting runs it.",
                'import asyncio\nasync def label(value):\n    await asyncio.sleep(0)\n    return value.upper()\nprint(asyncio.run(label("ok")))',
                "`OK`",
            ),
            ex(
                "Gather tasks",
                "`gather` waits for several awaitables.",
                'async def main():\n    values = await asyncio.gather(label("a"), label("b"))\n    print(values)\nasyncio.run(main())',
                "`['A', 'B']`",
            ),
            ex(
                "Bound concurrency",
                "A semaphore keeps only a small number of tasks inside a resource section.",
                "limit = asyncio.Semaphore(2)\nasync def bounded_work(value):\n    async with limit:\n        await asyncio.sleep(0)\n        return value",
                "At most two calls enter the section at once.",
            ),
            ex(
                "Handle cancellation",
                "Cancellation is a normal lifecycle event that needs cleanup.",
                'async def safe_task():\n    try:\n        await asyncio.sleep(1)\n    except asyncio.CancelledError:\n        print("cancelled")\n        raise',
                "The task reports cancellation and re-raises it.",
            ),
            ex(
                "Preserve result identity",
                "Attach an identifier because completion order may differ from input order.",
                'results = {"fixture-a": {"status": "ok"}}\nprint(results)',
                "The caller can merge results deterministically.",
            ),
        ),
        "The event loop schedules awaitable work; the semaphore limits concurrent operations; cancellation and exceptions become explicit result states.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| call async function without await | coroutine never runs | await or schedule it |\n| unbounded gather | too many tasks | use a semaphore and batch |\n| ignore cancellation | cleanup is skipped | use `try/finally` and re-raise |\n| assume completion order | records mismatch | keep identifiers |\n| mix blocking I/O | event loop stalls | isolate or use async-compatible APIs |",
        "Use `asyncio.sleep` and local fixtures only. Do not turn an async example into a high-volume network client or use it against unapproved endpoints.",
        "Async I/O is cooperative scheduling with explicit limits, cancellation, and result identity.",
        "Async code does not make operations harmless, faster in every workload, or safe to direct at a public system.",
    ),
    Spec(
        39,
        "Host Inventories and Baseline Data",
        "An inventory describes what a tool observed about a host or fixture at one point in time. Baselines help identify change, but only when collection scope, normalization, and comparison are clear.",
        "Create a local host-like inventory from synthetic data and compare two snapshots without claiming that a difference is malicious.",
        "An **inventory** is a structured list of observed properties. A **baseline** is a reference snapshot. **Drift** is a difference between observations.",
        (
            ex(
                "Model a host",
                "A dictionary can represent a small inventory before a dataclass is introduced.",
                'host = {"name": "training-host", "os": "fixture", "services": ["python"]}\nprint(host)',
                "The host is explicitly synthetic.",
            ),
            ex(
                "Normalize a service list",
                "Sorting makes comparison deterministic.",
                'services = ["ssh", "python", "ssh"]\nnormalized = sorted(set(services))\nprint(normalized)',
                "`['python', 'ssh']`",
            ),
            ex(
                "Compare snapshots",
                "A set difference shows observed change.",
                'before = {"python", "ssh"}\nafter = {"python", "web"}\nprint("added", after - before)\nprint("removed", before - after)',
                "`web` is added and `ssh` is removed.",
            ),
            ex(
                "Record collection scope",
                "A baseline without scope is hard to interpret.",
                'snapshot = {"scope": "course fixture only", "observed": {"python"}}\nprint(snapshot["scope"])',
                "The scope travels with the observation.",
            ),
            ex(
                "State confidence",
                "A difference needs a review state, not an automatic accusation.",
                'finding = {"change": "service added", "status": "needs_review", "confidence": "medium"}\nprint(finding)',
                "The change is a review item.",
            ),
        ),
        "Collection normalizes local observations into a snapshot; comparison computes differences; a human or policy decides what the difference means.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| baseline without date | change cannot be placed in time | record timestamp |\n| normalize away detail | evidence is lost | keep raw plus comparison form |\n| difference equals attack | drift is overinterpreted | use needs-review status |\n| collect beyond scope | inventory becomes surveillance | define allowed properties |\n| no baseline provenance | reference may be untrusted | record source and method |",
        "Use synthetic host dictionaries and repository fixtures. Do not enumerate the actual host, network, processes, or accounts beyond what the lesson explicitly permits.",
        "A baseline makes change visible; judgment and provenance determine what the change means.",
        "Baselines can be incomplete, stale, or wrong. A difference is a lead for review, not a compromise verdict.",
    ),
    Spec(
        40,
        "Project: Host Baseline Auditor",
        "The project combines operating-system concepts into a local, bounded auditor. It should collect a small approved inventory, compare it to a synthetic baseline, and produce explainable drift without destructive action.",
        "Build a host baseline auditor for a fixture representation, with explicit scope, deterministic output, tests, and a resettable report.",
        "An **auditor** compares observed state with an expected baseline. A **control** defines what is allowed. A **finding** describes a difference and its evidence.",
        (
            ex(
                "Define the baseline",
                "The baseline is data with scope and version, not a hidden assumption.",
                'baseline = {"version": 1, "scope": ["python_version", "fixture_files"], "python_version": "3.x"}\nprint(baseline)',
                "The expected state is visible.",
            ),
            ex(
                "Collect bounded state",
                "The auditor should collect only the properties it has permission to inspect.",
                'observed = {"python_version": "3.x", "fixture_files": ["events.log"]}\nprint(observed)',
                "The observed state matches the declared scope.",
            ),
            ex(
                "Compare fields",
                "Each comparison should name its field and evidence.",
                'findings = []\nif observed["python_version"] != baseline["python_version"]:\n    findings.append({"field": "python_version", "status": "changed"})\nprint(findings)',
                "No finding when the values match.",
            ),
            ex(
                "Handle missing state",
                "Missing data is not the same as compliant state.",
                'if "fixture_files" not in observed:\n    findings.append({"field": "fixture_files", "status": "not_observed"})',
                "The report preserves uncertainty.",
            ),
            ex(
                "Write the project report",
                "A report needs scope, timestamp, findings, limitations, and reset instructions.",
                'report = {"scope": baseline["scope"], "findings": findings, "complete": True}\nprint(report)',
                "The artifact is reviewable and bounded.",
            ),
        ),
        "The auditor loads the versioned baseline, collects only approved local fixture state, normalizes it, compares field by field, reports changed/missing/not-observed states, and writes a safe report.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| audit everything | scope and privacy fail | define an allowlist of properties |\n| missing equals compliant | blind spots look safe | report not observed |\n| destructive remediation | audit changes the system | report first; remediate separately |\n| nondeterministic output | diffs are noisy | sort and normalize |\n| no reset | generated reports accumulate | document cleanup |",
        "The project is fixture-only and read-only. It must not alter permissions, services, processes, accounts, or network settings. Its README must include scope, baseline version, sample output, tests, limitations, and reset.",
        "An auditor produces a bounded comparison between an approved baseline and an observed snapshot; it does not own the system or decide intent.",
        "A baseline auditor cannot prove continuous compliance, detect every change, or safely remediate production systems without additional controls and authorization.",
    ),
]


def render(spec: Spec) -> str:
    previous_dir = (
        DIRS[spec.day - 1] if spec.day > 21 else "day_20_project__log_triage_cli"
    )
    next_dir = DIRS[spec.day + 1]
    lines = [
        f"# Day {spec.day}: {spec.title}",
        "",
        f"[← Day {spec.day - 1}]({{../{previous_dir}/{previous_dir}.md}}) · [Day index](../DAY_INDEX.md) · [Day {spec.day + 1} →](../{next_dir}/{next_dir}.md)",
        "",
        "## Table of Contents",
        "",
        "- [Why this lesson exists](#why-this-lesson-exists)",
        "- [Prerequisites](#prerequisites)",
        "- [Outcomes](#outcomes)",
        "- [The problem](#the-problem)",
        "- [Security boundary](#security-boundary)",
        "- [Lesson](#lesson)",
        "- [Vocabulary](#vocabulary)",
        "- [Worked examples](#worked-examples)",
        "- [Execution trace](#execution-trace)",
        "- [Common mistakes](#common-mistakes)",
        "- [Security application](#security-application)",
        "- [Exercises](#exercises)",
        "- [Finish line](#finish-line)",
        "",
        "## Why this lesson exists",
        "",
        spec.why,
        "",
        "## Prerequisites",
        "",
        f"Complete Day {spec.day - 1} and run the phase checks. The lesson assumes you can read a traceback, use a virtual environment, and work only with the supplied repository fixtures.",
        "",
        "## Outcomes",
        "",
        "By the end of this lesson, you can:",
        "",
        "- explain the concept in plain language and precise Python terms",
        "- run and modify each worked example",
        "- test a normal case, boundary case, and failure case",
        f"- apply the idea to the safe local context described by Day {spec.day}",
        "",
        "## The problem",
        "",
        spec.problem,
        "",
        "## Security boundary",
        "",
        "Use only local synthetic fixtures and explicitly authorized course files. The lesson does not authorize public scanning, credential use, remote command execution, or changes to operating-system state.",
        "",
        "## Lesson",
        "",
        "### Vocabulary",
        "",
        spec.vocabulary,
        "",
        "## Worked examples",
        "",
    ]
    for index, (title, explanation, code, output) in enumerate(spec.examples, 1):
        lines += [
            f"### Example {index}: {title}",
            "",
            explanation,
            "",
            "```python",
            code,
            "```",
            "",
            "**What to observe:**",
            "",
            output,
            "",
        ]
    lines += [
        "## Execution trace",
        "",
        spec.trace,
        "",
        "## Common mistakes",
        "",
        spec.mistakes,
        "",
        "## Security application",
        "",
        spec.security,
        "",
        "## Exercises",
        "",
        "Complete the numbered questions in [practice/exercises.md](practice/exercises.md) in order. Run every requested command, create the requested artifact, and record the limitation the exercise asks you to name.",
        "",
        "## Finish line",
        "",
        f"Run `python -m course_days.day{spec.day:03d}`, pass the relevant tests, complete the numbered exercises, and explain one edge case aloud or in writing.",
        "",
        "## Mental model",
        "",
        f"> {spec.mental}",
        "",
        "## Limitations",
        "",
        spec.limits,
        "",
        f"[← Day {spec.day - 1}]({{../{previous_dir}/{previous_dir}.md}}) · [Day index](../DAY_INDEX.md) · [Day {spec.day + 1} →](../{next_dir}/{next_dir}.md)",
        "",
    ]
    return "\n".join(lines).replace("{", "{").replace("}", "}")


def main() -> int:
    for spec in SPECS:
        directory = ROOT / DIRS[spec.day]
        path = directory / f"{directory.name}.md"
        text = render(spec).replace("({../", "(../").replace(".md})", ".md)")
        path.write_text(text, encoding="utf-8")
    print("Authored dense teaching chapters for Days 21–40.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
