"""Author dense teaching chapters for Days 61–80."""

from __future__ import annotations

# ruff: noqa: E501
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRS = {
    60: "day_60_project__tamper_evident_case_bundle",
    61: "day_61_local_service_architecture",
    62: "day_62_request_parsing_and_validation",
    63: "day_63_authentication_and_authorization",
    64: "day_64_injection_and_parameterized_queries",
    65: "day_65_xss_and_output_encoding",
    66: "day_66_csrf__cookies__and_cors",
    67: "day_67_ssrf_and_outbound_controls",
    68: "day_68_misconfiguration_and_defaults",
    69: "day_69_supply_chain_and_exceptional_conditions",
    70: "day_70_project__secure_case_api",
    71: "day_71_telemetry_and_event_schemas",
    72: "day_72_log_normalization",
    73: "day_73_ioc_enrichment",
    74: "day_74_detection_thresholds",
    75: "day_75_mitre_att_ck_mapping",
    76: "day_76_alert_triage",
    77: "day_77_baselines_and_anomalies",
    78: "day_78_threat_intelligence_provenance",
    79: "day_79_analyst_reporting",
    80: "day_80_project__mini_detection_pipeline",
    81: "day_81_response_lifecycle",
}


@dataclass(frozen=True)
class Spec:
    day: int
    title: str
    why: str
    problem: str
    vocabulary: str
    examples: tuple[tuple[str, str, str, str], ...]
    trace: str
    mistakes: str
    security: str
    mental: str
    limits: str


def e(title: str, teaching: str, code: str, result: str):
    return title, teaching, code, result


SPECS = [
    Spec(
        61,
        "Local Service Architecture",
        "A web service is a pipeline of request parsing, validation, authorization, business logic, and response construction. Drawing those boundaries before coding makes security behavior testable.",
        "Sketch a local case API that accepts a request, validates it, checks authorization, and returns a safe response without touching a real account.",
        "A request is untrusted input. A handler coordinates work. A service layer applies policy. A repository stores data. A response is an output boundary.",
        (
            e(
                "Draw the flow",
                "Make the stages visible before implementation.",
                'stages = ["request", "parse", "validate", "authorize", "service", "response"]\nprint(" -> ".join(stages))',
                "The request path is explicit.",
            ),
            e(
                "Use a typed request",
                "A boundary object separates raw data from internal fields.",
                'request = {"case_id": "training-061", "action": "read"}\nprint(request)',
                "The raw input is still subject to validation.",
            ),
            e(
                "Return a result",
                "Handlers should return data and status rather than print.",
                'response = {"status": 200, "body": {"case_id": "training-061"}}\nprint(response)',
                "The response is structured.",
            ),
            e(
                "Name a trust boundary",
                "The service should state where authorization is checked.",
                'boundary = {"untrusted": "HTTP body", "trusted_after": "validated authorization decision"}\nprint(boundary)',
                "The policy location is visible.",
            ),
            e(
                "Keep local scope",
                "A training service needs an explicit target and reset.",
                'scope = {"host": "127.0.0.1", "data": "synthetic", "reset": "delete training DB"}\nprint(scope)',
                "The service is bounded.",
            ),
        ),
        "The request enters as bytes or text, becomes a parsed object, passes schema and authorization checks, reaches a service function, and returns a minimal response. No stage should silently skip the previous boundary.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| auth in UI only | direct calls bypass it | enforce at service boundary |\n| handler does everything | tests and review are hard | separate layers |\n| return raw exception | internal data leaks | safe error response |\n| global mutable state | tests affect each other | explicit dependencies |\n| local API becomes public | scope expands | bind to loopback and document |",
        "Build only a local synthetic API. Do not add account management, public deployment, credential collection, or real case data.",
        "A service is a sequence of trust-boundary transitions; each transition must validate, authorize, and preserve evidence.",
        "Architecture diagrams are hypotheses until tests and deployment configuration enforce the boundaries.",
    ),
    Spec(
        62,
        "Request Parsing and Validation",
        "Web input arrives as bytes, headers, path segments, query values, and bodies. Parsing creates structure; validation decides whether that structure is acceptable.",
        "Validate a synthetic JSON request with required fields, bounds, and unknown-field policy before it reaches a service function.",
        "Parsing extracts structure. Validation checks type and policy. A schema describes shape. Canonical errors avoid leaking implementation details.",
        (
            e(
                "Parse JSON",
                "Parsing creates ordinary values but does not validate them.",
                'import json\nraw = \'{"case_id": "training-062", "limit": 10}\'\nrecord = json.loads(raw)\nprint(record)',
                "A dictionary is produced.",
            ),
            e(
                "Require an object",
                "The endpoint should reject a list when an object is expected.",
                'if not isinstance(record, dict):\n    raise ValueError("body must be an object")',
                "The wrong top-level shape fails early.",
            ),
            e(
                "Check required fields",
                "A missing field is different from an empty value.",
                'required = {"case_id", "limit"}\nprint(required - record.keys())',
                "An empty set means keys exist.",
            ),
            e(
                "Bound a field",
                "Limits prevent resource abuse and ambiguous behavior.",
                'limit = int(record["limit"])\nif not 1 <= limit <= 100:\n    raise ValueError("limit outside allowed range")',
                "10 is accepted; 0 and 101 are rejected.",
            ),
            e(
                "Reject unknown fields",
                "A strict schema prevents accidental policy bypass through ignored data.",
                'allowed = {"case_id", "limit"}\nunknown = set(record) - allowed\nprint(unknown)',
                "The caller can choose to reject unknown keys.",
            ),
        ),
        "The raw body is parsed, top-level type is checked, keys are compared to schema, values are converted and bounded, and only the validated model enters the service layer.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| parse equals validate | malformed data reaches policy | validate separately |\n| ignore unknown fields | caller smuggles unsupported intent | reject or document them |\n| huge string accepted | memory or storage abuse | bound length |\n| generic `except` | programmer bugs look like input errors | catch expected parse errors |\n| error echoes body | sensitive input leaks | return field-level safe errors |",
        "Use local JSON fixtures and test malformed JSON, missing fields, wrong types, unknown fields, and oversized values.",
        "Parsing answers what structure arrived; validation answers whether the application will accept it.",
        "Validation cannot prove that the caller is authorized or that the data is truthful.",
    ),
    Spec(
        63,
        "Authentication and Authorization",
        "Authentication asks who or what is calling. Authorization asks whether that identity may perform this action on this resource. Confusing them creates security gaps.",
        "Model a local case-read request with a fictional identity, role, resource owner, and explicit authorization decision.",
        "Authentication establishes an identity claim. Authorization evaluates a policy. A role is a group of permissions. An object-level check compares the requested resource to the caller’s allowed scope.",
        (
            e(
                "Represent identity",
                "The identity object should not contain a password.",
                'identity = {"subject": "student-63", "roles": ["analyst"]}\nprint(identity)',
                "The subject and roles are explicit.",
            ),
            e(
                "Define a permission",
                "Permissions should name action and resource.",
                'permission = {"action": "read", "resource": "case"}\nprint(permission)',
                "A policy can compare these fields.",
            ),
            e(
                "Check role policy",
                "A role check is only one layer.",
                'allowed_roles = {"analyst", "mentor"}\nprint(set(identity["roles"]) & allowed_roles)',
                "The intersection is non-empty for the fictional identity.",
            ),
            e(
                "Check the object",
                "The caller must be allowed to access this specific case.",
                'request = {"subject": "student-63", "case_id": "training-63"}\nowned = {"student-63": {"training-63"}}\nprint(request["case_id"] in owned[request["subject"]])',
                "The object decision is explicit.",
            ),
            e(
                "Fail closed",
                "Missing identity or permission should not become anonymous access.",
                'if not identity or not permission:\n    raise PermissionError("authorization required")',
                "The request stops before the service.",
            ),
        ),
        "The request presents an identity claim, authentication verifies it outside the business rule, authorization checks action and object scope, and only then does the service run.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| identity equals permission | every authenticated user can act | check action and object |\n| role-only check | horizontal access leak | compare resource scope |\n| client-side authorization | direct API call bypasses it | enforce server-side |\n| fail open | missing identity gets access | fail closed |\n| log credentials | authentication material leaks | log subject and outcome only |",
        "Use fictional identities and cases. Do not implement login collection or connect to a real identity provider in the lesson.",
        "Authentication names a caller; authorization limits what that caller may do here and now.",
        "A code sample cannot prove identity, protect sessions, or replace an organization’s access-control policy.",
    ),
    Spec(
        64,
        "Injection and Parameterized Queries",
        "Injection occurs when data is interpreted as code or query syntax. The core defense is to keep data separate from the language being executed and to validate values at the boundary.",
        "Store and search synthetic cases in SQLite using parameters, then compare it with an intentionally unsafe string-building example without executing attacker input.",
        "Injection changes the meaning of an interpreter input. A parameterized query sends values separately from SQL syntax. Allowlisting constrains identifiers or operations.",
        (
            e(
                "The unsafe shape",
                "String concatenation mixes data and SQL grammar; keep this as a non-executed illustration.",
                'username = "training-user"\nunsafe_sql = "SELECT * FROM users WHERE name = \'" + username + "\'"\nprint(unsafe_sql)',
                "The query text contains data inside its syntax.",
            ),
            e(
                "Use a placeholder",
                "The database receives SQL structure and value separately.",
                'query = "SELECT * FROM users WHERE name = ?"\nparams = (username,)\nprint(query, params)',
                "The value is not assembled into the query string.",
            ),
            e(
                "Validate an identifier",
                "Parameters are for values, not table or column names.",
                'allowed_columns = {"name", "severity"}\ncolumn = "severity"\nif column not in allowed_columns:\n    raise ValueError("column not allowed")',
                "Only known identifiers are accepted.",
            ),
            e(
                "Bound a result",
                "A query can still return too many rows.",
                'limit = 20\nif not 1 <= limit <= 100:\n    raise ValueError("limit outside policy")',
                "The database operation has a finite result bound.",
            ),
            e(
                "Test a quote as data",
                "A quote in a username should remain a value.",
                'candidate = "O\'Reilly"\nprint((candidate,))',
                "The parameter tuple holds the literal text.",
            ),
        ),
        "The program validates the operation and bounds, sends a fixed query with parameters, receives rows, and serializes only selected fields. It never turns user text into SQL source.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| concatenate values | input changes query syntax | use parameters |\n| parameterize identifiers | API does not treat table names as values | allowlist identifiers |\n| trust ORM blindly | raw fragments still bypass safety | review generated SQL and APIs |\n| no result bound | query exhausts resources | cap rows and time |\n| demonstrate with live target | unsafe practice expands scope | use local SQLite |",
        "Use only in-memory or disposable SQLite with synthetic records. The lesson explains an unsafe pattern but must not execute exploit strings or target a public database.",
        "Injection is prevented when the interpreter’s language remains fixed and external data remains data.",
        "Parameterized queries do not validate business logic, permissions, schema, or database availability.",
    ),
    Spec(
        65,
        "Cross-Site Scripting and Output Encoding",
        "A web application can turn stored or reflected text into browser-interpreted markup. The safe response is context-aware output encoding and a strict separation between data and HTML/JavaScript.",
        "Render a synthetic username as text and show why inserting it into an HTML string without escaping is unsafe.",
        "XSS is unintended script execution in a browser context. Escaping encodes special characters. Context determines the correct encoding rule. Content Security Policy is a defense in depth control.",
        (
            e(
                "Treat input as text",
                "A username is data until a renderer chooses a context.",
                'username = "<training-user>"\nprint(username)',
                "The characters remain literal text in the Python output.",
            ),
            e(
                "Escape HTML",
                "HTML escaping prevents `<` and `>` from becoming tags in a text context.",
                "import html\nsafe = html.escape(username, quote=True)\nprint(safe)",
                "The angle brackets are encoded.",
            ),
            e(
                "Use a template context",
                "A template engine’s text interpolation is safer than string-built markup when configured correctly.",
                'context = {"username": safe}\nprint(context)',
                "The model contains data, not executable markup.",
            ),
            e(
                "Do not use raw HTML blindly",
                "This illustrates the dangerous shape without a browser.",
                'unsafe_markup = "<p>" + username + "</p>"\nprint(unsafe_markup)',
                "The output includes the original tag-like characters; a browser context could interpret them.",
            ),
            e(
                "Set defense in depth",
                "Encoding is primary; policy headers reduce impact if a bug remains.",
                'headers = {"Content-Security-Policy": "default-src \'self\'"}\nprint(headers)',
                "The header is a policy layer, not a replacement for encoding.",
            ),
        ),
        "The application stores raw data, selects the output context, applies the context’s encoding, and sends a response with defense-in-depth headers. It does not concatenate untrusted text into executable contexts.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| HTML escape everywhere | URL or JavaScript context remains unsafe | use context-aware encoding |\n| mark untrusted HTML safe | browser interprets data | keep data and markup separate |\n| strip `<script>` only | alternate syntax bypasses filter | encode and use safe sinks |\n| rely on CSP only | policy gaps remain | fix output handling |\n| test only plain names | special characters fail | include quotes, tags, and Unicode |",
        "Use synthetic values and a local rendered fixture. Do not publish a test payload or target a public site.",
        "XSS defense is a context decision: keep untrusted data as data and encode it for the exact output context.",
        "Encoding cannot repair every DOM, URL, CSS, or browser integration mistake; review the whole rendering path.",
    ),
    Spec(
        66,
        "CSRF, Cookies, and CORS",
        "Browser state creates security behavior that is not visible in a single Python function. Cookies carry session context, CSRF defenses bind state-changing requests to intent, and CORS controls which browser origins may read responses.",
        "Model a local state-changing request and decide which cookie, CSRF, and origin checks belong to it.",
        "A cookie is browser-managed state. CSRF tricks a browser into sending ambient credentials. CORS is a browser read-access policy, not an authentication mechanism.",
        (
            e(
                "Describe a session cookie",
                "Cookie properties affect exposure and browser behavior.",
                'cookie = {"name": "session", "secure": True, "httponly": True, "samesite": "Lax"}\nprint(cookie)',
                "The flags are explicit.",
            ),
            e(
                "Separate read and write",
                "State-changing methods deserve stronger protection.",
                'method = "POST"\nchanges_state = method in {"POST", "PUT", "PATCH", "DELETE"}\nprint(changes_state)',
                "`True` for `POST`.",
            ),
            e(
                "Check a CSRF token",
                "A server compares a token bound to the session and request context.",
                'session_token = "training-csrf"\nprovided = "training-csrf"\nprint(session_token == provided)',
                "The example is a fictional equality check; real comparison and lifecycle belong in the framework.",
            ),
            e(
                "Allow a known origin",
                "CORS should name allowed origins rather than mirror arbitrary input.",
                'allowed = {"https://training.local"}\norigin = "https://training.local"\nprint(origin in allowed)',
                "The origin is explicitly allowed.",
            ),
            e(
                "Do not confuse CORS with auth",
                "A server still checks identity and permission.",
                'controls = ["authentication", "authorization", "CSRF", "CORS"]\nprint(controls)',
                "The controls solve different problems.",
            ),
        ),
        "The browser sends cookies according to cookie policy; the server authenticates and authorizes, checks CSRF for state-changing requests, and emits an explicit CORS policy for browser reads.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| CORS as auth | non-browser caller bypasses it | enforce auth server-side |\n| wildcard origin with credentials | origin trust is too broad | allowlist origins |\n| no CSRF for cookie auth | cross-site state change | use framework defense and tokens |\n| insecure cookie flags | session exposure | use Secure/HttpOnly/SameSite policy |\n| token in URL | leaks through history and referrers | use appropriate request channels |",
        "Use a local conceptual service and synthetic cookie names. Do not collect real sessions or demonstrate attacks against a public browser application.",
        "Cookies, CSRF, CORS, authentication, and authorization are separate browser and server controls.",
        "Exact behavior depends on browser, framework, deployment, and same-site topology; a checklist is not a complete review.",
    ),
    Spec(
        67,
        "SSRF and Outbound Request Controls",
        "A server that fetches a URL based on user input can become a network pivot. The defense is an explicit outbound policy: allowed schemes, hosts, ports, resolution behavior, redirects, and response limits.",
        "Design a local URL fetch policy that accepts one documentation fixture and rejects loopback, private, unsupported, or unknown destinations.",
        "SSRF is unintended server-side access through attacker-influenced requests. An egress policy controls outbound destinations. A redirect can change the effective destination.",
        (
            e(
                "Parse a URL",
                "A URL has components that the policy must inspect.",
                'from urllib.parse import urlparse\nparts = urlparse("https://training.local/docs")\nprint(parts.scheme, parts.hostname, parts.path)',
                "Scheme, host, and path are separate values.",
            ),
            e(
                "Allow schemes",
                "Reject schemes that the fetcher does not need.",
                'if parts.scheme not in {"https"}:\n    raise ValueError("scheme is not allowed")',
                "Only HTTPS passes this policy example.",
            ),
            e(
                "Allow a host",
                "A host allowlist is narrower than a denylist.",
                'allowed_hosts = {"training.local"}\nprint(parts.hostname in allowed_hosts)',
                "The documentation host is explicit.",
            ),
            e(
                "Bound redirects",
                "A response should not silently move to a new destination.",
                'policy = {"follow_redirects": False, "max_redirects": 0}\nprint(policy)',
                "Redirect behavior is explicit.",
            ),
            e(
                "Bound response bytes",
                "Even an allowed endpoint can return excessive data.",
                "MAX_BYTES = 1_000_000\nprint(MAX_BYTES)",
                "The response budget is finite.",
            ),
        ),
        "The server parses the URL, validates scheme/host/port, resolves and rechecks according to policy, uses a bounded client, and refuses unexpected redirects or destinations.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| blocklist only | new private target bypasses it | allowlist destinations |\n| validate before redirect only | redirect escapes policy | revalidate every hop or disable redirects |\n| hostname string check | DNS changes or alternate forms bypass | resolve and enforce carefully |\n| allow all HTTPS | HTTPS does not define destination trust | allow known hosts |\n| no response bound | memory and time abuse | cap bytes and timeout |",
        "Use a saved local fixture or a fake HTTP client. Do not make outbound requests to cloud metadata, private networks, or public systems.",
        "Outbound fetching is a capability; the destination policy must be narrower than user input.",
        "SSRF defenses are deployment-sensitive and need network-layer egress controls in addition to application checks.",
    ),
    Spec(
        68,
        "Misconfiguration and Secure Defaults",
        "Many security failures are ordinary configuration choices: debug enabled, permissive origins, verbose errors, weak cookies, unlimited bodies, or development keys.",
        "Create a configuration review that identifies unsafe defaults without changing a real service.",
        "A secure default is safe when the user does nothing. A misconfiguration is a deployed setting that violates intended security or reliability policy.",
        (
            e(
                "Represent settings",
                "A review needs names and effective values.",
                'settings = {"debug": False, "body_limit": 1_000_000, "allow_origins": ["https://training.local"]}\nprint(settings)',
                "The effective settings are inspectable.",
            ),
            e(
                "Flag debug",
                "Debug can reveal internals and must be false outside local development.",
                'if settings["debug"]:\n    print("review: debug enabled")',
                "The review creates a finding.",
            ),
            e(
                "Check a bounded body",
                "A finite body limit is a resource control.",
                'print(0 < settings["body_limit"] <= 10_000_000)',
                "The value is checked against policy.",
            ),
            e(
                "Review defaults",
                "An empty allowlist should not silently mean allow all.",
                'origins = settings.get("allow_origins", [])\nprint(origins)',
                "Missing configuration is visible.",
            ),
            e(
                "Make failure safe",
                "Invalid security configuration should stop startup in a controlled way.",
                'if not origins:\n    raise RuntimeError("no trusted origin configured")',
                "The service does not start with an ambiguous policy.",
            ),
        ),
        "The reviewer loads effective configuration, compares each setting to a policy, reports unsafe or missing values, and fails closed when a required security choice is absent.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| development default in production | debug or test keys remain | separate environments |\n| empty means all | missing origin opens access | fail closed |\n| config review only once | deployment drifts | review effective runtime settings |\n| print full config | secrets leak | redact sensitive values |\n| no owner | findings remain open | assign remediation |",
        "Use a static synthetic settings dictionary. Do not inspect or change a production deployment.",
        "A secure default reduces harm when configuration is omitted; an explicit policy still needs review and enforcement.",
        "Configuration scanners can miss code paths, secret stores, deployment overrides, and runtime behavior.",
    ),
    Spec(
        69,
        "Supply Chain and Exceptional Conditions",
        "A secure application depends on packages, build steps, services, and assumptions outside one source file. Exceptional conditions include dependency failure, missing updates, and unexpected runtime behavior.",
        "Review a synthetic dependency record and design a failure path that does not silently downgrade security.",
        "A supply chain includes code, packages, maintainers, build systems, and artifacts. An exceptional condition is a failure outside the ordinary happy path. Fail closed means refusing a sensitive action when a required control is unavailable.",
        (
            e(
                "Inventory a component",
                "Record source, version, purpose, and review date.",
                'component = {"name": "training-lib", "version": "1.0", "source": "reviewed-index", "reviewed": "2026-08-20"}\nprint(component)',
                "The provenance fields are visible.",
            ),
            e(
                "Separate required and optional",
                "Security controls should not silently become optional.",
                'dependency = {"name": "verifier", "required_for": "integrity", "optional": False}\nprint(dependency)',
                "The requirement is explicit.",
            ),
            e(
                "Handle unavailable verification",
                "If verification cannot run, do not mark data trusted.",
                'verification = {"status": "unavailable", "trusted": False}\nprint(verification)',
                "The state is incomplete.",
            ),
            e(
                "Pin a policy",
                "A review record should identify what was actually tested.",
                'policy = {"lockfile": True, "hashes": "reviewed", "updates": "scheduled"}\nprint(policy)',
                "The process is documented.",
            ),
            e(
                "Preserve evidence",
                "An error record should identify the component without dumping environment secrets.",
                'print({"component": component["name"], "event": "verification_failed"})',
                "The log is minimal.",
            ),
        ),
        "The program identifies dependencies and their provenance, attempts a required control, records whether it was available, and refuses to mark the artifact trusted when the control failed.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| install any package | unreviewed code enters | verify source and purpose |\n| latest without review | behavior changes silently | pin and test updates |\n| unavailable scanner equals pass | blind spot is reported as clean | fail closed or mark unknown |\n| log environment | tokens and paths leak | minimize component evidence |\n| no update owner | known issues persist | assign review lifecycle |",
        "Use only the repository’s declared development tools and synthetic component records. Do not install packages from arbitrary commands or execute downloaded artifacts.",
        "A supply-chain control is trustworthy only when its source, version, availability, and failure state are visible.",
        "No inventory eliminates maintainer compromise, build tampering, or unknown vulnerabilities; it supports informed review.",
    ),
    Spec(
        70,
        "Project: Secure Case API",
        "This project applies request validation, authorization, injection defense, output handling, browser controls, outbound policy, secure defaults, and dependency thinking to a single local API design.",
        "Build a local API for synthetic cases with read-only routes, explicit authorization, bounded JSON, safe errors, and a threat model.",
        "A route maps an HTTP method and path to behavior. An object-level authorization check compares the caller to the requested case. An API contract specifies request and response fields.",
        (
            e(
                "Define routes",
                "A small allowlist is easier to review.",
                'routes = {"GET /cases/{id}": "read synthetic case", "POST /cases": "disabled in training"}\nprint(routes)',
                "The supported surface is explicit.",
            ),
            e(
                "Validate a body",
                "The API accepts only fields needed for the action.",
                'allowed = {"case_id", "limit"}\nbody = {"case_id": "training-70", "limit": 10}\nprint(set(body) <= allowed)',
                "The body fits the schema.",
            ),
            e(
                "Authorize an object",
                "The caller must have scope over this case.",
                'permissions = {"student-70": {"training-70"}}\nprint("training-70" in permissions["student-70"])',
                "The object check is separate from identity.",
            ),
            e(
                "Use safe SQL",
                "The repository layer must parameterize values.",
                'query = "SELECT id, title FROM cases WHERE id = ?"\nprint(query)',
                "The query is fixed.",
            ),
            e(
                "Return safe errors",
                "The API response should not expose traceback or secret fields.",
                'response = {"status": 400, "error": "invalid request", "request_id": "training-70"}\nprint(response)',
                "The response is useful but minimal.",
            ),
        ),
        "The request enters through a bounded parser, passes auth and object checks, reaches a parameterized repository call, and returns a schema-controlled response with safe errors.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| broad route surface | more unreviewed behavior | allowlist routes |\n| auth without object check | case data crosses tenants | check resource scope |\n| raw SQL | injection risk | parameterize |\n| return model internals | secret fields leak | serialize allowlisted fields |\n| public bind | training API is exposed | loopback-only |",
        "The API is local, synthetic, read-only, and resettable. The project README must contain its route contract, scope, threat model, tests, example requests, and limitations.",
        "A secure API is a sequence of explicit contracts: route, input, identity, authorization, storage, output, and failure.",
        "This project is not production-ready and does not implement a complete identity provider, deployment hardening, or privacy program.",
    ),
    Spec(
        71,
        "Telemetry and Event Schemas",
        "Detection depends on events that different systems represent differently. A schema gives analysts stable fields while preserving source, time, and uncertainty.",
        "Define a normalized event schema for synthetic authentication activity and reject records that cannot support the required fields.",
        "Telemetry is collected operational data. A schema defines fields and types. Normalization maps source-specific fields into common fields. Provenance identifies the source.",
        (
            e(
                "Define an event",
                "Start with fields needed for a decision.",
                'event = {"event_type": "auth_failure", "source": "training-auth", "actor": "student", "observed_at": "now"}\nprint(event)',
                "The event has stable names.",
            ),
            e(
                "Map source fields",
                "Normalization makes source differences explicit.",
                'source_record = {"user": "student", "action": "login_failed"}\nnormalized = {"actor": source_record["user"], "event_type": "auth_failure"}\nprint(normalized)',
                "The mapping is visible.",
            ),
            e(
                "Validate time",
                "A detection without time cannot be placed in a sequence.",
                'if not event.get("observed_at"):\n    raise ValueError("timestamp required")',
                "The event is rejected when time is missing.",
            ),
            e(
                "Preserve source",
                "Normalized data must retain where it came from.",
                'normalized["provenance"] = {"source": "training-auth", "raw_id": "fixture-1"}\nprint(normalized)',
                "The mapping is auditable.",
            ),
            e(
                "Version a schema",
                "Fields evolve; a version tells readers how to interpret them.",
                'normalized["schema_version"] = 1\nprint(normalized["schema_version"])',
                "The version is explicit.",
            ),
        ),
        "The source record is mapped, required fields are checked, raw provenance is retained, and the versioned normalized event enters detection logic.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| drop source | analyst cannot trace mapping | preserve provenance |\n| no schema version | fields drift silently | version and document |\n| missing time accepted | sequence rules fail | reject or mark unknown |\n| normalize away raw | audit loses context | retain safe references |\n| event equals truth | collection errors become facts | record confidence |",
        "Use synthetic authentication events and local JSON fixtures only. Do not ingest real user telemetry.",
        "A schema creates stable analytical fields without erasing source or uncertainty.",
        "A normalized event can still be incomplete, delayed, duplicated, or wrong.",
    ),
    Spec(
        72,
        "Log Normalization",
        "Real logs use inconsistent timestamps, separators, levels, and field names. Normalization is a documented transformation, not an excuse to erase raw evidence.",
        "Convert two synthetic log formats into one event schema and report rejected fields.",
        "Normalization transforms equivalent source fields into canonical fields. A parser extracts. A mapper assigns. A rejected field is a data-quality result.",
        (
            e(
                "Parse key-value text",
                "Simple fixtures can be parsed with a bounded splitter.",
                'line = "level=warning user=student event=login_failed"\nfields = dict(item.split("=", 1) for item in line.split())\nprint(fields)',
                "The fields are strings.",
            ),
            e(
                "Map names",
                "Source keys can map to normalized names.",
                'normalized = {"severity": fields["level"], "actor": fields["user"], "event_type": fields["event"]}\nprint(normalized)',
                "The target schema is stable.",
            ),
            e(
                "Handle malformed pairs",
                "A bad token should be counted, not silently trusted.",
                'tokens = ["level=warning", "broken"]\nrejected = [token for token in tokens if "=" not in token]\nprint(rejected)',
                "`broken` is rejected.",
            ),
            e(
                "Preserve raw id",
                "The normalized record should point to its source line.",
                'normalized["provenance"] = {"line": 1, "source": "fixture-a"}\nprint(normalized)',
                "The mapping can be reviewed.",
            ),
            e(
                "Bound text",
                "Line length and field count are resource controls.",
                'print({"max_line": 2000, "max_fields": 50})',
                "The parser has finite limits.",
            ),
        ),
        "The normalizer bounds the line, extracts fields, maps names, converts types, records rejected tokens, and emits a versioned event with provenance.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| drop malformed tokens | quality problem disappears | count and report rejects |\n| map by position | format variation breaks | map named fields |\n| erase raw line | audit cannot reproduce | keep line reference |\n| unlimited fields | parser abuse | cap count and lengths |\n| call normalized event true | mapping is overtrusted | record quality and confidence |",
        "Use supplied synthetic log formats. Do not normalize real private logs without data-handling permission.",
        "Normalization is a controlled translation with evidence of what changed and what failed.",
        "A canonical schema can hide source-specific meaning if the mapping is too aggressive.",
    ),
    Spec(
        73,
        "IOC Enrichment and Provenance",
        "An indicator can be a domain, hash, address, or filename. Enrichment adds context, but it can also create privacy, accuracy, and false-confidence problems.",
        "Enrich synthetic indicators from a local lookup table and keep source, time, and confidence attached to each result.",
        "An IOC is an observed indicator. Enrichment adds context. Provenance records source and time. Confidence describes evidence quality.",
        (
            e(
                "Classify a candidate",
                "A candidate shape is not a verdict.",
                'candidate = {"value": "example.invalid", "kind": "domain", "status": "candidate"}\nprint(candidate)',
                "The label remains neutral.",
            ),
            e(
                "Use local enrichment",
                "A local table avoids contacting external services.",
                'lookup = {"example.invalid": {"owner": "training", "confidence": "high"}}\nprint(lookup.get(candidate["value"]))',
                "Synthetic context is returned.",
            ),
            e(
                "Attach provenance",
                "The result should say where the context came from.",
                'result = {**candidate, **lookup[candidate["value"]], "source": "course-fixture"}\nprint(result)',
                "The fields explain the enrichment.",
            ),
            e(
                "Handle no result",
                "Absence of enrichment is not evidence of safety.",
                'print({"value": "unknown.invalid", "status": "not_found", "safe": None})',
                "The unknown state is explicit.",
            ),
            e(
                "Bound cache",
                "Repeated lookups should not grow without a policy.",
                'cache_policy = {"max_entries": 100, "ttl_seconds": 3600}\nprint(cache_policy)',
                "Resource and staleness limits are visible.",
            ),
        ),
        "The indicator is parsed, looked up only in the approved local source, merged with provenance, and returned with a neutral status and confidence.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| enrichment equals malicious | context becomes accusation | retain candidate and confidence |\n| external lookup by default | privacy and scope expand | use local fixtures or explicit approval |\n| no timestamp | stale context looks current | record observation time |\n| no source | result cannot be audited | preserve provenance |\n| not found equals safe | blind spot becomes reassurance | use unknown |",
        "Use local synthetic indicators and a fixture lookup table. Do not resolve, scan, or query public reputation services.",
        "Enrichment adds context to an observation; it does not create certainty or permission to act.",
        "External data can be stale, biased, unavailable, or wrong, and enrichment may itself expose sensitive indicators.",
    ),
    Spec(
        74,
        "Detection Thresholds and Evaluation",
        "A detection rule is a policy over incomplete telemetry. Thresholds control false positives and false negatives, so a learner should evaluate them against labeled synthetic fixtures instead of trusting intuition.",
        "Choose and evaluate a threshold for synthetic failed-login events, then explain what the metric does not show.",
        "A threshold is a rule boundary. A true positive matches a labeled condition. A false positive alerts on benign data. Recall and precision summarize different error trade-offs.",
        (
            e(
                "Count events",
                "A simple detector starts with observable counts.",
                'events = ["failed", "failed", "ok"]\nfailures = events.count("failed")\nprint(failures)',
                "`2` failures.",
            ),
            e(
                "Apply a threshold",
                "The threshold turns count into an alert decision.",
                "threshold = 3\nprint(failures >= threshold)",
                "`False` for two failures.",
            ),
            e(
                "Create labels",
                "Evaluation requires an expected label in synthetic data.",
                'cases = [{"alert": True, "expected": True}, {"alert": True, "expected": False}]\nprint(cases)',
                "The two cases support error counting.",
            ),
            e(
                "Count errors",
                "Confusion-matrix counts make trade-offs visible.",
                'tp, fp, fn, tn = 1, 1, 0, 2\nprint({"tp": tp, "fp": fp, "fn": fn, "tn": tn})',
                "The outcomes are explicit.",
            ),
            e(
                "State threshold limits",
                "A rule may miss slow or distributed behavior.",
                'print({"blind_spot": "below-threshold distributed activity", "status": "known limitation"})',
                "The detector is not overclaimed.",
            ),
        ),
        "The detector aggregates bounded events, applies a threshold, compares output with synthetic labels, counts errors, and documents blind spots before deployment.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| threshold from intuition | false alarms or misses | evaluate labeled fixtures |\n| precision only | misses are ignored | examine recall too |\n| label is attacker truth | synthetic label is overtrusted | document labeling assumptions |\n| no time window | counts accumulate forever | define window and reset |\n| alert equals incident | automation overreacts | require triage |",
        "Use only synthetic labeled fixtures. Do not tune a detector against real people or claim its threshold identifies attackers.",
        "A detection threshold is a policy that trades false positives and negatives under a defined window and dataset.",
        "Metrics depend on labels, distribution, drift, and operational cost; they are not universal quality scores.",
    ),
    Spec(
        75,
        "MITRE ATT&CK Mapping as Documentation",
        "Framework mappings can help analysts communicate behavior, but a technique label is not proof that an adversary used it. The mapping should link observable evidence to a cautious hypothesis.",
        "Map synthetic behavior descriptions to a documented technique reference without claiming attribution.",
        "A tactic describes a goal. A technique describes a behavior. Mapping links evidence to a framework entry. Attribution claims actor identity and requires much more evidence.",
        (
            e(
                "Describe behavior",
                "Start with what the fixture actually shows.",
                'observation = {"event": "process_started", "command": "python --version", "source": "fixture"}\nprint(observation)',
                "The observation is concrete.",
            ),
            e(
                "Map cautiously",
                "A mapping is a hypothesis about behavior.",
                'mapping = {"observation": "process_started", "technique": "training-reference", "confidence": "low"}\nprint(mapping)',
                "The confidence is not certainty.",
            ),
            e(
                "Separate tactic",
                "A broad goal and a specific behavior are different fields.",
                'mapping["tactic"] = "execution-like"\nprint(mapping)',
                "The fields communicate different levels.",
            ),
            e(
                "Attach evidence",
                "A mapping without evidence is decorative.",
                'mapping["evidence_ref"] = {"case_id": "training-75", "line": 1}\nprint(mapping)',
                "The reviewer can return to the fixture.",
            ),
            e(
                "Reject attribution",
                "A framework match does not identify a person or group.",
                'mapping["attribution"] = "not assessed"\nprint(mapping)',
                "The report avoids overclaiming.",
            ),
        ),
        "The analyst records observation, selects a cautious framework reference, attaches evidence and confidence, and explicitly leaves attribution unassessed.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| technique equals attacker | attribution is invented | label mapping as hypothesis |\n| no evidence reference | mapping cannot be reviewed | link case and line |\n| framework name only | behavior is not explained | write observation first |\n| force a mapping | every event becomes a technique | allow unmapped |\n| ignore version | framework changes | record version/date |",
        "Use fictional observations and framework documentation as a vocabulary aid. Do not publish accusations or map real people from thin evidence.",
        "Framework mapping improves shared language; evidence and uncertainty remain the foundation.",
        "Frameworks are descriptive and versioned; they do not replace investigation, detection engineering, or legal standards.",
    ),
    Spec(
        76,
        "Alert Triage and Analyst Decisions",
        "An alert is a queue item, not a conclusion. Triage organizes evidence, severity, confidence, scope, next step, and closure reason so analysts do not confuse urgency with certainty.",
        "Triage synthetic alerts into review states with an explicit evidence checklist and no automatic accusation.",
        "Triage prioritizes work. Severity describes impact or urgency. Confidence describes evidence quality. Disposition records what happened to the alert.",
        (
            e(
                "Create an alert",
                "An alert needs an identifier and evidence reference.",
                'alert = {"id": "alert-76", "rule": "failed-login-threshold", "evidence": ["fixture:4"]}\nprint(alert)',
                "The alert points to evidence.",
            ),
            e(
                "Score separately",
                "Severity and confidence answer different questions.",
                'alert.update({"severity": "medium", "confidence": "low"})\nprint(alert)',
                "A medium-impact, low-confidence alert is possible.",
            ),
            e(
                "Choose a disposition",
                "Triage needs controlled states.",
                'allowed = {"new", "investigating", "benign", "escalated", "closed"}\nprint("investigating" in allowed)',
                "The state is from a finite vocabulary.",
            ),
            e(
                "Record next step",
                "The next action should be authorized and bounded.",
                'alert["next_step"] = "review synthetic timeline"\nprint(alert)',
                "The plan is local and specific.",
            ),
            e(
                "Close with reason",
                "Closure should preserve why a case ended.",
                'alert.update({"disposition": "benign_training_fixture", "closed_by": "student"})\nprint(alert)',
                "The outcome is explainable.",
            ),
        ),
        "Triage reads the alert and evidence, separates severity from confidence, selects a state, records a bounded next step, and preserves a disposition and reviewer.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| alert equals incident | unnecessary response | require evidence and triage |\n| severity equals confidence | urgency and certainty blur | store separately |\n| no closure reason | lessons are lost | require disposition |\n| investigate without scope | analyst overreaches | name authorized next step |\n| copy raw data everywhere | privacy expands | reference evidence minimally |",
        "Use synthetic alerts and a local queue. Do not triage real individuals or initiate response actions from this lesson.",
        "Triage is an evidence-organizing decision process that turns a signal into a documented next step.",
        "Triage quality depends on context, staffing, data quality, and escalation policy outside the code.",
    ),
    Spec(
        77,
        "Baselines and Anomaly Reasoning",
        "An anomaly is a deviation from a model, not proof of maliciousness. Baselines need a time window, feature definition, missing-data policy, and a plan for normal change.",
        "Compute a simple synthetic baseline and flag a value for review while preserving the model’s assumptions.",
        "A baseline summarizes normal reference data. An anomaly score measures deviation. A false positive is benign deviation. Concept drift means normal behavior changes over time.",
        (
            e(
                "Compute an average",
                "A simple baseline starts with a transparent statistic.",
                "values = [10, 11, 9, 10]\nmean = sum(values) / len(values)\nprint(mean)",
                "`10.0`",
            ),
            e(
                "Measure deviation",
                "The difference is a signal, not a verdict.",
                "observed = 15\nprint(observed - mean)",
                "A deviation of 5.",
            ),
            e(
                "Choose a rule",
                "The rule must name its threshold.",
                "threshold = 3\nprint(abs(observed - mean) > threshold)",
                "`True` for review.",
            ),
            e(
                "Handle missing data",
                "No sample should not silently become zero.",
                'sample = None\nprint({"status": "not_observed" if sample is None else "observed"})',
                "Missingness is explicit.",
            ),
            e(
                "Document drift",
                "A baseline needs refresh and review.",
                'model = {"window": "training fixture", "refresh": "manual review", "owner": "student"}\nprint(model)',
                "The model lifecycle is visible.",
            ),
        ),
        "The detector defines a reference window, computes a feature, measures deviation, applies a threshold, and emits a review signal with model version and missing-data status.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| anomaly equals attack | benign change is accused | use needs-review |\n| no window | old behavior dominates | define a reference period |\n| missing equals normal | blind spot disappears | mark unknown |\n| no refresh | drift creates noise | version and review model |\n| feature leaks privacy | unnecessary collection | minimize and aggregate |",
        "Use synthetic counts and no real user behavior. Document the feature, window, threshold, false-positive risk, and reset procedure.",
        "An anomaly detector identifies difference from a model; human or policy review determines meaning.",
        "Simple statistics can fail under seasonality, dependence, adversarial adaptation, and changing operations.",
    ),
    Spec(
        78,
        "Threat Intelligence Provenance",
        "Threat intelligence is useful only when analysts can judge source, freshness, confidence, and handling restrictions. Copying an indicator without context creates false authority.",
        "Represent a synthetic intelligence report and decide whether its indicator is suitable for a local training rule.",
        "Intelligence is analyzed information. Provenance records source and transformation. Freshness describes age. Confidence reflects evidence quality. Handling restrictions limit sharing.",
        (
            e(
                "Model a report",
                "Start with source and observation time.",
                'report = {"source": "training-lab", "observed_at": "2026-08-20", "indicator": "example.invalid"}\nprint(report)',
                "The origin is explicit.",
            ),
            e(
                "Add confidence",
                "Confidence is not the same as severity.",
                'report.update({"confidence": "medium", "severity": "unknown"})\nprint(report)',
                "The fields remain separate.",
            ),
            e(
                "Track transformation",
                "A normalized indicator should say what changed.",
                'report["transformation"] = "lowercase domain for comparison"\nprint(report)',
                "The transformation is auditable.",
            ),
            e(
                "Apply freshness",
                "Old data may need review before use.",
                'report["freshness"] = {"status": "training-only", "expires": "documented"}\nprint(report)',
                "Freshness policy is visible.",
            ),
            e(
                "Respect handling",
                "A source restriction is part of safe use.",
                'report["handling"] = "do not redistribute"\nprint(report["handling"])',
                "The learner sees a sharing boundary.",
            ),
        ),
        "The analyst records source, time, indicator, transformation, confidence, freshness, and handling before deciding whether a local rule can use the information.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| source name as proof | provenance is shallow | record method and time |\n| old indicator as current | stale detection | apply freshness |\n| confidence equals truth | uncertainty disappears | preserve confidence |\n| redistribute restricted data | handling breach | respect restrictions |\n| query indicator externally | scope and privacy expand | use local fixtures |",
        "Use only synthetic reports and indicators. Do not paste private intelligence or query public reputation services.",
        "Intelligence is contextual evidence with provenance and handling rules, not a magic label.",
        "Sources can be wrong, biased, stale, compromised, or unsuitable for the learner’s legal and operational context.",
    ),
    Spec(
        79,
        "Analyst Reporting and Evidence-Based Writing",
        "A security report must let another person reproduce the reasoning. Separating observation, analysis, assessment, action, and limitation reduces accidental overclaiming.",
        "Write a short synthetic alert report that distinguishes facts from interpretation and names the next authorized step.",
        "An observation is what was recorded. Analysis connects observations. Assessment states a cautious interpretation. A limitation identifies missing or weak evidence.",
        (
            e(
                "Write an observation",
                "Use neutral, timestamped language.",
                'observation = "Three failed logins occurred in the training fixture between 10:00 and 10:02 UTC."\nprint(observation)',
                "The sentence states a bounded fact.",
            ),
            e(
                "Write analysis",
                "Analysis explains why the fact matters without inventing a person.",
                'analysis = "The count crosses the training rule threshold; the fixture has no identity validation."\nprint(analysis)',
                "The uncertainty remains visible.",
            ),
            e(
                "Write assessment",
                "Use confidence and scope.",
                'assessment = {"status": "needs_review", "confidence": "low", "scope": "synthetic fixture"}\nprint(assessment)',
                "The conclusion is limited.",
            ),
            e(
                "Name next step",
                "The action must be authorized and concrete.",
                'next_step = "review the local timeline and confirm fixture provenance"\nprint(next_step)',
                "The next step is bounded.",
            ),
            e(
                "List limitations",
                "A report is stronger when it says what it cannot show.",
                'limitations = ["no real identity data", "no endpoint context", "synthetic timestamps"]\nprint(limitations)',
                "The reader can judge confidence.",
            ),
        ),
        "The report moves from source-backed observation to analysis, cautious assessment, authorized next step, and limitations. A reader can tell fact from inference.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| adjective as evidence | ‘suspicious’ replaces facts | write observable detail |\n| no source | claim cannot be checked | cite case and line |\n| certainty language | thin evidence becomes verdict | state confidence |\n| action without authorization | report triggers harm | name allowed next step |\n| omit limitations | reader overtrusts result | include blind spots |",
        "Use a synthetic case and local references. Do not write accusations about real people, organizations, or public indicators.",
        "Good reporting preserves the chain from observation to interpretation and makes uncertainty actionable.",
        "Writing quality cannot repair bad collection, biased labels, or missing evidence; it makes those gaps visible.",
    ),
    Spec(
        80,
        "Project: Mini Detection Pipeline",
        "The project composes telemetry schemas, normalization, enrichment, thresholds, mappings, triage, baselines, provenance, and reporting into a small defensive pipeline with honest limits.",
        "Build a local pipeline that ingests synthetic events, normalizes them, applies one detection rule, creates a triage item, and writes an evidence-based report.",
        "A pipeline is an ordered transformation. A detection rule emits a signal. Triage adds context and disposition. A report preserves evidence and limitations.",
        (
            e(
                "Define stages",
                "A project is easier to debug when every stage has one purpose.",
                'stages = ["ingest", "normalize", "enrich", "detect", "triage", "report"]\nprint(" -> ".join(stages))',
                "The pipeline is explicit.",
            ),
            e(
                "Normalize an event",
                "The event must carry provenance.",
                'event = {"event_type": "auth_failure", "source": "fixture", "actor": "student", "line": 2}\nprint(event)',
                "A normalized synthetic event.",
            ),
            e(
                "Apply a rule",
                "A rule produces a signal, not a conclusion.",
                'signal = {"rule": "three-failures", "matched": True, "confidence": "low"}\nprint(signal)',
                "The signal is cautious.",
            ),
            e(
                "Create triage",
                "Triage records evidence and next step.",
                'alert = {"signal": signal, "evidence": [event], "status": "new", "next_step": "review fixture"}\nprint(alert)',
                "The alert is actionable but bounded.",
            ),
            e(
                "Write limitations",
                "The report should prevent overinterpretation.",
                'report = {"scope": "synthetic only", "complete": True, "limitations": ["no identity proof", "no production context"]}\nprint(report)',
                "The report is transparent.",
            ),
        ),
        "The pipeline validates input, normalizes fields, enriches from local data, applies a bounded rule, creates a triage item, and writes a report with provenance, completeness, and limitations.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| pipeline drops raw reference | signal cannot be checked | retain evidence ids |\n| enrichment becomes truth | context overrules observation | keep confidence |\n| alert auto-escalates | false positive causes harm | require triage |\n| no schema version | future data breaks | version events |\n| no reset | fixtures and reports accumulate | document cleanup |",
        "The pipeline must use only repository fixtures, local lookup tables, finite inputs, and neutral labels. Its README must include threat model, tests, sample report, and reset.",
        "A detection pipeline turns bounded observations into reviewable signals while preserving provenance and uncertainty at every stage.",
        "This is not a SIEM, threat-intelligence platform, or real-world detection service; production needs governance, access control, retention, and monitoring.",
    ),
]


def render(spec: Spec) -> str:
    prev_dir = DIRS[spec.day - 1]
    next_dir = DIRS[spec.day + 1]
    lines = [
        f"# Day {spec.day}: {spec.title}",
        "",
        f"[← Day {spec.day - 1}](../{prev_dir}/{prev_dir}.md) · [Day index](../DAY_INDEX.md) · [Day {spec.day + 1} →](../{next_dir}/{next_dir}.md)",
        "",
        "## Table of Contents",
        "",
        "- [Why this lesson exists](#why-this-lesson-exists)",
        "- [Prerequisites](#prerequisites)",
        "- [Outcomes](#outcomes)",
        "- [The problem](#the-problem)",
        "- [Security boundary](#security-boundary)",
        "- [Lesson](#lesson)",
        "- [Vocabulary](#vocabulary)",
        "- [Worked examples](#worked-examples)",
        "- [Execution trace](#execution-trace)",
        "- [Common mistakes](#common-mistakes)",
        "- [Security application](#security-application)",
        "- [Exercises](#exercises)",
        "- [Finish line](#finish-line)",
        "",
        "## Why this lesson exists",
        "",
        spec.why,
        "",
        "## Prerequisites",
        "",
        f"Complete Day {spec.day - 1}. Use only the local course fixtures, loopback services, and synthetic records described by the lesson.",
        "",
        "## Outcomes",
        "",
        "By the end of this lesson, you can:",
        "",
        "- explain the concept before using the tool\n- run and modify every worked example\n- test normal, boundary, and failure behavior\n- state the trust boundary and residual risk\n- complete the numbered cybersecurity exercises",
        "",
        "## The problem",
        "",
        spec.problem,
        "",
        "## Security boundary",
        "",
        "This lesson is educational and bounded. It does not authorize public scanning, credential use, interception, exploit delivery, real-user profiling, or changes to systems you do not own.",
        "",
        "## Lesson",
        "",
        "### Vocabulary",
        "",
        spec.vocabulary,
        "",
        "## Worked examples",
        "",
    ]
    for i, (title, teaching, code, result) in enumerate(spec.examples, 1):
        lines += [
            f"### Example {i}: {title}",
            "",
            teaching,
            "",
            "```python",
            code,
            "```",
            "",
            "**What to observe:**",
            "",
            result,
            "",
        ]
    lines += [
        "## Execution trace",
        "",
        spec.trace,
        "",
        "## Common mistakes",
        "",
        spec.mistakes,
        "",
        "## Security application",
        "",
        spec.security,
        "",
        "## Exercises",
        "",
        "Complete the numbered questions in [practice/exercises.md](practice/exercises.md) in order. Use the examples as a starting point, then record the requested output, edge case, and limitation.",
        "",
        "## Finish line",
        "",
        f"Run `python -m course_days.day{spec.day}`, pass the relevant tests, complete the numbered exercises, and explain one edge case aloud or in writing.",
        "",
        "## Mental model",
        "",
        f"> {spec.mental}",
        "",
        "## Limitations",
        "",
        spec.limits,
        "",
        f"[← Day {spec.day - 1}](../{prev_dir}/{prev_dir}.md) · [Day index](../DAY_INDEX.md) · [Day {spec.day + 1} →](../{next_dir}/{next_dir}.md)",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    for spec in SPECS:
        directory = ROOT / DIRS[spec.day]
        (directory / f"{directory.name}.md").write_text(render(spec), encoding="utf-8")
    print("Authored dense teaching chapters for Days 61–80.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
