"""Author dense teaching chapters for Days 101–120."""

from __future__ import annotations

# ruff: noqa: E501
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRS = {
    100: "day_100_project__authorized_local_assessment",
    101: "day_101_secure_sdlc",
    102: "day_102_ci_quality_gates",
    103: "day_103_static_analysis",
    104: "day_104_sbom_and_provenance",
    105: "day_105_secret_detection",
    106: "day_106_containers_and_isolation",
    107: "day_107_cloud_identity_concepts",
    108: "day_108_configuration_drift",
    109: "day_109_security_metrics",
    110: "day_110_project__secure_delivery_pipeline",
    111: "day_111_security_tool_architecture",
    112: "day_112_performance_and_backpressure",
    113: "day_113_advanced_concurrency",
    114: "day_114_failure_injection_and_recovery",
    115: "day_115_privacy_and_retention",
    116: "day_116_research_and_source_evaluation",
    117: "day_117_capstone_planning",
    118: "day_118_capstone_implementation",
    119: "day_119_capstone_security_review",
    120: "day_120_final_demonstration",
}


@dataclass(frozen=True)
class Spec:
    day: int
    title: str
    why: str
    problem: str
    vocabulary: str
    examples: tuple[tuple[str, str, str, str], ...]
    trace: str
    mistakes: str
    security: str
    mental: str
    limits: str


def e(title: str, teaching: str, code: str, result: str):
    return title, teaching, code, result


SPECS = [
    Spec(
        101,
        "Secure SDLC and Security Requirements",
        "Security is cheaper to reason about before code and deployment decisions harden. A secure software-development lifecycle turns assets, abuse cases, controls, tests, and ownership into ordinary engineering work.",
        "Translate a synthetic case API requirement into security acceptance criteria that can be tested before release.",
        "An abuse case describes harmful use. A security requirement states a control. Acceptance criteria define observable evidence. A threat model records assumptions and residual risk.",
        (
            e(
                "Name an asset",
                "Begin with what the feature must protect.",
                'asset = {"name": "synthetic case records", "owner": "course", "impact": "privacy"}\nprint(asset)',
                "The asset and owner are explicit.",
            ),
            e(
                "Write an abuse case",
                "Describe a harmful condition without writing an exploit.",
                'abuse = "A caller reads a case outside its assigned scope."\nprint(abuse)',
                "The misuse is testable as an authorization case.",
            ),
            e(
                "Write a requirement",
                "Turn the abuse case into a control.",
                'requirement = "The service must check object scope before returning a case."\nprint(requirement)',
                "The requirement states behavior.",
            ),
            e(
                "Define acceptance evidence",
                "A requirement needs a proof method.",
                'acceptance = {"case": "cross-object read", "expected": 403, "test": "test_authorization_matrix"}\nprint(acceptance)',
                "The control has observable evidence.",
            ),
            e(
                "Assign ownership",
                "Unowned requirements become forgotten requirements.",
                'print({"owner": "service-team", "review": "before release"})',
                "The lifecycle includes responsibility.",
            ),
        ),
        "The requirement begins with an asset and abuse case, becomes a control, receives a testable acceptance criterion, and is assigned to an owner before implementation.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| security at the end | architecture is expensive to change | write requirements early |\n| vague secure language | no test can prove it | name observable behavior |\n| no owner | control is forgotten | assign responsibility |\n| exploit-first | scope and safety drift | use abuse cases and fixtures |\n| no residual risk | release claim is overconfident | record limits |",
        "Use the local synthetic case API only. Turn its security requirements into tests and review items; do not build new attack capability.",
        "Secure SDLC is a repeatable path from asset and abuse case to owned, testable control.",
        "No lifecycle prevents all defects; security requirements need domain, privacy, and operational review.",
    ),
    Spec(
        102,
        "CI Quality Gates",
        "Continuous integration makes quality checks repeatable on every change. A gate should be fast, explainable, and proportionate, while a failure should stop unsafe delivery rather than be ignored.",
        "Design a local CI-like sequence that formats, lints, compiles, tests, checks links, and records artifacts.",
        "A quality gate is a required check. CI runs checks in an automated environment. An artifact is an output such as a test report. A false negative lets a defect pass.",
        (
            e(
                "List gates",
                "The gate sequence is a policy object.",
                'gates = ["format", "lint", "compile", "test", "links"]\nprint(gates)',
                "The required checks are visible.",
            ),
            e(
                "Represent a result",
                "Each check needs status and evidence.",
                'result = {"name": "pytest", "status": "passed", "artifact": "test-report.txt"}\nprint(result)',
                "The result is reviewable.",
            ),
            e(
                "Fail closed",
                "A failed required gate should not report success.",
                'required = ["lint", "tests"]\nresults = {"lint": "passed", "tests": "failed"}\nprint(all(results[name] == "passed" for name in required))',
                "`False` blocks delivery.",
            ),
            e(
                "Separate flaky from failed",
                "A retry policy should not hide a persistent failure.",
                'print({"status": "flaky", "needs_review": True, "release": False})',
                "The gate remains conservative.",
            ),
            e(
                "Store safe artifacts",
                "Reports should not contain secrets or private environment values.",
                'artifact_policy = {"tests": True, "environment_dump": False, "secrets": False}\nprint(artifact_policy)',
                "The output policy is explicit.",
            ),
        ),
        "The pipeline runs deterministic checks, captures minimal artifacts, aggregates statuses, and refuses delivery when a required gate fails or is unknown.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| gate only locally | CI differs from developer | reproduce environment |\n| ignore failure | unsafe change ships | fail closed |\n| dump environment | secrets leak | minimize artifacts |\n| flaky equals pass | defects hide | quarantine and review |\n| too many slow checks | feedback is ignored | stage and prioritize |",
        "Run gates only on the course repository. Never upload private logs or credentials to a CI artifact.",
        "A quality gate is a decision boundary: required evidence passes or delivery stops.",
        "CI results can be wrong when dependencies, runners, tests, or configuration differ from production.",
    ),
    Spec(
        103,
        "Static Analysis and Code Review Signals",
        "Static tools find patterns without executing the program. They are valuable review assistants when their findings are understood, triaged, and combined with tests rather than treated as proof of security.",
        "Run a local lint and type-check policy, classify findings, and record justified exceptions narrowly.",
        "Static analysis inspects source. A rule identifies a pattern. A suppression disables a finding. A false positive is a finding that does not represent a defect in context.",
        (
            e(
                "Run a checker",
                "A command returns findings for review.",
                'findings = [{"rule": "E501", "file": "module.py", "line": 10}]\nprint(findings)',
                "The finding points to a location.",
            ),
            e(
                "Classify severity",
                "Not every warning has the same release impact.",
                'finding = {"rule": "unsafe-path", "severity": "high", "status": "open"}\nprint(finding)',
                "The status drives action.",
            ),
            e(
                "Justify an exception",
                "A suppression should be narrow and documented.",
                'exception = {"rule": "line-length", "scope": "embedded fixture only", "reason": "generated teaching text"}\nprint(exception)',
                "The exception does not disable all checks.",
            ),
            e(
                "Combine with tests",
                "Static output and runtime behavior answer different questions.",
                'evidence = {"lint": "passed", "tests": "passed", "security_review": "pending"}\nprint(evidence)',
                "The evidence remains multidimensional.",
            ),
            e(
                "Review a diff",
                "A clean tool result does not replace human review.",
                'review = {"diff_read": True, "assumptions_checked": True, "owner": "student"}\nprint(review)',
                "The review record is explicit.",
            ),
        ),
        "Source is checked, findings are categorized, narrow exceptions are justified, tests add runtime evidence, and a human reviews assumptions before release.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| tool equals proof | behavior is untested | add tests and review |\n| disable rule globally | signal disappears | narrow suppression |\n| ignore all warnings | debt accumulates | triage and own findings |\n| copy tool config blindly | checks mismatch code | understand rules |\n| no version | result changes silently | record tool/version |",
        "Run only local tools on course code. Do not upload source containing private material to an external analyzer.",
        "Static analysis is a signal generator; engineers interpret the signal and prove behavior with tests and review.",
        "Static tools have blind spots, false positives, and configuration dependence.",
    ),
    Spec(
        104,
        "SBOM and Provenance",
        "Delivery teams need to know which components produced an artifact. An SBOM-like inventory and provenance record help answer what was built, from which source, with which tools, and under which review.",
        "Create a small provenance record for a synthetic course artifact without claiming that metadata proves safety.",
        "An SBOM inventories software components. Provenance records origin and build steps. An artifact is a produced file or image. Reproducibility means rebuilding from the same declared inputs.",
        (
            e(
                "List components",
                "The inventory begins with names and versions.",
                'sbom = [{"name": "python", "version": "3.x"}, {"name": "course-tool", "version": "1.0"}]\nprint(sbom)',
                "The components are named.",
            ),
            e(
                "Record source",
                "Source commit links output to a change.",
                'provenance = {"commit": "abc123", "branch": "course-redesign"}\nprint(provenance)',
                "The source reference is explicit.",
            ),
            e(
                "Record builder",
                "The environment affects output.",
                'provenance.update({"builder": "local-ci", "python": "3.x"})\nprint(provenance)',
                "The builder context is visible.",
            ),
            e(
                "Hash an artifact",
                "A digest identifies the bytes that were produced.",
                'import hashlib\nprint(hashlib.sha256(b"training-artifact").hexdigest()[:12])',
                "A stable fingerprint is recorded.",
            ),
            e(
                "State unknowns",
                "Inventory is evidence, not a security guarantee.",
                'print({"unknown": ["transitive build behavior", "future vulnerability"]})',
                "The report remains honest.",
            ),
        ),
        "The artifact is linked to source, builder, components, build steps, and digest; reviewers can compare records without treating the record as proof of a harmless supply chain.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| only direct dependencies | transitive code is missed | inventory full graph |\n| no source commit | artifact cannot be traced | record provenance |\n| hash equals trust | origin is overclaimed | protect source and process |\n| stale SBOM | current artifact differs | generate per build |\n| include secrets | metadata leaks | sanitize records |",
        "Use synthetic artifact names and local records. Do not publish private build metadata or install unreviewed packages.",
        "Provenance makes a build’s inputs and steps inspectable; it does not guarantee every component is secure.",
        "SBOM formats, signing, and provenance standards need organizational tooling and verification.",
    ),
    Spec(
        105,
        "Secret Detection and Remediation",
        "Secrets often enter repositories through convenience. Detection is one layer; prevention, removal from history, rotation, and safe reporting complete the response.",
        "Scan synthetic files for token-like values, report locations without printing secrets, and write a remediation plan.",
        "A secret is sensitive authentication material. Detection finds candidates. Rotation invalidates a credential and issues a replacement. False positives are benign matches.",
        (
            e(
                "Use a candidate pattern",
                "Patterns identify candidates, not confirmed secrets.",
                'import re\npattern = re.compile(r"token=[^\\s]+")\nprint(bool(pattern.search("token=training-secret")))',
                "A candidate is found.",
            ),
            e(
                "Redact the match",
                "The report should not reproduce the value.",
                'text = "token=training-secret"\nprint(re.sub(r"(token=)[^\\s]+", r"\\1[REDACTED]", text))',
                "The marker replaces the value.",
            ),
            e(
                "Record location",
                "File and line are useful without full content.",
                'finding = {"file": "fixture.txt", "line": 1, "kind": "token-like"}\nprint(finding)',
                "The location is safe enough for training.",
            ),
            e(
                "Plan rotation",
                "Removing a string from the working tree does not revoke a real credential.",
                'plan = ["revoke", "issue replacement", "remove from history if needed", "review access"]\nprint(plan)',
                "The response steps are explicit.",
            ),
            e(
                "Handle false positives",
                "A pattern may match a placeholder or test value.",
                'print({"candidate": "training-secret", "confirmed": False, "review": True})',
                "The result is not overclaimed.",
            ),
        ),
        "The scanner reads bounded files, identifies candidate patterns, redacts values before reporting, records location and confidence, and directs real secret response toward revocation and access review.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| print match | secret leaks in report | redact before output |\n| delete only | credential remains valid | revoke and rotate |\n| scan private tree | scope violation | use fixtures |\n| pattern equals secret | false positives | review candidates |\n| forget history | old commit retains value | assess history and access |",
        "Use placeholders only. If a real credential is ever exposed, stop, notify the owner privately, and follow the repository security policy; do not paste it into issues or reports.",
        "Secret detection finds candidates; remediation removes utility through revocation, rotation, history handling, and access review.",
        "Detection patterns miss formats and can create false positives; real secret response requires the credential owner.",
    ),
    Spec(
        106,
        "Containers and Isolation Concepts",
        "Containers package a process and its dependencies, but they are not magical security boundaries. Images, privileges, mounts, networks, and secrets still need explicit policy.",
        "Describe a least-privilege local container configuration without running untrusted images or altering the host.",
        "An image is a packaged filesystem and metadata. A container is a running instance. A mount shares host data. Isolation reduces but does not eliminate risk.",
        (
            e(
                "Name the image source",
                "Source and digest matter for reproducibility.",
                'image = {"name": "course-app", "source": "local build", "digest": "reviewed"}\nprint(image)',
                "The image provenance is visible.",
            ),
            e(
                "Drop privileges",
                "A process should not run as root without a reason.",
                'runtime = {"user": "non-root", "read_only_fs": True}\nprint(runtime)',
                "The default is restrictive.",
            ),
            e(
                "Limit mounts",
                "Mounts cross the container-host boundary.",
                'mounts = [{"source": "training-output", "target": "/output", "read_only": False}]\nprint(mounts)',
                "Only the intended directory is shared.",
            ),
            e(
                "Disable unnecessary network",
                "A local tool may not need outbound access.",
                'network = {"mode": "none", "reason": "fixture-only"}\nprint(network)',
                "The capability is removed.",
            ),
            e(
                "State residual risk",
                "Isolation is a layer, not a guarantee.",
                'print({"unknown": ["kernel", "runtime", "image dependencies"]})',
                "The report remains cautious.",
            ),
        ),
        "The deployment declares image provenance, user, filesystem, mounts, network, resources, and secrets; the runtime receives only capabilities required by the local task.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| image tag as provenance | tag can move | record digest/source |\n| root by default | compromise impact grows | non-root |\n| mount home directory | host data exposed | narrow mount |\n| network by default | outbound scope expands | disable or allowlist |\n| container equals sandbox | controls are overtrusted | defense in depth |",
        "Use diagrams or configuration snippets only; do not run unreviewed images or mount private host paths.",
        "Isolation is a capability budget around a process, not an excuse to skip source, image, host, and network review.",
        "Container security depends on runtime, kernel, orchestrator, image, and host configuration.",
    ),
    Spec(
        107,
        "Cloud Identity Concepts",
        "Cloud security often fails when an identity receives more permission than its task needs or when roles, resources, and trust relationships are unclear. This lesson stays conceptual and local.",
        "Model a least-privilege role for a synthetic report worker without connecting to a cloud account.",
        "An identity is a principal. A role is a set of permissions. A resource is an object. Least privilege grants only required actions. A trust policy controls who may assume a role.",
        (
            e(
                "Name a principal",
                "Use a fictional workload identity.",
                'principal = {"name": "training-report-worker", "type": "workload"}\nprint(principal)',
                "The identity is explicit.",
            ),
            e(
                "List actions",
                "Permissions should be specific.",
                'policy = {"actions": ["read_case_fixture", "write_report"], "resources": ["training-only"]}\nprint(policy)',
                "The actions and resources are bounded.",
            ),
            e(
                "Deny broad actions",
                "A negative permission makes the boundary visible.",
                'print({"not_allowed": ["admin", "delete_source", "public_network"]})',
                "The role is narrow.",
            ),
            e(
                "Record trust",
                "Role assumption has a caller condition.",
                'trust = {"allowed_principal": "training-runner", "environment": "test"}\nprint(trust)',
                "The trust relationship is explicit.",
            ),
            e(
                "Review unused access",
                "Permissions should be reduced when no longer needed.",
                'print({"review": "remove unused actions", "cadence": "documented"})',
                "The lifecycle is part of least privilege.",
            ),
        ),
        "The designer names principal, actions, resources, trust conditions, and lifecycle review before any cloud configuration is applied.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| admin role for convenience | blast radius grows | narrow actions/resources |\n| resource wildcard | access crosses cases | scope resource identifiers |\n| identity equals trust | any caller assumes role | define trust policy |\n| credentials in code | secrets leak | use platform identity mechanisms |\n| never review | stale access persists | schedule review |",
        "Use fictional policy objects only. Do not log into or modify a cloud account for this lesson.",
        "Cloud identity is a relationship among principal, action, resource, and trust conditions.",
        "Provider semantics vary; production identity design needs platform specialists and actual ownership.",
    ),
    Spec(
        108,
        "Configuration Drift",
        "A secure configuration can become insecure after a manual change, deployment override, dependency update, or environment difference. Drift detection compares an approved baseline to effective state.",
        "Compare synthetic baseline and runtime configuration, classify drift, and assign a review action.",
        "Drift is a difference from an approved state. Effective configuration is what the process actually uses. A baseline is a reviewed reference.",
        (
            e(
                "Create a baseline",
                "A baseline includes version and owner.",
                'baseline = {"version": 2, "debug": False, "body_limit": 1000000, "owner": "course"}\nprint(baseline)',
                "The approved state is visible.",
            ),
            e(
                "Read runtime state",
                "Effective state may differ from source configuration.",
                'runtime = {"version": 2, "debug": True, "body_limit": 1000000}\nprint(runtime)',
                "Runtime debug is drifted.",
            ),
            e(
                "Compare keys",
                "Each difference needs field and before/after values.",
                "changes = {k: (baseline[k], runtime.get(k)) for k in baseline if baseline[k] != runtime.get(k)}\nprint(changes)",
                "`debug` differs.",
            ),
            e(
                "Classify severity",
                "A change’s effect determines priority.",
                'finding = {"field": "debug", "severity": "high", "status": "needs_review"}\nprint(finding)',
                "The drift is actionable.",
            ),
            e(
                "Avoid auto-remediation",
                "Report first when the fix could affect service.",
                'print({"remediate": False, "next": "owner review"})',
                "The tool does not change the system.",
            ),
        ),
        "The auditor loads a versioned baseline, captures effective state, computes field-level differences, classifies impact, and sends a review item without silently changing configuration.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| source config only | override is missed | inspect effective state |\n| auto-fix all drift | outage or data loss | report and approve |\n| no version | baseline meaning is unclear | version it |\n| ignore missing field | control disappears | mark unknown |\n| log secrets | configuration leaks | redact |",
        "Use synthetic dictionaries and local files. Do not inspect or remediate real deployment configuration.",
        "Drift detection compares approved intent with effective reality and makes change visible.",
        "Configuration is dynamic and provider-specific; drift reports need owner review and deployment context.",
    ),
    Spec(
        109,
        "Security Metrics and Measurement",
        "Metrics influence decisions. A good metric defines unit, population, time window, data quality, and action; a bad metric rewards gaming or hides uncertainty.",
        "Design three synthetic metrics for test quality, detection review, and remediation without using real organizational data.",
        "A metric is a defined measurement. A denominator is the population used. Coverage measures what was observed. A leading indicator predicts work; a lagging indicator records outcome.",
        (
            e(
                "Define a ratio",
                "A metric must state numerator and denominator.",
                "passed = 18\ntotal = 20\nprint(passed / total)",
                "`0.9`, or 90% if reported clearly.",
            ),
            e(
                "Name the population",
                "A percentage without population is misleading.",
                'metric = {"name": "tests_passed", "population": "required checks", "window": "one commit"}\nprint(metric)',
                "The context travels with the number.",
            ),
            e(
                "Add data quality",
                "Missing telemetry affects confidence.",
                'metric["data_quality"] = "complete"\nprint(metric)',
                "The quality field is explicit.",
            ),
            e(
                "Avoid vanity metrics",
                "A high count may not mean safer behavior.",
                'print({"metric": "alerts_closed", "warning": "closure speed can hide quality"})',
                "The interpretation is cautious.",
            ),
            e(
                "Attach action",
                "Measurement should change a decision.",
                'metric["action"] = "review failed gates"\nprint(metric)',
                "The metric has purpose.",
            ),
        ),
        "The metric definition identifies population, unit, time window, data quality, and decision; only then are values calculated and interpreted.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| count without denominator | progress is unclear | define population |\n| optimize number | behavior is gamed | pair measures with review |\n| missing equals zero | quality looks better | report missingness |\n| no time window | trends mix periods | define window |\n| metric equals security | complexity is hidden | state limitations |",
        "Use invented values and document that they are examples. Do not claim the metrics describe a real team or organization.",
        "A security metric is a measurement contract tied to a decision, not a badge of safety.",
        "Metrics can be biased, incomplete, and gamed; qualitative review remains essential.",
    ),
    Spec(
        110,
        "Project: Secure Delivery Pipeline",
        "This project composes SDLC requirements, CI gates, static analysis, provenance, secret detection, isolation, identity, drift, and metrics into a delivery decision that can be inspected and repeated.",
        "Design a local pipeline that either produces a reviewed artifact or stops with a clear reason.",
        "A delivery pipeline is a sequence of build and verification stages. A release decision is the final policy result. Evidence artifacts support review.",
        (
            e(
                "Define stages",
                "The pipeline should show where controls run.",
                'stages = ["requirements", "tests", "lint", "secrets", "sbom", "artifact", "review"]\nprint(stages)',
                "The sequence is visible.",
            ),
            e(
                "Aggregate gates",
                "A required failure blocks release.",
                'gates = {"tests": True, "lint": True, "secrets": False}\nprint(all(gates.values()))',
                "`False` blocks delivery.",
            ),
            e(
                "Create provenance",
                "The artifact needs source and component context.",
                'artifact = {"commit": "abc123", "components": ["python"], "digest": "reviewed"}\nprint(artifact)',
                "The output is traceable.",
            ),
            e(
                "Review drift",
                "Effective configuration is part of delivery evidence.",
                'print({"config_baseline": "v2", "drift": False})',
                "The pipeline records configuration state.",
            ),
            e(
                "Write decision",
                "A decision must say why it passed or stopped.",
                'decision = {"release": False, "reason": "secret candidate requires review"}\nprint(decision)',
                "The stop is explainable.",
            ),
        ),
        "The pipeline loads requirements, runs checks, captures artifacts, evaluates provenance/configuration/secrets, and returns a release decision with reason and owner.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| gate only tests | supply chain is ignored | include provenance and secrets |\n| secrets report value | leak worsens | redact |\n| pass on unknown | blind spot becomes release | fail closed or mark blocked |\n| no owner | blocked work stalls | assign remediation |\n| artifact without source | cannot reproduce | record commit/build |",
        "Use local tools and synthetic records. Do not build a production deployment or upload private pipeline artifacts.",
        "Secure delivery is evidence aggregation plus a policy decision; a green test suite is only one input.",
        "A local pipeline does not prove production security, compliant provenance, or absence of malicious dependencies.",
    ),
    Spec(
        111,
        "Security Tool Architecture",
        "A mature security tool needs clear modules for collection, parsing, policy, storage, reporting, and orchestration. Architecture prevents a proof-of-concept from becoming an unreviewable tool.",
        "Design module boundaries and dependency directions for a local detection utility.",
        "Architecture describes components and relationships. Dependency direction says which layer may call which. An adapter translates external systems into internal interfaces.",
        (
            e(
                "Name layers",
                "Layering makes responsibility reviewable.",
                'layers = ["cli", "orchestration", "policy", "domain", "adapters"]\nprint(layers)',
                "The layers are ordered.",
            ),
            e(
                "Define an interface",
                "A protocol lets tests substitute a fixture reader.",
                "class Reader:\n    def read(self, limit: int) -> list[str]:\n        raise NotImplementedError",
                "The caller depends on behavior.",
            ),
            e(
                "Keep policy pure",
                "Policy should not open files or make network calls.",
                'def decide(event):\n    return event.get("severity", 0) >= 7',
                "The decision is testable.",
            ),
            e(
                "Use an adapter",
                "The adapter owns external representation.",
                'adapter = {"source": "fixture", "target": "domain event"}\nprint(adapter)',
                "The translation boundary is explicit.",
            ),
            e(
                "Document dependencies",
                "A diagram is only useful if it states direction.",
                'edges = [("cli", "orchestration"), ("orchestration", "policy"), ("adapters", "domain")]\nprint(edges)',
                "The architecture can be reviewed.",
            ),
        ),
        "Input enters through adapters/CLI, becomes domain data, passes pure policy, and returns through reporting; external effects remain at edges.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| policy imports network | tests have side effects | keep policy pure |\n| circular layers | changes spread | define direction |\n| adapter leaks raw fields | domain trusts source | normalize |\n| global configuration | hidden coupling | inject dependencies |\n| diagram without tests | architecture is aspirational | test boundaries |",
        "Use local fixtures and dependency injection. Do not add remote connectors or agentic execution.",
        "Good architecture makes trust boundaries and effects visible in module relationships.",
        "Architecture cannot guarantee correct policy, safe deployment, or team ownership.",
    ),
    Spec(
        112,
        "Performance and Backpressure",
        "Performance is a security property when slow or oversized work can exhaust a service. Measure first, then choose bounded queues, batching, streaming, and rejection policies.",
        "Process a synthetic stream with a bounded queue and explain what happens when the consumer is slower than the producer.",
        "Throughput is work per time. Latency is time per operation. Backpressure limits producers. A queue is a buffer. Rejection is an explicit resource policy.",
        (
            e(
                "Measure a count",
                "Begin with a simple workload measurement.",
                "processed = 100\nseconds = 2\nprint(processed / seconds)",
                "50 records per second.",
            ),
            e(
                "Bound a queue",
                "A finite queue prevents unlimited memory growth.",
                "from queue import Queue\nqueue = Queue(maxsize=3)\nprint(queue.maxsize)",
                "The capacity is explicit.",
            ),
            e(
                "Reject or wait",
                "When full, the producer needs a policy.",
                'policy = {"full_queue": "wait briefly then reject", "report": "backpressure"}\nprint(policy)',
                "The behavior is documented.",
            ),
            e(
                "Batch work",
                "Batches can reduce overhead but increase latency and memory.",
                'batch = [1, 2, 3]\nprint({"size": len(batch), "max": 100})',
                "The batch has a bound.",
            ),
            e(
                "Report incomplete work",
                "Dropped or rejected work must be visible.",
                'print({"accepted": 98, "rejected": 2, "complete": False})',
                "The result does not look perfect.",
            ),
        ),
        "The producer creates bounded work, the queue applies backpressure, the consumer processes within a resource budget, and the report records accepted, rejected, and incomplete items.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| benchmark synthetic only | real workload differs | state assumptions |\n| unbounded queue | memory exhaustion | cap capacity |\n| drop silently | detection gaps | report rejection |\n| batch unlimited | latency/memory grows | cap batch |\n| optimize before measure | complexity without benefit | measure first |",
        "Use small synthetic workloads and local timing. Do not generate load against any external system.",
        "Performance safety is bounded work plus honest accounting of what was rejected or delayed.",
        "Benchmarks vary by hardware, input, Python version, and contention; capacity needs production measurement.",
    ),
    Spec(
        113,
        "Advanced Concurrency and Cancellation",
        "Concurrency at scale introduces cancellation, ordering, shared state, and cleanup problems. Reliable security tooling needs deterministic identifiers and explicit lifecycle control.",
        "Coordinate bounded asynchronous tasks, cancel them cleanly, and preserve result identity.",
        "Cancellation requests work to stop. A future represents pending work. Idempotence means repeating an operation has the same safe effect. A race depends on timing.",
        (
            e(
                "Name tasks",
                "Every task needs an identifier.",
                'tasks = {"fixture-a": "pending", "fixture-b": "pending"}\nprint(tasks)',
                "Results can be joined by id.",
            ),
            e(
                "Limit concurrency",
                "A semaphore caps simultaneous work.",
                "import asyncio\nlimit = asyncio.Semaphore(2)\nprint(limit)",
                "The limit is explicit.",
            ),
            e(
                "Handle cancellation",
                "Cleanup belongs in `finally`.",
                'async def work():\n    try:\n        await asyncio.sleep(0)\n    finally:\n        print("cleanup")',
                "Cleanup runs when the task ends or is cancelled.",
            ),
            e(
                "Make operation idempotent",
                "A repeated report write should not duplicate evidence.",
                'seen = {"fixture-a"}\nprint("fixture-a" in seen)',
                "The identity check prevents duplicate handling.",
            ),
            e(
                "Aggregate states",
                "Mixed success needs a clear summary.",
                'print({"ok": 3, "failed": 1, "cancelled": 1})',
                "The summary preserves failure states.",
            ),
        ),
        "The coordinator creates identified tasks, limits concurrency, handles cancellation and cleanup, aggregates state, and refuses to call a partial run complete.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| no cancellation | tasks keep running | propagate cancellation |\n| shared mutable list | ordering/races | return identified results |\n| duplicate retries | duplicate effects | require idempotence |\n| ignore cancelled | incomplete run looks green | count cancelled |\n| no cleanup | resources remain | use finally/context managers |",
        "Use `asyncio` with local sleeps and fixtures only. Do not create concurrent network clients for public systems.",
        "Reliable concurrency is bounded, cancellable, and explicit about partial completion.",
        "Concurrency correctness is difficult to prove with small tests; production systems need load, failure, and operational testing.",
    ),
    Spec(
        114,
        "Failure Injection and Recovery",
        "A resilient tool is not one that never fails; it is one whose failure modes are expected, bounded, observable, and recoverable without corrupting evidence.",
        "Inject controlled timeout, malformed data, and write failures into a local pipeline and verify recovery behavior.",
        "Failure injection deliberately creates a test condition. Recovery restores an acceptable state. A retryable failure differs from a permanent failure. A circuit breaker stops repeated attempts.",
        (
            e(
                "Inject a timeout",
                "A fake function makes the failure reproducible.",
                'def fake_timeout():\n    raise TimeoutError("training timeout")\ntry:\n    fake_timeout()\nexcept TimeoutError as error:\n    print(type(error).__name__)',
                "The timeout is classified.",
            ),
            e(
                "Recover with fallback",
                "A fallback must not claim full success.",
                'result = {"status": "degraded", "complete": False}\nprint(result)',
                "The degraded state is visible.",
            ),
            e(
                "Stop repeated attempts",
                "A breaker prevents repeated failure amplification.",
                'breaker = {"state": "open", "reason": "repeated training failures"}\nprint(breaker)',
                "Further work is stopped.",
            ),
            e(
                "Preserve partial output",
                "A checkpoint can make recovery resumable.",
                'checkpoint = {"processed": 7, "last_id": "fixture-7"}\nprint(checkpoint)',
                "The progress is explicit.",
            ),
            e(
                "Test recovery",
                "The test asserts state and cleanup, not only no exception.",
                'assert result["status"] == "degraded"\nprint("recovery contract passed")',
                "The recovery behavior is tested.",
            ),
        ),
        "The injected failure enters a known category, the pipeline stops or falls back according to policy, records partial state, cleans resources, and reports incomplete work.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| catch all | failure looks successful | classify |\n| retry permanent error | repeated damage | stop |\n| fallback as full data | users overtrust | mark degraded |\n| no checkpoint | restart duplicates work | persist safe progress |\n| inject in production | outage | disposable fixture only |",
        "Inject failures only into pure local components or disposable fixtures. Never deliberately disrupt a real service.",
        "Resilience is explicit failure state plus bounded recovery and cleanup.",
        "Failure injection in a toy pipeline cannot prove production resilience or recovery-time objectives.",
    ),
    Spec(
        115,
        "Privacy and Retention",
        "Security tooling often collects more personal data than it needs. Privacy engineering asks what is necessary, how long it is kept, who can access it, and how it is deleted.",
        "Design a retention policy for synthetic case records and implement minimization and deletion metadata.",
        "Data minimization collects only what is needed. Retention is how long data is kept. A deletion record proves an action without preserving the deleted content.",
        (
            e(
                "Classify fields",
                "Not every field has the same sensitivity.",
                'fields = {"case_id": "low", "message": "medium", "token": "secret"}\nprint(fields)',
                "Sensitivity is explicit.",
            ),
            e(
                "Minimize report",
                "A report can omit raw message and token.",
                'report = {"case_id": "training-115", "status": "review"}\nprint(report)',
                "Only necessary fields remain.",
            ),
            e(
                "Set retention",
                "Retention needs purpose and period.",
                'policy = {"purpose": "training", "retention_days": 7, "owner": "course"}\nprint(policy)',
                "The policy is concrete.",
            ),
            e(
                "Record deletion",
                "The record can prove deletion without retaining content.",
                'deletion = {"case_id": "training-115", "deleted_at": "now", "content": "not stored"}\nprint(deletion)',
                "The audit record is minimized.",
            ),
            e(
                "Restrict access",
                "Access policy is part of privacy.",
                'print({"readers": ["student"], "public": False})',
                "The data is not public.",
            ),
        ),
        "The system classifies and minimizes fields, applies retention, restricts access, deletes content at the end of purpose, and keeps only a safe deletion record.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| collect just in case | privacy scope grows | minimize |\n| retention forever | breach impact grows | define purpose and period |\n| deletion without proof | control is unreviewable | keep safe metadata |\n| hash equals anonymize | identifiers remain linkable | assess re-identification |\n| public sample data | private fields leak | synthetic fixtures |",
        "Use synthetic case data only. Do not process personal logs, names, messages, or credentials.",
        "Privacy is a lifecycle of collection, purpose, access, retention, minimization, and deletion.",
        "Privacy obligations vary by jurisdiction and organization; a short policy is not legal advice.",
    ),
    Spec(
        116,
        "Research and Source Evaluation",
        "Security learners meet conflicting tutorials, outdated commands, and impressive but unsafe demonstrations. Research skill means checking primary sources, version, scope, evidence, and reproducibility.",
        "Evaluate three synthetic source records and choose which one can support a course claim.",
        "A primary source is closest to the authority or specification. A secondary source explains or summarizes. Currency is how up to date a source is. Reproducibility means another learner can verify the claim.",
        (
            e(
                "Record a source",
                "A source record needs title, publisher, date, and URL.",
                'source = {"title": "Python docs", "publisher": "Python", "date": "current", "url": "https://docs.python.org/3/"}\nprint(source)',
                "The provenance is visible.",
            ),
            e(
                "Check claim fit",
                "A good source supports the exact claim, not just the topic.",
                'claim = "input returns text"\nsource["supports"] = claim\nprint(source)',
                "The relationship is recorded.",
            ),
            e(
                "Compare authority",
                "An official specification may outrank an unsourced short video for exact behavior.",
                'ranking = ["official docs", "recognized course", "reviewed educator", "unsourced post"]\nprint(ranking)',
                "The selection rule is explicit.",
            ),
            e(
                "Record version",
                "Commands change across versions.",
                'source["version"] = "Python 3"\nprint(source)',
                "The applicability is visible.",
            ),
            e(
                "State uncertainty",
                "A source can be useful without proving every detail.",
                'print({"confidence": "medium", "follow_up": "run local example"})',
                "The learner is directed to verify.",
            ),
        ),
        "The researcher defines a claim, finds the closest authoritative source, records version and date, checks exact support, reproduces locally, and cites uncertainty or alternatives.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| popularity equals accuracy | outdated advice wins | check authority and currency |\n| snippet as evidence | context is missing | open the source |\n| no version | command fails later | record version |\n| video without timestamp | learner cannot locate section | add exact segment |\n| cite topic not claim | support is vague | map claim to source |",
        "Use public official documentation and reviewed educational sources. Do not follow suspicious instructions or download-and-run unknown artifacts.",
        "Research is a reproducible claim-to-source-to-local-check process.",
        "No source is automatically current or complete; security decisions need expert and organizational review.",
    ),
    Spec(
        117,
        "Capstone Planning",
        "A capstone should demonstrate judgment, not become an unbounded collection of tools. Planning turns a broad security goal into a scoped problem, architecture, milestones, tests, and demonstration evidence.",
        "Plan a defensive Python capstone that combines local telemetry, safe validation, reporting, tests, and one specialization track.",
        "A capstone is an integrated project. A milestone is a bounded increment. A decision log records important trade-offs. A definition of done states evidence.",
        (
            e(
                "Choose a problem",
                "A good problem has a user, asset, and safe boundary.",
                'problem = {"user": "student analyst", "asset": "synthetic events", "boundary": "local fixtures"}\nprint(problem)',
                "The project is bounded.",
            ),
            e(
                "Define milestones",
                "Milestones reduce a large project into demonstrable steps.",
                'milestones = ["schema", "parser", "policy", "tests", "report", "review"]\nprint(milestones)',
                "The order is visible.",
            ),
            e(
                "Choose architecture",
                "Reuse tested modules rather than copy code.",
                'architecture = {"input": "fixture", "core": "pure policy", "output": "redacted report"}\nprint(architecture)',
                "The design has boundaries.",
            ),
            e(
                "Define done",
                "Completion needs artifacts and explanation.",
                'done = ["tests pass", "README", "threat model", "sample output", "limitations"]\nprint(done)',
                "The evidence is concrete.",
            ),
            e(
                "Record a trade-off",
                "A decision log explains why the project is shaped this way.",
                'decision = {"choice": "fixture-only", "benefit": "safe reproducibility", "cost": "not production telemetry"}\nprint(decision)',
                "The trade-off is honest.",
            ),
        ),
        "The capstone moves from user/asset/boundary to milestones, architecture, evidence, and trade-offs. Scope is reduced until the learner can finish and explain it.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| build every tool | project never finishes | choose one outcome |\n| no threat model | features create risk | model before code |\n| demo only | no tests or evidence | define done |\n| copy libraries blindly | understanding is missing | explain decisions |\n| production claims | local project is overclaimed | state limits |",
        "Choose a local defensive capstone. No public data collection, exploit capability, or real credential integration.",
        "A capstone is a bounded argument that the learner can design, build, test, review, and explain a security tool.",
        "A plan cannot predict every implementation problem; revise scope when evidence shows it is too large.",
    ),
    Spec(
        118,
        "Capstone Implementation",
        "Implementation is where design decisions meet real code. The learner should build incrementally, keep the core testable, and preserve the evidence needed for a final demonstration.",
        "Implement the capstone in small vertical slices and record testable outputs at each milestone.",
        "A vertical slice crosses input, core behavior, and output. A checkpoint is evidence at a milestone. Refactoring changes structure while preserving behavior.",
        (
            e(
                "Build the first slice",
                "A tiny end-to-end path reveals integration mistakes early.",
                'slice = {"input": "one fixture event", "decision": "review", "output": "one report row"}\nprint(slice)',
                "The first slice is demonstrable.",
            ),
            e(
                "Add a failing test",
                "A test can state the next behavior before implementation.",
                'expected = {"invalid_severity": "rejected"}\nprint(expected)',
                "The contract guides code.",
            ),
            e(
                "Keep a checkpoint",
                "Save outputs after each milestone.",
                'checkpoint = {"milestone": "parser", "tests": 4, "artifact": "sample-report.json"}\nprint(checkpoint)',
                "Progress is measurable.",
            ),
            e(
                "Refactor safely",
                "A refactor should preserve observable contracts.",
                'before = {"status": 200, "body_fields": ["case_id"]}\nafter = before.copy()\nprint(before == after)',
                "The expected behavior remains equal.",
            ),
            e(
                "Document a limitation",
                "Implementation notes should prevent misuse.",
                'print({"limitation": "fixture-only", "not": "production detector"})',
                "The scope remains visible.",
            ),
        ),
        "The learner implements one slice, writes tests, records output, refactors under test protection, and documents limitations before adding the next feature.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| build all layers at once | debugging is overwhelming | vertical slices |\n| no tests until end | regressions hide | test each milestone |\n| copy output as proof | behavior is not understood | explain and reproduce |\n| ignore cleanup | artifacts accumulate | reset after each run |\n| overbuild | capstone loses focus | cut scope |",
        "Use the planned local fixtures and safe modules. Do not expand the capstone into scanning, credential handling, or remote automation.",
        "Implementation is a sequence of small, tested, explainable slices that preserve the capstone argument.",
        "A local capstone can contain defects; review and retesting are part of the work.",
    ),
    Spec(
        119,
        "Capstone Security Review",
        "A final review asks whether the capstone’s claims are supported, whether the controls are correctly placed, and whether the demonstration could mislead a user.",
        "Review a capstone with a checklist covering inputs, secrets, authorization, resources, evidence, tests, and limitations.",
        "A security review challenges assumptions. A control is effective only when it protects the intended boundary. A residual risk is a known remaining weakness.",
        (
            e(
                "Review inputs",
                "List every external or fixture-controlled input.",
                'inputs = ["fixture path", "JSON record", "CLI limit"]\nprint(inputs)',
                "The review surface is explicit.",
            ),
            e(
                "Review secrets",
                "Search for values and unsafe logging paths.",
                'secret_controls = {"source": False, "logs": False, "fixtures": False}\nprint(secret_controls)',
                "No secret source is intended.",
            ),
            e(
                "Review authorization",
                "A tool must state who can invoke each action.",
                'auth = {"local_user": True, "remote_admin": False, "target": "fixture"}\nprint(auth)',
                "The authority is bounded.",
            ),
            e(
                "Review resources",
                "Limits should cover input, output, time, and concurrency.",
                'limits = {"lines": 100, "bytes": 1000000, "seconds": 10, "workers": 2}\nprint(limits)',
                "The resource policy is visible.",
            ),
            e(
                "Write residual risk",
                "A review ends with what remains and who accepts it.",
                'risk = {"item": "synthetic rules miss real patterns", "owner": "course", "accepted": True}\nprint(risk)',
                "The limitation is owned.",
            ),
        ),
        "The reviewer walks input to output, checks controls at boundaries, runs tests and negative cases, inspects artifacts and secrets, and records residual risks rather than declaring absolute security.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| review only code | setup and deployment ignored | inspect whole path |\n| green tests equals safe | threats are untested | use threat model |\n| no negative cases | rejection paths fail | add boundary tests |\n| hide residual risk | users overtrust | state owner and acceptance |\n| review author alone | blind spots persist | use another reviewer |",
        "Review the local capstone only. Do not use the review to justify testing an external target or collecting real data.",
        "Security review is a reasoned challenge to the system’s claims, controls, evidence, and limits.",
        "A review is bounded by reviewer skill, time, tools, and available evidence; it is not a guarantee.",
    ),
    Spec(
        120,
        "Final Demonstration and Engineering Judgment",
        "The final day is not a victory lap over copied code. It demonstrates that the learner can explain a system, run it safely, show evidence, defend design choices, and state what the system cannot prove.",
        "Prepare a final demonstration of the capstone from clean setup through tests, safe sample run, threat model, and retrospective.",
        "A demonstration is a repeatable presentation of behavior. Engineering judgment weighs trade-offs under constraints. A retrospective records learning and next improvements.",
        (
            e(
                "Start clean",
                "A demonstration should prove setup, not depend on hidden state.",
                'setup = {"clone": True, "venv": True, "tests": "pass", "fixtures": "present"}\nprint(setup)',
                "The starting conditions are visible.",
            ),
            e(
                "Explain architecture",
                "Name input, core policy, effects, and output.",
                'architecture = ["fixture", "parser", "pure policy", "redacted report"]\nprint(" -> ".join(architecture))',
                "The data flow is explainable.",
            ),
            e(
                "Run a normal case",
                "Show expected output and why it is correct.",
                'demo = {"input": "valid fixture", "status": "review", "evidence": ["line-2"]}\nprint(demo)',
                "The run is reproducible.",
            ),
            e(
                "Run a failure case",
                "A mature demo shows safe rejection and incomplete states.",
                'failure = {"input": "invalid fixture", "status": "rejected", "secret_leaked": False}\nprint(failure)',
                "The negative behavior is visible.",
            ),
            e(
                "Give the retrospective",
                "Explain one decision, one weakness, and one next step.",
                'retro = {"decision": "fixture-only", "weakness": "no production telemetry", "next": "improve schema tests"}\nprint(retro)',
                "The learner shows judgment instead of certainty.",
            ),
        ),
        "The demonstration starts from clean setup, explains architecture, runs normal and failure cases, shows tests and evidence, names safety boundaries, and closes with limitations and next work.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| demo only happy path | reliability is hidden | show rejection and failure |\n| read slides only | understanding is untested | run and explain code |\n| claim production ready | local evidence is overclaimed | state scope |\n| hide trade-offs | judgment is invisible | explain decisions |\n| no reset | demo cannot repeat | clean environment |",
        "The final demonstration remains local, synthetic, resettable, and authorized. It must never include real credentials, private data, public scanning, or destructive actions.",
        "Engineering judgment is the ability to make, test, explain, and limit a decision under real constraints.",
        "Completing the course does not make someone an advanced engineer by itself; continued practice, mentorship, university work, code review, and responsible experience remain essential.",
    ),
]


def render(spec: Spec) -> str:
    prev_dir = DIRS[spec.day - 1]
    next_dir = DIRS[spec.day + 1] if spec.day < 120 else DIRS[spec.day]
    lines = [
        f"# Day {spec.day}: {spec.title}",
        "",
        f"[← Day {spec.day - 1}](../{prev_dir}/{prev_dir}.md) · [Day index](../DAY_INDEX.md) · [Day {spec.day + 1} →](../{next_dir}/{next_dir}.md)",
        "",
        "## Table of Contents",
        "",
        "- [Why this lesson exists](#why-this-lesson-exists)",
        "- [Prerequisites](#prerequisites)",
        "- [Outcomes](#outcomes)",
        "- [The problem](#the-problem)",
        "- [Security boundary](#security-boundary)",
        "- [Lesson](#lesson)",
        "- [Vocabulary](#vocabulary)",
        "- [Worked examples](#worked-examples)",
        "- [Execution trace](#execution-trace)",
        "- [Common mistakes](#common-mistakes)",
        "- [Security application](#security-application)",
        "- [Exercises](#exercises)",
        "- [Finish line](#finish-line)",
        "",
        "## Why this lesson exists",
        "",
        spec.why,
        "",
        "## Prerequisites",
        "",
        f"Complete Day {spec.day - 1}. Work from a clean virtual environment and use only local synthetic fixtures.",
        "",
        "## Outcomes",
        "",
        "By the end of this lesson, you can:",
        "",
        "- explain the concept before using it\n- run and modify all worked examples\n- test normal, boundary, and failure behavior\n- state scope, evidence, and residual risk\n- complete the numbered exercises",
        "",
        "## The problem",
        "",
        spec.problem,
        "",
        "## Security boundary",
        "",
        "This lesson is educational and bounded. It does not authorize public scanning, credential use, destructive actions, persistence, or processing of private data.",
        "",
        "## Lesson",
        "",
        "### Vocabulary",
        "",
        spec.vocabulary,
        "",
        "## Worked examples",
        "",
    ]
    for i, (title, teaching, code, result) in enumerate(spec.examples, 1):
        lines += [
            f"### Example {i}: {title}",
            "",
            teaching,
            "",
            "```python",
            code,
            "```",
            "",
            "**What to observe:**",
            "",
            result,
            "",
        ]
    lines += [
        "## Execution trace",
        "",
        spec.trace,
        "",
        "## Common mistakes",
        "",
        spec.mistakes,
        "",
        "## Security application",
        "",
        spec.security,
        "",
        "## Exercises",
        "",
        "Complete the numbered questions in [practice/exercises.md](practice/exercises.md) in order. Record the evidence, output, edge case, and limitation requested by each question.",
        "",
        "## Finish line",
        "",
        f"Run `python -m course_days.day{spec.day:03d}`, pass the relevant tests, complete the numbered exercises, and explain one edge case aloud or in writing.",
        "",
        "## Mental model",
        "",
        f"> {spec.mental}",
        "",
        "## Limitations",
        "",
        spec.limits,
        "",
        f"[← Day {spec.day - 1}](../{prev_dir}/{prev_dir}.md) · [Day index](../DAY_INDEX.md) · [Day {spec.day + 1} →](../{next_dir}/{next_dir}.md)",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    for spec in SPECS:
        directory = ROOT / DIRS[spec.day]
        (directory / f"{directory.name}.md").write_text(render(spec), encoding="utf-8")
    print("Authored dense teaching chapters for Days 101–120.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
