"""Author dense teaching chapters for Days 41–60."""

from __future__ import annotations

# ruff: noqa: E501
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRS = {
    40: "day_40_project__host_baseline_auditor",
    41: "day_41_addresses__ports__and_sockets",
    42: "day_42_tcp_clients_and_servers",
    43: "day_43_udp_and_framing",
    44: "day_44_dns_concepts",
    45: "day_45_http_requests_and_responses",
    46: "day_46_tls_and_certificate_validation",
    47: "day_47_packet_capture_fixtures",
    48: "day_48_rate_limits_and_retries",
    49: "day_49_network_baselines",
    50: "day_50_project__local_service_monitor",
    51: "day_51_trust_boundaries_and_threat_models",
    52: "day_52_encoding_and_unicode",
    53: "day_53_hashes_and_integrity",
    54: "day_54_hmac_and_authenticity",
    55: "day_55_secure_randomness",
    56: "day_56_password_verification",
    57: "day_57_symmetric_and_asymmetric_crypto",
    58: "day_58_safe_serialization",
    59: "day_59_secure_errors_and_logging",
    60: "day_60_project__tamper_evident_case_bundle",
    61: "day_61_local_service_architecture",
}


@dataclass(frozen=True)
class Lesson:
    day: int
    title: str
    why: str
    problem: str
    vocabulary: str
    examples: tuple[tuple[str, str, str, str], ...]
    trace: str
    mistakes: str
    security: str
    mental: str
    limits: str


def example(title: str, teaching: str, code: str, result: str):
    return title, teaching, code, result


SPECS = [
    Lesson(
        41,
        "Addresses, Ports, and Sockets",
        "Network programs begin with names and endpoints. A learner must understand what an address identifies, what a port represents, and why a socket operation is not automatically authorized.",
        "Describe a local service endpoint and create a socket object without scanning or connecting to an unknown host.",
        "An IP address identifies an interface in a network context. A port identifies a transport endpoint. A socket is a program object representing communication settings.",
        (
            example(
                "Represent an endpoint",
                "Keep host and port as separate typed values.",
                'from dataclasses import dataclass\n@dataclass(frozen=True)\nclass Endpoint:\n    host: str\n    port: int\n\nprint(Endpoint("127.0.0.1", 8000))',
                "`Endpoint(host='127.0.0.1', port=8000)`",
            ),
            example(
                "Validate a port",
                "Conversion and range policy are separate steps.",
                'def port(value: str) -> int:\n    number = int(value)\n    if not 1 <= number <= 65535:\n        raise ValueError("port outside TCP/UDP range")\n    return number',
                "`port('8000')` returns 8000; 0 and 65536 are rejected.",
            ),
            example(
                "Create a socket",
                "Creating a socket does not send traffic.",
                "import socket\nsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\nprint(sock.family, sock.type)\nsock.close()",
                "The object is IPv4/TCP and is closed without connecting.",
            ),
            example(
                "Use a context manager",
                "Cleanup should happen even when later code fails.",
                "with socket.socket() as sock:\n    sock.settimeout(1.0)\n    print(sock.gettimeout())",
                "`1.0` seconds.",
            ),
            example(
                "State scope",
                "A network operation should carry its authorization boundary.",
                'scope = {"host": "127.0.0.1", "purpose": "course fixture", "remote": False}\nprint(scope)',
                "The scope is local and explicit.",
            ),
        ),
        "The endpoint is validated, the socket is created, options are set, and cleanup happens. No network operation occurs until a connect, bind, send, or receive call is made.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| port as a string everywhere | comparisons behave unexpectedly | convert at the boundary |\n| socket never closed | resources remain open | use `with` |\n| localhost equals harmless | a local service may contain private data | define authorization and fixture |\n| address equals identity | IP data is overinterpreted | record source and confidence |\n| connect in a test | external side effect | use a fake or local controlled service |",
        "Use loopback or a fake socket in tests. Do not enumerate ports or connect to systems not explicitly supplied by the course.",
        "An endpoint is data; a socket is a capability; authorization must exist before the capability is used.",
        "Addresses and ports change, can be spoofed, and do not identify a person or authorize access.",
    ),
    Lesson(
        42,
        "TCP Clients, Servers, and Framing",
        "TCP provides an ordered byte stream, not messages. A security engineer must understand connection lifecycle, partial reads, framing, and timeouts before writing a client or service.",
        "Build a local loopback echo exchange with a length or delimiter rule and a finite timeout.",
        "TCP is connection-oriented. A **stream** has no message boundaries. **Framing** tells the receiver where one message ends. `accept` creates a per-client socket.",
        (
            example(
                "Bind a local server",
                "Binding reserves an endpoint for a local process.",
                'import socket\nserver = socket.socket()\nserver.bind(("127.0.0.1", 0))\nprint(server.getsockname()[1])\nserver.close()',
                "Port zero asks the OS for a temporary local port.",
            ),
            example(
                "Listen and accept",
                "A server creates a listening socket, then accepts a client socket.",
                "server.listen(1)\nclient, address = server.accept()\nclient.close()",
                "`client` represents one connection; this call blocks until a client arrives.",
            ),
            example(
                "Send bytes",
                "Sockets send bytes, so text needs an encoding.",
                'payload = "hello".encode("utf-8")\nprint(payload)',
                "`b'hello'`",
            ),
            example(
                "Frame with a delimiter",
                "A newline can separate small training messages.",
                'buffer = b"one\\ntwo\\n"\nmessages = buffer.split(b"\\n")\nprint(messages[:2])',
                "The first two frames are `one` and `two`.",
            ),
            example(
                "Set a timeout",
                "Blocking network calls need a finite wait.",
                "sock.settimeout(1.0)\nprint(sock.gettimeout())",
                "The call will not wait forever.",
            ),
        ),
        "A TCP server binds and listens, accepts a connection, receives arbitrary-sized chunks, reconstructs frames, responds, and closes. A single `recv` is not guaranteed to return one complete message.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| assume `recv` is one message | partial or combined frames | implement framing |\n| forget close | sockets accumulate | use context managers and `finally` |\n| no timeout | connection hangs | set a finite timeout |\n| bind all interfaces | service is exposed unexpectedly | use loopback for practice |\n| echo untrusted bytes | protocol confusion | define encoding and maximum frame size |",
        "Use only loopback and a disposable port. The exercise must include a maximum frame size and a test for a partial frame; it must not become a remote shell or scanner.",
        "TCP is a stream with a lifecycle and no built-in message boundaries; framing and limits are application responsibilities.",
        "TLS, authentication, access control, and operational hardening are not provided by a bare TCP socket.",
    ),
    Lesson(
        43,
        "UDP and Message Framing",
        "UDP sends independent datagrams without a connection guarantee. It can be useful for bounded local telemetry, but loss, duplication, reordering, and spoofing must be part of the design.",
        "Parse a local datagram fixture and explain why a missing response is not automatically an attack.",
        "A datagram is one UDP packet payload. UDP is connectionless and does not guarantee delivery. A sequence number supports application-level ordering.",
        (
            example(
                "Create a UDP socket",
                "The type distinguishes UDP from TCP.",
                "import socket\nsock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)\nprint(sock.type)\nsock.close()",
                "The socket type is datagram.",
            ),
            example(
                "Encode a datagram",
                "The payload has an explicit byte representation.",
                'message = b"event=1\\n"\nprint(len(message))',
                "The length is known before sending.",
            ),
            example(
                "Add a sequence number",
                "A receiver can detect missing or repeated application messages.",
                'packet = {"sequence": 4, "payload": "heartbeat"}\nprint(packet)',
                "The sequence is metadata, not proof of sender identity.",
            ),
            example(
                "Bound a datagram",
                "Reject oversized data before parsing or storing it.",
                'MAX = 1200\nif len(message) > MAX:\n    raise ValueError("datagram too large")',
                "Oversized training data is rejected.",
            ),
            example(
                "Describe uncertainty",
                "A timeout is a transport result, not a conclusion.",
                'result = {"status": "no_response", "complete": False}\nprint(result)',
                "The report preserves uncertainty.",
            ),
        ),
        "The sender creates a bounded byte payload; the receiver obtains one datagram or a timeout; the application validates framing, sequence, and schema before interpreting it.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| assume delivery | missing data disappears | report loss or timeout |\n| trust source address | spoofing is possible | authenticate at the application layer |\n| accept unlimited payload | memory or parser abuse | cap size |\n| use UDP for secrets | no confidentiality by default | use an appropriate authenticated protocol |\n| call loss malicious | network conditions are ignored | preserve alternative explanations |",
        "Use serialized local fixtures rather than sending traffic. If a live demonstration is used, keep both endpoints on loopback and document cleanup.",
        "UDP provides datagrams, not reliability or identity; the application must state what loss means.",
        "A local UDP test does not represent an internet path, and a packet observation does not prove intent.",
    ),
    Lesson(
        44,
        "DNS Concepts and Safe Resolution",
        "Names are translated into addresses through a resolver path that can vary by cache, configuration, and time. Security tooling should distinguish lookup results from ownership or trust.",
        "Resolve a documentation name or local fixture safely and record the resolver result without probing the returned host.",
        "DNS maps names to records. A resolver performs lookup. A cache stores results for a period. TTL expresses a caching interval.",
        (
            example(
                "Resolve a local name",
                "Use the standard library for a single explicit lookup.",
                'import socket\nprint(socket.gethostbyname("localhost"))',
                "Usually `127.0.0.1` in a local environment.",
            ),
            example(
                "Inspect multiple results",
                "One name can map to multiple addresses.",
                'print(socket.getaddrinfo("localhost", 0, type=socket.SOCK_STREAM))',
                "The result contains address families and endpoints.",
            ),
            example(
                "Preserve the name",
                "The original name is important provenance.",
                'record = {"name": "localhost", "resolved": ["127.0.0.1"], "observed": True}\nprint(record)',
                "The name and result stay together.",
            ),
            example(
                "Bound a lookup",
                "A tool should not treat resolution as a permission to connect.",
                'policy = {"allowed_names": {"localhost"}}\nprint("localhost" in policy["allowed_names"])',
                "Only an explicitly allowed training name passes policy.",
            ),
            example(
                "State time",
                "Results need an observation time because DNS can change.",
                "from datetime import datetime, timezone\nprint(datetime.now(timezone.utc).isoformat())",
                "An aware UTC timestamp.",
            ),
        ),
        "The name is selected, policy checks it, the resolver returns records, and the tool records time and source. No connection follows automatically.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| resolution equals ownership | name is treated as trusted | record it as an observation |\n| connect after lookup | lookup becomes an unapproved action | separate phases |\n| assume one address | load balancing and IPv6 are missed | handle multiple results |\n| cache forever | stale result is treated as current | record time and TTL when available |\n| log private names | internal data leaks | minimize output |",
        "Use `localhost` or documented synthetic names only. Do not enumerate DNS names, perform zone transfers, or connect to resolved endpoints.",
        "DNS is a time-bound naming observation, not identity, authorization, or proof of ownership.",
        "Resolvers, caches, hosts files, and network policy affect results; a Python lookup cannot prove the full DNS path.",
    ),
    Lesson(
        45,
        "HTTP Requests, Responses, and Safe Parsing",
        "HTTP is a text-and-byte protocol used by security tools and applications. Understanding methods, status, headers, bodies, and limits helps a learner inspect a local service without treating requests as harmless by default.",
        "Parse a synthetic HTTP exchange and make a bounded request only to a supplied loopback service.",
        "A request has a method, target, headers, and body. A response has a status, headers, and body. Headers are metadata, not automatically safe input.",
        (
            example(
                "Parse a request line",
                "The method, target, and version are separate fields.",
                'line = "GET /health HTTP/1.1"\nmethod, target, version = line.split()\nprint(method, target, version)',
                "`GET /health HTTP/1.1` as three values.",
            ),
            example(
                "Read a status",
                "Status codes are categories, not complete explanations.",
                "status = 200\nprint(200 <= status < 300)",
                "`True` for a successful class.",
            ),
            example(
                "Build headers",
                "Header names and values need validation and limits.",
                'headers = {"Accept": "application/json", "User-Agent": "training-client"}\nprint(headers)',
                "The request identifies a bounded client.",
            ),
            example(
                "Parse JSON deliberately",
                "A content type does not guarantee valid JSON.",
                'import json\ndata = json.loads(\'{"status": "ok"}\')\nprint(data["status"])',
                "`ok`",
            ),
            example(
                "Limit a body",
                "Never read an unbounded response into memory.",
                'body = b"training response"\nMAX = 4096\nprint(body[:MAX])',
                "The preview is bounded.",
            ),
        ),
        "A parser reads the request line and headers, checks the declared limits, decodes the body according to a documented encoding, and returns a structured result or rejection.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| trust status only | error body is ignored | inspect status, headers, and body policy |\n| follow redirects blindly | target changes | bound and review redirects |\n| no body limit | memory abuse | cap bytes |\n| log authorization header | credential leak | redact sensitive headers |\n| request public targets | unauthorized traffic | use local fixtures or written permission |",
        "Use a loopback server or saved HTTP fixture. Document allowed method, host, path, body limit, timeout, and cleanup.",
        "HTTP is a structured exchange whose metadata and body cross a trust boundary; parse and bound both sides.",
        "HTTP parsing and a successful local request do not prove application security or server identity.",
    ),
    Lesson(
        46,
        "TLS and Certificate Validation",
        "Encryption in transit is useful only when the client validates who it is communicating with. A learner should understand certificates and hostname checks without writing a bypass.",
        "Inspect the standard library’s secure client defaults and explain why disabling certificate verification is not a fix.",
        "TLS provides confidentiality and integrity for a negotiated connection. A certificate binds a public key to an identity under a trust model. Hostname verification checks the requested name.",
        (
            example(
                "Create a default context",
                "The standard client context enables ordinary verification defaults.",
                "import ssl\ncontext = ssl.create_default_context()\nprint(context.check_hostname, context.verify_mode)",
                "Hostname checking is enabled and certificates are required.",
            ),
            example(
                "Name the target",
                "The requested hostname is part of validation.",
                'target = {"hostname": "training.local", "purpose": "loopback demo"}\nprint(target)',
                "The identity expectation is explicit.",
            ),
            example(
                "Reject a mismatch conceptually",
                "A certificate for another name should not be accepted silently.",
                'expected = "training.local"\npresented = "other.local"\nprint(expected == presented)',
                "`False`; the client should fail rather than continue.",
            ),
            example(
                "Separate trust stores",
                "Trust decisions depend on which CA roots the client uses.",
                'trust_policy = {"system_roots": True, "custom_roots": []}\nprint(trust_policy)',
                "The trust source is documented.",
            ),
            example(
                "Do not disable verification",
                "A bypass converts an identity failure into an undetected connection.",
                'safe = {"verify_certificates": True, "verify_hostname": True}\nprint(safe)',
                "Both checks remain enabled.",
            ),
        ),
        "The client chooses a trust store, negotiates TLS, validates the chain and hostname, and only then treats the connection as authenticated for the stated identity.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| `CERT_NONE` in production | identity is not checked | keep verification enabled |\n| trust any hostname | wrong service can impersonate | verify hostname |\n| encryption equals authentication | endpoint identity is assumed | describe the trust model |\n| ignore expiration | stale credentials remain trusted | check validity |\n| print certificate details carelessly | internal names leak | minimize logs |",
        "Use documentation and a local controlled certificate if needed. Do not add a verification bypass or connect to arbitrary public targets.",
        "TLS protects a connection only under an explicit certificate and hostname trust decision.",
        "TLS configuration is complex, trust stores vary, and certificate validation does not authorize actions after connection.",
    ),
    Lesson(
        47,
        "Packet-Capture Fixtures and Layered Parsing",
        "Packet captures are rich evidence, but a beginner can easily mistake a decoded field for complete context. A fixture-first parser makes layers, offsets, and truncation visible.",
        "Parse a saved, synthetic packet summary rather than sniffing a live interface.",
        "A packet is a sequence of bytes. A protocol layer interprets part of it. A capture fixture is saved evidence with collection limits and metadata.",
        (
            example(
                "Represent a frame",
                "A fixture can describe layers without needing live capture.",
                'frame = {"number": 1, "layers": ["ethernet", "ip", "tcp"], "captured": True}\nprint(frame)',
                "The layer list is explicit.",
            ),
            example(
                "Parse a bounded header",
                "Never index bytes without checking length.",
                'data = b"GET /"\nif len(data) < 4:\n    raise ValueError("truncated")\nprint(data[:4])',
                "`b'GET '`",
            ),
            example(
                "Preserve offsets",
                "Offsets let a reviewer locate a field in a fixture.",
                'field = {"name": "payload", "start": 40, "length": 5}\nprint(field)',
                "The evidence location is retained.",
            ),
            example(
                "Mark truncation",
                "A capture may omit bytes by design.",
                'capture = {"captured_bytes": 64, "original_bytes": 120, "truncated": True}\nprint(capture)',
                "The result cannot be interpreted as a complete payload.",
            ),
            example(
                "Separate observation",
                "A decoded flag is not automatically malicious.",
                'finding = {"flag": "SYN", "label": "observed", "confidence": "low"}\nprint(finding)',
                "The neutral label preserves uncertainty.",
            ),
        ),
        "The parser validates fixture length, decodes one layer, records offsets and truncation, and returns observations with provenance rather than a story about an attacker.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| sniff live interface | scope and privacy fail | use saved fixtures |\n| assume full payload | truncated data is overread | check lengths and flags |\n| decode without layer | fields are misaligned | parse in order |\n| packet equals event | context is missing | record only observation |\n| store sensitive capture | evidence leaks | use synthetic fixtures and minimize |",
        "Use only supplied packet summaries or synthetic byte strings. Do not capture other people’s traffic or build a live interception tool.",
        "A packet parser transforms bounded bytes into layered observations with offsets and completeness metadata.",
        "A capture can be truncated, malformed, encrypted, spoofed, or detached from application context.",
    ),
    Lesson(
        48,
        "Rate Limits, Retries, and Backoff",
        "Retries can recover from transient local failures or amplify load. A security engineer must distinguish a bounded retry policy from a loop that turns one failure into an outage.",
        "Implement a local retry helper that stops after a finite number of attempts and reports the final state.",
        "A **rate limit** bounds operations per time. A **retry** repeats a failed operation. **Backoff** spaces attempts. **Jitter** varies wait time to avoid synchronized retries.",
        (
            example(
                "Bound attempts",
                "The attempt count is part of the contract.",
                "def attempts(max_attempts=3):\n    for number in range(1, max_attempts + 1):\n        yield number\nprint(list(attempts()))",
                "`[1, 2, 3]`",
            ),
            example(
                "Retry a local function",
                "Only retry an explicitly transient error.",
                "def retry(function, attempts=3):\n    for number in range(attempts):\n        try:\n            return function()\n        except TimeoutError:\n            if number == attempts - 1:\n                raise",
                "The final timeout is not hidden.",
            ),
            example(
                "Calculate capped backoff",
                "A cap prevents wait time from growing without bound.",
                "def delay(attempt, cap=8):\n    return min(cap, 2 ** attempt)\nprint([delay(n) for n in range(4)])",
                "`[1, 2, 4, 8]`",
            ),
            example(
                "Respect a budget",
                "Retries share a total time budget.",
                'budget = {"attempts": 3, "seconds": 10}\nprint(budget)',
                "The caller can stop when either budget is exhausted.",
            ),
            example(
                "Report partial work",
                "No response after retries is an explicit outcome.",
                'print({"status": "unavailable_after_retries", "complete": False})',
                "The report does not claim the target was down or malicious.",
            ),
        ),
        "The operation checks whether the error is retryable, increments a finite attempt count, waits within a cap, and returns success or an incomplete result with the reason.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| retry every exception | bugs repeat | classify transient failures |\n| no cap | delays or attempts grow | cap count and time |\n| synchronized clients | load spike | add jitter where appropriate |\n| retry unsafe action | duplicate side effects | require idempotency |\n| no status | failure looks empty | report attempts and final state |",
        "Demonstrate with a local function that fails predictably. Do not use retries to increase request volume against any external service.",
        "Reliability controls are bounded decisions about when to stop; a retry is not a permission to keep trying.",
        "Backoff tuning depends on the service and workload. It cannot repair a broken authorization or protocol design.",
    ),
    Lesson(
        49,
        "Network Baselines and Change Detection",
        "A baseline can make local service behavior easier to understand. It can also create false alarms when normal timing, DNS, or deployment changes are treated as threats.",
        "Compare two synthetic connection summaries and classify the difference as observed drift requiring review.",
        "A baseline is a reference observation. A feature is a measured property. Drift is a difference. A false positive is an alert for benign change.",
        (
            example(
                "Create features",
                "A baseline compares normalized features rather than raw log order.",
                'baseline = {"port": 8000, "protocol": "tcp", "latency_ms": 20}\nprint(baseline)',
                "The feature set is explicit.",
            ),
            example(
                "Normalize a measurement",
                "Rounding can reduce noise, but should be documented.",
                "latencies = [19, 21, 20]\nprint(round(sum(latencies) / len(latencies), 1))",
                "`20.0` milliseconds.",
            ),
            example(
                "Compare fields",
                "Each changed field gets its own finding.",
                'before = {"port": 8000}\nafter = {"port": 8080}\nprint({"field": "port", "before": before["port"], "after": after["port"]})',
                "The difference is reviewable.",
            ),
            example(
                "Add context",
                "A deployment window can explain benign drift.",
                'context = {"change_window": True, "owner_note": "training update"}\nprint(context)',
                "Context reduces overclaiming.",
            ),
            example(
                "State confidence",
                "A baseline finding should be a lead, not a verdict.",
                'print({"status": "needs_review", "confidence": "low"})',
                "The label is neutral.",
            ),
        ),
        "The collector normalizes local observations, compares them to a dated baseline, attaches context, and reports changed or missing features without deciding intent.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| baseline never updated | normal change alerts forever | version and review it |\n| raw timing comparison | noise creates alerts | define normalization |\n| drift equals intrusion | evidence is overinterpreted | use needs-review |\n| no collection scope | monitoring expands silently | list approved features |\n| ignore missing data | blind spot becomes normal | report not observed |",
        "Use synthetic connection summaries and local fixtures only. Document the baseline date, feature definitions, review owner, and residual false-positive risk.",
        "A baseline highlights change relative to a reference; it does not explain why the change occurred.",
        "Baselines are sensitive to deployment, clock, configuration, and measurement quality.",
    ),
    Lesson(
        50,
        "Project: Local Service Monitor",
        "This project combines sockets, HTTP parsing, TLS reasoning, timeouts, retries, and baselines into a local monitor that reports bounded observations instead of acting like an internet scanner.",
        "Build a monitor for one supplied loopback service with explicit timeout, retry, endpoint, and cleanup rules.",
        "A monitor observes availability and response properties. It does not prove health, ownership, or security. An **SLO** is a documented reliability target.",
        (
            example(
                "Define scope",
                "The monitor should carry its one approved endpoint.",
                'scope = {"host": "127.0.0.1", "port": 8000, "path": "/health", "max_attempts": 2}\nprint(scope)',
                "The endpoint and budgets are visible.",
            ),
            example(
                "Record a check",
                "A result should separate transport from application outcome.",
                'result = {"connected": True, "status": 200, "latency_ms": 12}\nprint(result)',
                "The fields describe what was observed.",
            ),
            example(
                "Handle timeout",
                "Timeout is incomplete evidence.",
                'print({"connected": False, "status": None, "reason": "timeout", "complete": False})',
                "The report avoids a false healthy/unhealthy claim.",
            ),
            example(
                "Compare baseline",
                "A threshold is a review policy, not proof of compromise.",
                'baseline_ms = 20\nobserved_ms = 45\nprint({"latency_changed": observed_ms > baseline_ms * 2})',
                "The difference is a local review signal.",
            ),
            example(
                "Reset cleanly",
                "A project must say how to stop and remove generated reports.",
                'cleanup = ["stop local server", "delete training-output"]\nprint(cleanup)',
                "The reset plan is explicit.",
            ),
        ),
        "The monitor validates scope, performs a finite local check, handles timeout/retry, parses a bounded response, compares safe features, and writes a report with completeness and limitations.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| scan a range | project becomes reconnaissance | one supplied endpoint only |\n| no timeout | monitor hangs | finite timeout |\n| retry forever | load amplification | finite retry budget |\n| call latency attack | timing is ambiguous | report as observation |\n| no cleanup | local service persists | document reset |",
        "The checkpoint must be loopback-only, read-only, finite, synthetic, and tested with a fake service or fixture. No public host, credential, or scanning feature is allowed.",
        "A monitor is a bounded observation pipeline with a documented endpoint and uncertainty-aware report.",
        "A local monitor cannot establish availability for all users, application correctness, or security posture.",
    ),
    Lesson(
        51,
        "Trust Boundaries and Threat Models for Crypto",
        "Cryptography is not a decoration around data. Before choosing a primitive, identify what must remain secret, what must be tamper-evident, who holds keys, and what happens when verification fails.",
        "Threat-model a local case bundle before selecting hashes, HMAC, encryption, or signatures.",
        "A trust boundary separates assumptions. Confidentiality hides content. Integrity detects change. Authenticity ties data to a key or signer. A threat model records assets and adversaries.",
        (
            example(
                "Name properties",
                "Different goals require different controls.",
                'needs = {"secret": "confidentiality", "changed": "integrity", "sender": "authenticity"}\nprint(needs)',
                "The requirements are not collapsed into one word: secure.",
            ),
            example(
                "Model a key holder",
                "Key location and access matter as much as the algorithm.",
                'key_plan = {"holder": "local test process", "storage": "not in source", "rotation": "documented"}\nprint(key_plan)',
                "The trust assumption is visible.",
            ),
            example(
                "Define failure",
                "Verification failure needs a safe default.",
                'failure_policy = {"on_bad_tag": "reject", "continue": False}\nprint(failure_policy)',
                "Bad data is not processed.",
            ),
            example(
                "State threat",
                "A threat names an action and asset.",
                'threat = {"action": "modify_case_bundle", "asset": "integrity", "control": "verify_mac_before_parse"}\nprint(threat)',
                "The control maps to the threat.",
            ),
            example(
                "Record residual risk",
                "No primitive solves key compromise or wrong trust decisions.",
                'print("residual: compromised key or wrong key selection defeats verification")',
                "The limitation remains visible.",
            ),
        ),
        "The model starts with properties and key holders, chooses a failure policy, maps threat to control, and states what remains. Only then should code select a primitive.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| say “encrypted” | property is unclear | name confidentiality/integrity/authenticity |\n| hard-code key | secret enters source | externalize key handling |\n| parse before verify | attacker controls parser input | verify before trusting content |\n| bad tag becomes warning | tampered data continues | reject safely |\n| algorithm first | requirements are missed | threat-model first |",
        "Use only training keys and synthetic bundles. Never use a university, employer, or personal key in exercises.",
        "Cryptography implements a property under key and trust assumptions; the assumptions are part of the security design.",
        "A correct primitive with a compromised key, wrong mode, or bad lifecycle can fail completely.",
    ),
    Lesson(
        52,
        "Encoding, Unicode, and Canonical Bytes",
        "Cryptographic functions operate on bytes, while learners usually see text. Inconsistent encoding or normalization can make two parties hash different data that looks identical.",
        "Convert synthetic text into agreed bytes, preserve the original representation, and explain where normalization belongs.",
        "Text is Unicode. Bytes are numeric data. Encoding maps text to bytes. Canonicalization chooses one representation for comparison or signing.",
        (
            example(
                "Encode UTF-8",
                "The encoding must be explicit at the boundary.",
                'text = "café"\ndata = text.encode("utf-8")\nprint(data)',
                "UTF-8 bytes are displayed.",
            ),
            example(
                "Decode with the same rule",
                "The inverse operation requires the compatible encoding.",
                'print(data.decode("utf-8"))',
                "`café`",
            ),
            example(
                "Hash bytes, not a vague string",
                "The digest input must be reproducible.",
                "import hashlib\nprint(hashlib.sha256(data).hexdigest()[:12])",
                "A stable prefix for the exact bytes.",
            ),
            example(
                "Normalize deliberately",
                "Unicode normalization changes bytes and must be part of the protocol.",
                'import unicodedata\ncanonical = unicodedata.normalize("NFC", text)\nprint(canonical)',
                "The canonical text is explicit.",
            ),
            example(
                "Preserve raw and canonical",
                "Evidence needs provenance even when comparison uses a canonical form.",
                'record = {"raw": text, "canonical": canonical, "encoding": "utf-8"}\nprint(record)',
                "Both representations remain available.",
            ),
        ),
        "The protocol chooses text normalization and encoding, produces bytes, applies the cryptographic operation to those bytes, and records the choices so another implementation can reproduce them.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| hash implicit encoding | digests differ by platform | encode explicitly |\n| normalize without record | original evidence changes | preserve raw and rule |\n| decode arbitrary bytes | errors or replacement characters | define error policy |\n| compare display text | visually similar data differs | compare agreed canonical bytes |\n| treat bytes as secret | representation is mistaken for confidentiality | apply access controls |",
        "Use synthetic strings including non-ASCII characters and test round trips. Do not include personal names or private files.",
        "Cryptography sees bytes; secure protocols must specify how human-facing text becomes those bytes.",
        "Canonicalization can be lossy and Unicode security is complex; protocol designers must define exact rules.",
    ),
    Lesson(
        53,
        "Hashes and Integrity",
        "A cryptographic hash is a compact fingerprint of bytes. It can detect accidental or unauthorized change only when the expected digest comes from a trusted comparison point.",
        "Hash a local fixture, change a copy, and show that the digest changes without calling the digest proof of authorship.",
        "A hash is a one-way digest. Integrity is the property of detecting change. A collision is two inputs with the same digest; secure hashes make finding one impractical under assumptions.",
        (
            example(
                "Hash a value",
                "The same bytes produce the same digest.",
                'import hashlib\nprint(hashlib.sha256(b"training").hexdigest())',
                "A repeatable hexadecimal digest.",
            ),
            example(
                "Compare bytes",
                "The comparison must be exact and ideally constant-time where relevant.",
                'left = hashlib.sha256(b"a").digest()\nright = hashlib.sha256(b"a").digest()\nprint(left == right)',
                "`True`",
            ),
            example(
                "Change one byte",
                "Small input changes produce a different digest.",
                'one = hashlib.sha256(b"training").hexdigest()\ntwo = hashlib.sha256(b"Training").hexdigest()\nprint(one == two)',
                "`False`",
            ),
            example(
                "Hash a file in chunks",
                "Chunking avoids loading a large local fixture at once.",
                'digest = hashlib.sha256()\nfor chunk in [b"part-1", b"part-2"]:\n    digest.update(chunk)\nprint(digest.hexdigest()[:12])',
                "The chunked digest is deterministic.",
            ),
            example(
                "State the trust point",
                "A digest is useful only when the expected digest is trusted.",
                'evidence = {"sha256": "recorded-value", "source": "reviewed-baseline"}\nprint(evidence)',
                "The baseline provenance is part of the evidence.",
            ),
        ),
        "The bytes are fed to the hash in order; the digest is compared to a trusted baseline; a mismatch becomes an integrity finding, not an identity claim.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| hash equals encryption | digest is treated as secret | explain one-way fingerprint |\n| expected digest untrusted | attacker can replace both files | protect the baseline |\n| hash text implicitly | reproducibility fails | specify encoding |\n| use weak legacy hash | collision risks are higher | choose a current approved hash |\n| digest equals authorship | source is overclaimed | separate integrity and authenticity |",
        "Hash only synthetic files and copies. Store the expected digest beside an explanation of how it was obtained; do not treat a course digest as proof of a real file’s origin.",
        "A hash answers whether bytes match a trusted reference; it does not answer who created them.",
        "Hash security depends on the algorithm, input handling, baseline protection, and threat model.",
    ),
    Lesson(
        54,
        "HMAC and Message Authenticity",
        "A keyed message authentication code adds a secret key to integrity checking. It can show that a verifier with the same key accepts a message, but it does not provide non-repudiation and depends on key protection.",
        "Authenticate a synthetic record with an HMAC, verify it before parsing, and reject a changed message.",
        "HMAC is a keyed integrity/authenticity construction. A tag is the resulting authenticator. Constant-time comparison reduces timing leakage in comparisons.",
        (
            example(
                "Create a tag",
                "The same key and bytes produce the same tag.",
                'import hmac, hashlib\nkey = b"training-key"\nmessage = b"case=54"\ntag = hmac.new(key, message, hashlib.sha256).hexdigest()\nprint(tag[:12])',
                "A deterministic tag prefix.",
            ),
            example(
                "Verify with compare_digest",
                "Do not use ordinary early-exit comparison for a secret tag.",
                "expected = hmac.new(key, message, hashlib.sha256).hexdigest()\nprint(hmac.compare_digest(tag, expected))",
                "`True`",
            ),
            example(
                "Detect tampering",
                "A changed message produces a different tag.",
                'changed = b"case=55"\nactual = hmac.new(key, changed, hashlib.sha256).hexdigest()\nprint(hmac.compare_digest(tag, actual))',
                "`False`",
            ),
            example(
                "Verify before parse",
                "Do not let unverified bytes control a parser or action.",
                'if not hmac.compare_digest(tag, expected):\n    raise ValueError("authentication failed")\nrecord = message.decode("utf-8")',
                "Only an authenticated message is decoded.",
            ),
            example(
                "Name key scope",
                "A key should have an owner and purpose.",
                'key_policy = {"purpose": "training bundle", "holder": "test process", "rotation": "reset each run"}\nprint(key_policy)',
                "The key lifecycle is documented.",
            ),
        ),
        "The sender computes a tag over exact bytes; the receiver recomputes it with the expected key, compares safely, and only then parses or acts on the message.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| compare with `==` | timing behavior is less deliberate | use `compare_digest` |\n| verify after parse | attacker controls parser input | verify first |\n| reuse key everywhere | compromise spreads | define key scope and rotation |\n| expose key in logs | authenticity is lost | minimize and protect keys |\n| call HMAC non-repudiation | shared key cannot identify one signer | state the property accurately |",
        "Use a fake key stored in the test fixture or generated per run. Never paste a real credential or send HMAC material to an external service.",
        "HMAC authenticates bytes to parties that share a protected key; verification must precede interpretation.",
        "HMAC does not solve key distribution, compromise, replay, or non-repudiation.",
    ),
    Lesson(
        55,
        "Secure Randomness and Token Design",
        "Security tokens, salts, nonces, and identifiers require unpredictable values. Ordinary pseudo-random helpers are useful for games and simulations but are not interchangeable with a cryptographic random source.",
        "Generate a short-lived training token, encode it safely, and explain its purpose and lifecycle.",
        "Entropy measures uncertainty. A nonce is intended for one use. A salt is a public random value mixed into password derivation. A token is a bearer value whose secrecy matters.",
        (
            example(
                "Generate bytes",
                "`secrets` is designed for security-sensitive randomness.",
                "import secrets\nvalue = secrets.token_bytes(16)\nprint(len(value))",
                "`16` bytes, without printing the secret.",
            ),
            example(
                "Encode for a URL",
                "Text transport needs a safe representation.",
                "token = secrets.token_urlsafe(16)\nprint(len(token))",
                "A URL-safe token string length is visible, not its value.",
            ),
            example(
                "Use a nonce once",
                "The protocol should record use rather than reuse blindly.",
                "nonce = secrets.token_bytes(12)\nused = {nonce}\nprint(nonce in used)",
                "`True` after recording it.",
            ),
            example(
                "Compare a token safely",
                "A token check should not reveal the expected value.",
                'import hmac\nprovided = "training"\nexpected = "training"\nprint(hmac.compare_digest(provided, expected))',
                "`True` without printing a real secret.",
            ),
            example(
                "Set expiry",
                "Randomness does not replace lifecycle policy.",
                'token_record = {"created": "now", "expires": "soon", "purpose": "training"}\nprint(token_record)',
                "The token has purpose and expiry metadata.",
            ),
        ),
        "The secure generator creates unpredictable bytes, the protocol encodes them, records purpose and lifecycle without storing the secret in logs, and verification compares supplied material safely.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| use `random` for tokens | values may be predictable | use `secrets` |\n| print token | bearer secret leaks | log presence or a safe identifier |\n| reuse nonce | protocol assumptions fail | enforce uniqueness per key/context |\n| no expiry | leaked token remains useful | set lifetime and revoke |\n| low entropy | guessing becomes easier | choose adequate bytes for the threat model |",
        "Generate only disposable training tokens and delete them after the exercise. Never use a course token for a real account or service.",
        "Secure randomness supplies unpredictable values; lifecycle and access policy decide whether those values remain useful to an attacker.",
        "No random generator fixes a leaked token, weak authentication, replay, or poor key management.",
    ),
    Lesson(
        56,
        "Password Verification and Slow Derivation",
        "Passwords are human-chosen and often guessable. Systems should store a verifier derived with an approved password-hashing scheme, not the password or a fast raw hash.",
        "Compare a training password against a stored verifier while keeping the password out of source, logs, and output.",
        "A password hash uses a salt and work factor. A salt prevents identical passwords from sharing a digest. A verifier lets the system check a candidate without storing the password.",
        (
            example(
                "Use a salt conceptually",
                "The salt is public metadata but changes the derived output.",
                'salt = b"training-salt"\npassword = b"example"\nprint(len(salt), len(password))',
                "The values have different roles.",
            ),
            example(
                "Do not use a raw SHA",
                "A fast general hash is not a password verifier.",
                'import hashlib\nprint(hashlib.sha256(b"example").hexdigest()[:12])',
                "This digest is shown only to explain why the wrong primitive is tempting.",
            ),
            example(
                "Use a standard password library",
                "Approved libraries encode salt and cost decisions.",
                '# Pseudocode shape: use the selected library’s documented API.\nverifier = {"algorithm": "approved-password-kdf", "cost": "reviewed"}\nprint(verifier)',
                "The implementation choice is documented rather than improvised.",
            ),
            example(
                "Compare without logging",
                "The candidate should exist only for the verification call.",
                'candidate = "input-from-user"\nprint({"candidate_received": bool(candidate)})',
                "Only presence is reported.",
            ),
            example(
                "Handle failure equally",
                "A failed verification should not reveal which account detail was wrong.",
                'print({"authenticated": False, "reason": "generic"})',
                "The response avoids account enumeration.",
            ),
        ),
        "The system receives a candidate, applies the stored verifier’s salt and cost, compares the derived result, and returns a generic outcome. The password never enters a report or source file.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| store plaintext | one leak exposes every password | store a verifier |\n| use raw SHA | guessing is too cheap | use an approved password KDF |\n| fixed salt | identical passwords correlate | use a unique salt per password |\n| log candidates | credentials leak | never log password material |\n| detailed login errors | account enumeration | use a generic failure response |",
        "Use only a fictional training password and a standard library or documented course dependency. Do not implement a password cracker or test against real accounts.",
        "Password verification is a deliberately expensive comparison with protected lifecycle, not a reversible encryption operation.",
        "Work factors age, breaches happen, and authentication needs rate limits, MFA, recovery, and monitoring in addition to password storage.",
    ),
    Lesson(
        57,
        "Symmetric and Asymmetric Cryptography",
        "Encryption protects confidentiality under a key model. Symmetric systems use a shared secret; asymmetric systems use a public/private pair. Choosing one requires knowing who must encrypt, decrypt, sign, or verify.",
        "Map security requirements to a key model and use library-level pseudocode without inventing cryptography.",
        "Symmetric encryption uses one secret key for both directions. Asymmetric cryptography uses a public key and private key. A signature proves possession of a private key under a verification model.",
        (
            example(
                "Map the key roles",
                "Start with who needs which operation.",
                'roles = {"encrypt_to_recipient": "recipient public key", "decrypt": "recipient private key", "sign": "sender private key", "verify": "sender public key"}\nprint(roles)',
                "The roles are explicit.",
            ),
            example(
                "Symmetric key scope",
                "A shared key requires secure distribution to every participant.",
                'plan = {"key": "shared secret", "holders": ["sender", "receiver"], "purpose": "training bundle"}\nprint(plan)',
                "The distribution assumption is visible.",
            ),
            example(
                "Public versus private",
                "A public key can be distributed; the private key must remain controlled.",
                'keys = {"public": "shareable identifier", "private": "protected secret"}\nprint(keys)',
                "The example never contains real key material.",
            ),
            example(
                "Authenticated encryption",
                "Confidentiality without integrity is incomplete for many messages.",
                'requirements = ["confidentiality", "integrity", "nonce uniqueness"]\nprint(requirements)',
                "The required properties are listed before implementation.",
            ),
            example(
                "Reject homemade crypto",
                "Use a reviewed library and documented construction.",
                'decision = {"implementation": "approved library", "custom_cipher": False}\nprint(decision)',
                "The project avoids inventing primitives.",
            ),
        ),
        "The design identifies parties and properties, chooses key roles, selects an approved construction, verifies before parsing, and documents key storage, rotation, and failure behavior.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| encryption equals authenticity | sender is assumed | add authentication/signature model |\n| public key is secret | distribution becomes impossible | protect private key |\n| reuse nonce | construction assumptions break | follow library protocol |\n| roll own cipher | subtle flaws | use reviewed libraries |\n| key in source | repository leak compromises data | externalize key management |",
        "Keep this lesson design-level and use training libraries only. Do not encrypt personal records, build a covert channel, or exchange keys with an external system.",
        "Cryptographic design begins with parties, properties, and key roles; the primitive is only one part of the system.",
        "Real cryptographic deployments require expert review, key management, algorithm agility, side-channel analysis, and operational controls.",
    ),
    Lesson(
        58,
        "Safe Serialization and Deserialization",
        "Serialization turns objects into data for storage or transport. Some formats are data-only; others can execute behavior when loaded. Security code must choose a format and validate its schema.",
        "Serialize a synthetic case record with JSON and reject unexpected fields before it reaches policy.",
        "Serialization encodes an object. Deserialization reconstructs data. A schema defines allowed fields and types. A data-only format does not execute code by itself.",
        (
            example(
                "Serialize JSON",
                "JSON keeps the example data-oriented.",
                'import json\nrecord = {"case_id": "training-058", "severity": 3}\ntext = json.dumps(record, sort_keys=True)\nprint(text)',
                "A deterministic JSON string.",
            ),
            example(
                "Parse JSON",
                "Parsing creates ordinary Python values that still require validation.",
                'loaded = json.loads(text)\nprint(type(loaded).__name__, loaded["severity"])',
                "A dictionary and integer.",
            ),
            example(
                "Allow only fields",
                "A schema boundary prevents unexpected data from silently entering policy.",
                'allowed = {"case_id", "severity"}\nprint(set(loaded) <= allowed)',
                "`True` for the example.",
            ),
            example(
                "Reject unsafe shapes",
                "A list where a dictionary is expected should fail explicitly.",
                'if not isinstance(loaded, dict):\n    raise ValueError("record must be an object")',
                "The policy rejects the wrong shape.",
            ),
            example(
                "Avoid executable loaders",
                "Do not load untrusted Python object formats in a security boundary.",
                'policy = {"accepted": ["json"], "rejected": ["executable-object-format"]}\nprint(policy)',
                "The format decision is documented.",
            ),
        ),
        "The loader parses data into primitive values, checks top-level type, allowed keys, field types, sizes, and required fields, then constructs the internal model.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| load executable objects | untrusted data can run behavior | use data-only format |\n| trust JSON shape | malformed data reaches code | validate schema |\n| accept unlimited nesting | parser resource abuse | bound depth and size |\n| serialize secrets | reports leak material | minimize fields |\n| ignore version | format drift breaks tools | version the schema |",
        "Use only JSON fixtures under the repository. Add tests for unknown keys, oversized strings, wrong types, missing fields, and malformed JSON.",
        "Serialization is a data boundary; choose a non-executable format and validate before constructing trusted internal objects.",
        "JSON itself does not solve authorization, secrets, resource limits, or business-logic validation.",
    ),
    Lesson(
        59,
        "Secure Errors and Logging",
        "Crypto and network failures are sensitive. An error should help an operator recover without revealing keys, passwords, raw tokens, internal paths, or attacker-controlled formatting.",
        "Design error categories and structured logs for a local case bundle without exposing secret material.",
        "An error category groups a failure for a caller. A safe message is actionable but minimized. A correlation identifier links events without copying sensitive data.",
        (
            example(
                "Define safe categories",
                "Categories help callers choose behavior.",
                'categories = {"input": "reject", "timeout": "retry-or-stop", "integrity": "stop", "bug": "escalate"}\nprint(categories)',
                "The policy differs by failure.",
            ),
            example(
                "Redact fields",
                "Redaction happens on structured data before formatting.",
                'safe = {"event": "decrypt_failed", "case_id": "training", "key": "[REDACTED]"}\nprint(safe)',
                "The key is not output.",
            ),
            example(
                "Use correlation",
                "A short case id helps search without exposing a raw payload.",
                'record = {"case_id": "training-059", "error": "integrity_check_failed"}\nprint(record)',
                "The record is searchable and minimal.",
            ),
            example(
                "Avoid exception echo",
                "User-controlled text should not become an unescaped log record.",
                'message = "bad\\nvalue".replace("\\n", "\\\\n")\nprint(message)',
                "The line break is visible as text.",
            ),
            example(
                "Separate user message and debug detail",
                "Different audiences need different fields and access.",
                'public = {"status": "rejected", "reason": "invalid record"}\ndebug = {"internal": "training-only detail"}\nprint(public)',
                "The safe output is intentionally smaller.",
            ),
        ),
        "The boundary catches a known category, creates a minimal safe record, attaches a correlation id, and stores restricted detail separately or omits it.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| log key or plaintext | cryptographic material leaks | redact and minimize |\n| echo attacker text | fake records or injection | encode control characters |\n| same message for all | operators cannot act | categorize failures |\n| detail in exception | traceback leaks paths and values | safe public error plus restricted detail |\n| retry integrity failure | tampered data is processed | stop and review |",
        "Use synthetic errors and fake keys only. Tests must assert that key-like strings, passwords, and raw payloads cannot appear in safe logs.",
        "Secure error handling preserves enough information to act while withholding material that increases harm.",
        "Logging policy depends on retention, access, correlation, and incident procedures outside the Python function.",
    ),
    Lesson(
        60,
        "Project: Tamper-Evident Case Bundle",
        "This project combines encoding, hashes, HMAC, serialization, error policy, and provenance into a local case bundle that can detect modification without pretending to be legal chain of custody.",
        "Build a bundle of synthetic JSON records with canonical bytes, a manifest digest, an HMAC tag, and a verification command.",
        "A manifest lists bundle members. Canonical bytes make hashing reproducible. Tamper-evident means change is detectable under a protected verification key.",
        (
            example(
                "Create canonical JSON",
                "Stable key ordering and encoding make bytes reproducible.",
                'import json\nrecord = {"severity": 7, "case_id": "training-060"}\ncanonical = json.dumps(record, sort_keys=True, separators=(",", ":")).encode("utf-8")\nprint(canonical)',
                "The canonical bytes have no incidental spaces.",
            ),
            example(
                "Digest a member",
                "The manifest can store a digest for each member.",
                "import hashlib\nmember_hash = hashlib.sha256(canonical).hexdigest()\nprint(member_hash[:12])",
                "A stable digest prefix.",
            ),
            example(
                "Build a manifest",
                "The manifest names scope and members.",
                'manifest = {"version": 1, "members": {"record.json": member_hash}, "scope": "training-only"}\nprint(manifest)',
                "The bundle structure is visible.",
            ),
            example(
                "Authenticate the manifest",
                "HMAC protects the manifest under the training key.",
                'import hmac\nkey = b"training-bundle-key"\nmanifest_bytes = json.dumps(manifest, sort_keys=True).encode()\ntag = hmac.new(key, manifest_bytes, hashlib.sha256).hexdigest()\nprint(tag[:12])',
                "The tag is stored separately from the secret key.",
            ),
            example(
                "Verify before reading",
                "Verification must precede interpreting members as trusted.",
                "ok = hmac.compare_digest(tag, hmac.new(key, manifest_bytes, hashlib.sha256).hexdigest())\nprint(ok)",
                "`True` for the unchanged training manifest.",
            ),
        ),
        "The project canonicalizes data, hashes each member, authenticates the manifest, writes a bounded bundle, and verifies the tag and member digests before reporting a result.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| hash noncanonical JSON | equivalent data hashes differently | define canonical bytes |\n| store key with bundle | attacker gets verification key | separate key lifecycle |\n| parse before verify | tampered content controls code | verify manifest first |\n| claim legal evidence | technical check is overclaimed | state training limitations |\n| no version | future parser guesses | version the bundle schema |",
        "The bundle is local, synthetic, resettable, and verified with a disposable training key. The README must document exact bytes, key handling, tamper test, cleanup, and limitations.",
        "A tamper-evident bundle makes changes detectable under a defined byte and key policy; it does not make data true.",
        "This is not a production evidence system, secure archival service, or legal chain-of-custody implementation.",
    ),
]


def render(lesson: Lesson) -> str:
    prev_dir = DIRS[lesson.day - 1]
    next_dir = DIRS[lesson.day + 1]
    lines = [
        f"# Day {lesson.day}: {lesson.title}",
        "",
        f"[← Day {lesson.day - 1}](../{prev_dir}/{prev_dir}.md) · [Day index](../DAY_INDEX.md) · [Day {lesson.day + 1} →](../{next_dir}/{next_dir}.md)",
        "",
        "## Table of Contents",
        "",
        "- [Why this lesson exists](#why-this-lesson-exists)",
        "- [Prerequisites](#prerequisites)",
        "- [Outcomes](#outcomes)",
        "- [The problem](#the-problem)",
        "- [Security boundary](#security-boundary)",
        "- [Lesson](#lesson)",
        "- [Vocabulary](#vocabulary)",
        "- [Worked examples](#worked-examples)",
        "- [Execution trace](#execution-trace)",
        "- [Common mistakes](#common-mistakes)",
        "- [Security application](#security-application)",
        "- [Exercises](#exercises)",
        "- [Finish line](#finish-line)",
        "",
        "## Why this lesson exists",
        "",
        lesson.why,
        "",
        "## Prerequisites",
        "",
        f"Complete Day {lesson.day - 1}. Run the repository checks and use only the local fixtures and explicitly authorized loopback services.",
        "",
        "## Outcomes",
        "",
        "By the end of this lesson, you can:",
        "",
        "- explain the protocol or security property in plain language\n- run and modify every worked example\n- test a normal, boundary, and failure case\n- identify the trust boundary and residual risk\n- connect the concept to the numbered cybersecurity exercises",
        "",
        "## The problem",
        "",
        lesson.problem,
        "",
        "## Security boundary",
        "",
        "Use synthetic data, local fixtures, and loopback-only demonstrations. This lesson does not authorize scanning, interception, credential use, remote command execution, or changes to systems you do not own.",
        "",
        "## Lesson",
        "",
        "### Vocabulary",
        "",
        lesson.vocabulary,
        "",
        "## Worked examples",
        "",
    ]
    for number, (title, teaching, code, result) in enumerate(lesson.examples, 1):
        lines += [
            f"### Example {number}: {title}",
            "",
            teaching,
            "",
            "```python",
            code,
            "```",
            "",
            "**What to observe:**",
            "",
            result,
            "",
        ]
    lines += [
        "## Execution trace",
        "",
        lesson.trace,
        "",
        "## Common mistakes",
        "",
        lesson.mistakes,
        "",
        "## Security application",
        "",
        lesson.security,
        "",
        "## Exercises",
        "",
        "Complete the numbered questions in [practice/exercises.md](practice/exercises.md) in order. Run the requested local command, inspect its output, and record the limitation asked for by the exercise.",
        "",
        "## Finish line",
        "",
        f"Run `python -m course_days.day{lesson.day:03d}`, pass the relevant tests, complete the numbered exercises, and explain one edge case aloud or in writing.",
        "",
        "## Mental model",
        "",
        f"> {lesson.mental}",
        "",
        "## Limitations",
        "",
        lesson.limits,
        "",
        f"[← Day {lesson.day - 1}](../{prev_dir}/{prev_dir}.md) · [Day index](../DAY_INDEX.md) · [Day {lesson.day + 1} →](../{next_dir}/{next_dir}.md)",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    for lesson in SPECS:
        directory = ROOT / DIRS[lesson.day]
        (directory / f"{directory.name}.md").write_text(
            render(lesson), encoding="utf-8"
        )
    print("Authored dense teaching chapters for Days 41–60.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
