"""Author dense teaching chapters for Days 81–100."""

from __future__ import annotations

# ruff: noqa: E501
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRS = {
    80: "day_80_project__mini_detection_pipeline",
    81: "day_81_response_lifecycle",
    82: "day_82_evidence_integrity",
    83: "day_83_filesystem_timelines",
    84: "day_84_sqlite_artifacts",
    85: "day_85_browser_and_document_artifacts",
    86: "day_86_email_and_phishing_fixtures",
    87: "day_87_network_evidence",
    88: "day_88_volatile_evidence_concepts",
    89: "day_89_incident_reporting",
    90: "day_90_project__synthetic_breach_investigation",
    91: "day_91_rules_of_engagement",
    92: "day_92_asset_inventory",
    93: "day_93_safe_service_discovery",
    94: "day_94_cve_and_severity_reasoning",
    95: "day_95_local_web_testing",
    96: "day_96_authorization_testing",
    97: "day_97_input_validation_testing",
    98: "day_98_bounded_fuzzing",
    99: "day_99_findings_and_retesting",
    100: "day_100_project__authorized_local_assessment",
    101: "day_101_secure_sdlc",
}


@dataclass(frozen=True)
class Spec:
    day: int
    title: str
    why: str
    problem: str
    vocabulary: str
    examples: tuple[tuple[str, str, str, str], ...]
    trace: str
    mistakes: str
    security: str
    mental: str
    limits: str


def e(title: str, teaching: str, code: str, result: str):
    return title, teaching, code, result


SPECS = [
    Spec(
        81,
        "The Response Lifecycle",
        "Response work is a controlled lifecycle, not a collection of exciting commands. Preparation, detection, analysis, containment, recovery, and lessons learned each have different evidence and authority requirements.",
        "Represent a synthetic alert from intake through closure while keeping actions bounded and approvals visible.",
        "An incident is a suspected adverse event requiring coordinated handling. Containment limits impact. Eradication removes a cause. Recovery restores service. A retrospective improves the system.",
        (
            e(
                "Define states",
                "A finite lifecycle prevents hidden transitions.",
                'states = ["new", "triage", "contained", "recovered", "closed"]\nprint(states)',
                "The allowed lifecycle is visible.",
            ),
            e(
                "Record an owner",
                "A response item needs responsibility.",
                'case = {"id": "training-81", "owner": "student", "state": "new"}\nprint(case)',
                "The case has an owner and state.",
            ),
            e(
                "Require authorization",
                "A containment action is not implied by an alert.",
                'action = {"name": "disable_fixture_account", "approved": False}\nprint(action)',
                "The action remains pending.",
            ),
            e(
                "Preserve evidence",
                "Response should reference evidence rather than alter it.",
                'case["evidence_refs"] = ["fixture:event-2"]\nprint(case)',
                "The case points to local evidence.",
            ),
            e(
                "Close with lessons",
                "Closure includes outcome and improvement.",
                'closure = {"state": "closed", "root_cause": "training fixture", "lesson": "add parser test"}\nprint(closure)',
                "The closeout is explainable.",
            ),
        ),
        "The case moves only through allowed states; every action has an owner, authority, evidence reference, and outcome. A signal does not automatically authorize containment.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| alert equals incident | response starts without validation | triage first |\n| no owner | work stalls | assign responsibility |\n| alter evidence | investigation loses provenance | preserve and work on copies |\n| contain without approval | service impact | define authority |\n| close without learning | defect repeats | record retrospective action |",
        "Use only a synthetic case and describe actions without performing them on real systems. The project must state who may approve each state transition.",
        "Response is a governed lifecycle that moves evidence and decisions through explicit states.",
        "Real response depends on law, policy, contracts, communications, and business continuity beyond this lesson.",
    ),
    Spec(
        82,
        "Evidence Integrity and Handling",
        "Evidence must remain attributable and unchanged enough for another reviewer to check it. Hashes, manifests, access records, and working copies support integrity but do not create a legal chain of custody by themselves.",
        "Create a local manifest for synthetic files and record who, when, where, and how each item was handled.",
        "Integrity means detecting change. Provenance records origin and transformation. A working copy is an analysis copy. A manifest lists evidence and digests.",
        (
            e(
                "Hash a file",
                "A digest detects later content changes.",
                'import hashlib\ndata = b"synthetic evidence"\nprint(hashlib.sha256(data).hexdigest()[:12])',
                "A repeatable digest prefix.",
            ),
            e(
                "Create a manifest",
                "The manifest binds names to digests and scope.",
                'manifest = {"case": "training-82", "files": {"event.txt": "digest"}, "scope": "local"}\nprint(manifest)',
                "The evidence set is explicit.",
            ),
            e(
                "Record handling",
                "Every transfer or transformation should be recorded.",
                'log = {"item": "event.txt", "actor": "student", "action": "copied", "time": "now"}\nprint(log)',
                "The handling event is visible.",
            ),
            e(
                "Verify before analysis",
                "Work should stop when a digest changes unexpectedly.",
                'expected = "abc"\nactual = "xyz"\nprint({"integrity_ok": expected == actual})',
                "`False` means review is required.",
            ),
            e(
                "Separate original and copy",
                "Analysis should not overwrite the source.",
                'paths = {"original": "evidence/original", "working": "analysis/copy"}\nprint(paths)',
                "The handling boundary is clear.",
            ),
        ),
        "The item is acquired into a controlled location, hashed, entered in the manifest, copied for analysis, and rechecked before conclusions are written.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| hash after editing | original state is unknown | hash at acquisition |\n| store digest beside attacker-controlled file | baseline can change | protect manifest |\n| no handling log | provenance is unclear | record actions and times |\n| analyze original | evidence is altered | use a working copy |\n| call hash legal proof | technical control overclaimed | state limits |",
        "Use synthetic files and a local manifest. Do not collect, copy, or analyze private evidence.",
        "Evidence integrity is a set of repeatable controls that make change and handling visible.",
        "Integrity controls do not prove truth, identity, or legal admissibility without organizational process.",
    ),
    Spec(
        83,
        "Filesystem Timelines",
        "File metadata and content changes can help reconstruct a sequence. Timestamps are clues with clock, filesystem, and copying limitations—not an automatic story of who acted.",
        "Build a synthetic timeline from file events and identify gaps and ambiguous ordering.",
        "A filesystem timestamp is metadata about an operation or state. A timeline orders observations. Clock skew and copying can change interpretation.",
        (
            e(
                "Represent events",
                "A timeline entry needs item, time, and source.",
                'events = [{"path": "a.txt", "kind": "modified", "time": "10:00Z"}]\nprint(events)',
                "The event is a bounded observation.",
            ),
            e(
                "Sort parsed times",
                "Use aware timestamps rather than text sorting.",
                'from datetime import datetime\nevents = ["2026-08-20T10:02:00+00:00", "2026-08-20T10:01:00+00:00"]\nprint(sorted(map(datetime.fromisoformat, events)))',
                "The earlier instant comes first.",
            ),
            e(
                "Record source",
                "A copied file and an original need different provenance.",
                'events[0]["source"] = "synthetic-fixture"\nprint(events[0])',
                "The source is attached.",
            ),
            e(
                "Flag clock uncertainty",
                "An event can be ordered while its exact meaning remains uncertain.",
                'print({"ordered": True, "clock_confidence": "low"})',
                "The report avoids overconfidence.",
            ),
            e(
                "Identify a gap",
                "Missing events are part of the timeline conclusion.",
                'print({"gap": "10:03–10:10Z", "explanation": "not observed"})',
                "The gap is explicit.",
            ),
        ),
        "The parser reads bounded metadata, converts timezones, sorts observations, attaches source and confidence, and reports missing windows rather than inventing actions.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| timestamp equals action | metadata is overinterpreted | say observed time only |\n| text sort | offsets misorder events | parse aware time |\n| copied file treated as original | provenance is lost | record source and transformations |\n| no gaps | incomplete collection looks complete | report not observed |\n| identify a person | file metadata is not identity proof | avoid attribution |",
        "Use only synthetic files and timestamps. Do not inspect a real home directory, university system, or workplace disk.",
        "A timeline orders observations and exposes gaps; it does not establish causation or identity.",
        "Filesystem semantics vary across platforms, filesystems, clocks, and copy tools.",
    ),
    Spec(
        84,
        "SQLite Artifacts",
        "Applications often store useful evidence in local databases. Safe analysis requires read-only copies, schema discovery, parameterized queries, bounded rows, and careful handling of deleted or stale records.",
        "Inspect a disposable SQLite fixture and produce a query result without modifying the source database.",
        "A SQLite artifact is a database file. A schema describes tables and columns. Read-only analysis avoids altering the source. A query plan affects resource behavior.",
        (
            e(
                "Connect to memory",
                "Use an in-memory database while learning SQL shape.",
                'import sqlite3\ndb = sqlite3.connect(":memory:")\ndb.execute("CREATE TABLE events (id INTEGER, kind TEXT)")\nprint(db.execute("SELECT name FROM sqlite_master WHERE type=\'table\'").fetchall())',
                "The table is visible.",
            ),
            e(
                "Insert fixture rows",
                "Synthetic data makes the query repeatable.",
                'db.executemany("INSERT INTO events VALUES (?, ?)", [(1, "login"), (2, "process")])\nprint(db.execute("SELECT COUNT(*) FROM events").fetchone())',
                "`(2,)`",
            ),
            e(
                "Use parameters",
                "Values remain separate from SQL syntax.",
                'kind = "login"\nprint(db.execute("SELECT id FROM events WHERE kind = ?", (kind,)).fetchall())',
                "`[(1,)]`",
            ),
            e(
                "Bound rows",
                "A forensic query should not accidentally return millions of rows.",
                'print(db.execute("SELECT id, kind FROM events LIMIT ?", (10,)).fetchall())',
                "The result is finite.",
            ),
            e(
                "Copy before work",
                "A source artifact should be preserved before analysis.",
                'paths = {"source": "evidence/app.db", "working_copy": "analysis/app.db"}\nprint(paths)',
                "The source and copy are distinct.",
            ),
        ),
        "The analyst preserves a source copy, discovers schema, uses parameters and read-only operations, caps results, and records query purpose and limitations.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| query original writable | evidence changes | work on a copy or read-only connection |\n| string SQL | injection and quoting errors | parameterize |\n| assume table names | query fails or misreads | inspect schema |\n| no limit | analysis exhausts resources | bound result |\n| missing timezone | timeline is wrong | normalize and preserve raw |",
        "Use only a disposable fixture. Do not open private browser, application, or workplace databases.",
        "Database analysis is a bounded, read-only interpretation of a preserved artifact.",
        "SQLite internals, deleted records, journaling, and application semantics require specialized tools and careful authorization.",
    ),
    Spec(
        85,
        "Browser and Document Artifacts",
        "Browser history, downloaded files, and office documents may contain useful context and sensitive personal data. Analysis should use supplied fixtures and minimize what is copied into reports.",
        "Extract a few fields from synthetic browser and document fixtures without interpreting them as proof of a person’s intent.",
        "An artifact is a recorded object. Metadata describes creation or modification. Content is the body. Provenance records source and handling.",
        (
            e(
                "Model a history row",
                "A history record needs URL-like text, time, and source.",
                'row = {"url": "https://training.local/docs", "visited_at": "2026-08-20T10:00:00Z", "source": "fixture"}\nprint(row)',
                "The source and time are present.",
            ),
            e(
                "Redact a query",
                "URLs may include tokens or personal identifiers.",
                'from urllib.parse import urlsplit, urlunsplit\nparts = urlsplit(row["url"])\nprint(urlunsplit((parts.scheme, parts.netloc, parts.path, "", "")))',
                "The query and fragment are omitted.",
            ),
            e(
                "Model document metadata",
                "Metadata and content should be separated.",
                'document = {"name": "training.doc", "author": "synthetic", "content_hash": "digest"}\nprint(document)',
                "The report can minimize content.",
            ),
            e(
                "Check fixture type",
                "A parser should not assume every file is the expected format.",
                'allowed = {".json", ".txt"}\nprint(".json" in allowed)',
                "The allowed formats are explicit.",
            ),
            e(
                "State interpretation",
                "A visit or metadata field is an observation, not intent.",
                'print({"observation": "fixture URL recorded", "intent": "not assessed"})',
                "The report avoids attribution.",
            ),
        ),
        "The analyst reads only a supplied fixture, extracts selected fields, removes unnecessary query data, records hashes and provenance, and writes a neutral interpretation.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| copy full URLs | tokens or personal data leak | redact query/fragment |\n| browsing equals intent | evidence becomes accusation | state intent unassessed |\n| open real profile | privacy violation | use fixtures |\n| trust extension | parser confusion | validate format and size |\n| publish document content | unnecessary exposure | minimize fields |",
        "Use synthetic browser rows and documents created for the course. Do not inspect a real browser profile or personal document.",
        "Artifacts preserve traces of activity and metadata; interpretation must remain cautious and privacy-aware.",
        "Artifacts can be shared, manipulated, stale, or incomplete, and lawful access requirements vary.",
    ),
    Spec(
        86,
        "Email and Phishing Fixtures",
        "Phishing analysis teaches headers, links, attachments, and social-engineering indicators without asking a learner to send, open, or interact with a real malicious message.",
        "Analyze a synthetic email fixture and report indicators, provenance, and uncertainty without visiting its links.",
        "An email header contains transport and message metadata. A URL is a destination string. An attachment is a referenced file. A lure is persuasive text designed to influence behavior.",
        (
            e(
                "Parse headers",
                "Header names and values are data to normalize.",
                'headers = {"From": "training@example.invalid", "Subject": "Review fixture"}\nprint(headers)',
                "The headers are synthetic.",
            ),
            e(
                "Extract a URL",
                "Extraction does not mean navigation.",
                'body = "Please visit https://training.invalid/review"\nprint(body.split()[2])',
                "The URL is printed as a string only.",
            ),
            e(
                "Check domain policy",
                "A training allowlist can reject unknown destinations.",
                'allowed = {"training.invalid"}\nprint("training.invalid" in allowed)',
                "The destination is recognized as a fixture domain.",
            ),
            e(
                "Model attachment metadata",
                "Metadata can be reviewed without opening content.",
                'attachment = {"name": "invoice.pdf", "size": 1200, "opened": False}\nprint(attachment)',
                "The attachment remains unopened.",
            ),
            e(
                "Report uncertainty",
                "A suspicious pattern is not proof of compromise.",
                'print({"signals": ["urgent language"], "clicked": False, "compromise": "not assessed"})',
                "The report distinguishes observation.",
            ),
        ),
        "The parser reads a fixture, normalizes safe headers, extracts links without navigation, checks attachment metadata, and reports signals plus what was not observed.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| click link | analysis becomes execution | treat as text |\n| open attachment | code or macros run | inspect metadata or sandbox under authority |\n| sender equals identity | headers can be forged | state provenance limits |\n| suspicious equals compromise | overclaiming | write neutral signals |\n| publish raw email | personal data leaks | minimize and redact |",
        "Use synthetic email text and `.invalid` domains. Do not send messages, click links, open real attachments, or collect credentials.",
        "Phishing analysis is cautious interpretation of message features and provenance, not a test of a person’s intent.",
        "Email headers and content can be forged, forwarded, truncated, or altered; attribution requires more evidence.",
    ),
    Spec(
        87,
        "Network Evidence",
        "Network evidence can explain sequence and protocol behavior, but it is sensitive and often incomplete. Fixture-first analysis lets learners practise fields, timestamps, direction, and truncation safely.",
        "Summarize synthetic flow records and identify what the fixture cannot show.",
        "A flow summarizes endpoints and bytes. Direction indicates source-to-destination orientation. A capture is packet-level evidence. Truncation limits interpretation.",
        (
            e(
                "Model a flow",
                "A flow record should name endpoints, time, and counts.",
                'flow = {"src": "127.0.0.1", "dst": "127.0.0.1", "src_port": 5000, "dst_port": 8000, "bytes": 120}\nprint(flow)',
                "The record is loopback-only.",
            ),
            e(
                "Normalize direction",
                "A report should define which endpoint is considered source.",
                'direction = {"source": flow["src"], "destination": flow["dst"]}\nprint(direction)',
                "Direction is explicit.",
            ),
            e(
                "Aggregate safely",
                "Totals can summarize without retaining every payload.",
                "flows = [120, 80]\nprint(sum(flows))",
                "`200` bytes across synthetic records.",
            ),
            e(
                "Mark truncation",
                "Missing packets or payloads limit conclusions.",
                'print({"payload_present": False, "complete": False})',
                "The limitation is visible.",
            ),
            e(
                "Avoid identity claims",
                "An endpoint is not a person.",
                'print({"endpoint": "127.0.0.1", "identity": "not established"})',
                "The interpretation is bounded.",
            ),
        ),
        "The analyst loads a saved fixture, parses flow fields, normalizes direction and time, aggregates selected counts, and marks missing payload or capture gaps.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| capture live traffic | privacy and authorization fail | use fixtures |\n| endpoint equals actor | identity is invented | state not established |\n| missing payload ignored | analysis looks complete | report truncation |\n| aggregate loses provenance | result cannot be checked | keep flow references |\n| packet pattern equals intent | context is absent | use neutral language |",
        "Use only synthetic flow records. Do not sniff interfaces, intercept traffic, or reconstruct other people’s communications.",
        "Network evidence describes observed communication properties with scope and completeness limits.",
        "Encryption, NAT, proxies, spoofing, and missing collection can make a flow misleading.",
    ),
    Spec(
        88,
        "Volatile Evidence Concepts",
        "Some evidence changes quickly: process lists, memory, open connections, and temporary state. The safe lesson is to reason about volatility and collection order without collecting from a real host.",
        "Create a synthetic evidence-priority plan and explain why collection order matters.",
        "Volatile evidence changes quickly. A snapshot is one observation. Collection order is the sequence in which evidence is preserved. A live response has operational risk.",
        (
            e(
                "Rank volatility",
                "Prioritize evidence that changes fastest in the plan.",
                'order = ["memory-like state", "process list", "connections", "disk fixture"]\nprint(order)',
                "The plan is ordered by conceptual volatility.",
            ),
            e(
                "Model a snapshot",
                "A snapshot needs time and scope.",
                'snapshot = {"kind": "processes", "captured_at": "now", "host": "synthetic"}\nprint(snapshot)',
                "The context is preserved.",
            ),
            e(
                "Record absence",
                "A missing collection is not an empty state.",
                'print({"kind": "memory", "status": "not_collected", "reason": "fixture only"})',
                "The limitation is honest.",
            ),
            e(
                "State collection impact",
                "Live collection can alter the system or expose data.",
                'risk = {"impact": "process list changes", "mitigation": "synthetic fixture"}\nprint(risk)',
                "The safety trade-off is explicit.",
            ),
            e(
                "Preserve order",
                "A response plan should explain why order was chosen.",
                'plan = {"order": order, "rationale": "preserve volatile state first"}\nprint(plan)',
                "The reasoning is reviewable.",
            ),
        ),
        "The plan ranks evidence, records scope and time, names unavailable sources, and documents collection impact before any live action is considered.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| collect everything first | volatile state changes | plan order |\n| live collection casually | system impact | use fixture or authority |\n| missing equals empty | blind spot is hidden | mark not collected |\n| no timestamp | state cannot be placed | record time |\n| memory dump without policy | privacy and access risk | do not collect in lesson |",
        "Use synthetic snapshots only. Do not inspect processes, memory, connections, or accounts on a real host.",
        "Volatility is a planning property: preserve changing observations first when authorized, and disclose what was not collected.",
        "Real volatile evidence collection requires specialized authority, tools, minimization, and legal or organizational procedures.",
    ),
    Spec(
        89,
        "Incident Reporting",
        "A report converts technical observations into a shared decision record. It should be concise enough to use and detailed enough to reproduce, with separate facts, assessment, actions, and limitations.",
        "Write a synthetic incident report with an executive summary, timeline, evidence references, impact assessment, and next steps.",
        "An executive summary communicates impact and status. A timeline orders observations. An impact assessment states affected scope. An action item has an owner and due state.",
        (
            e(
                "Write a summary",
                "Lead with scope, status, and confidence.",
                'summary = {"status": "investigating", "scope": "training fixture", "confidence": "low"}\nprint(summary)',
                "The summary is cautious.",
            ),
            e(
                "Build a timeline",
                "Use evidence references rather than unsupported prose.",
                'timeline = [{"time": "10:00Z", "event": "fixture alert", "ref": "line-2"}]\nprint(timeline)',
                "The event is traceable.",
            ),
            e(
                "Assess impact",
                "Impact is a bounded claim.",
                'impact = {"systems": 0, "real_users": 0, "training_records": 3}\nprint(impact)',
                "The scope is explicit.",
            ),
            e(
                "Assign action",
                "Reports should result in owned follow-up.",
                'action = {"task": "add parser test", "owner": "student", "state": "open"}\nprint(action)',
                "The action is concrete.",
            ),
            e(
                "State limitations",
                "A report protects readers from overtrust.",
                'limitations = ["synthetic", "no identity proof", "no live collection"]\nprint(limitations)',
                "The limitations are visible.",
            ),
        ),
        "The report gathers validated observations, orders them, assesses bounded impact, records authorized actions, assigns owners, and preserves limitations and evidence references.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| bury status | leaders cannot act | start with summary |\n| mix fact and interpretation | claims are hard to review | label sections |\n| no impact boundary | scope expands in retelling | quantify what is known |\n| no owner | action stalls | assign follow-up |\n| omit uncertainty | report becomes verdict | state confidence and gaps |",
        "Use synthetic events and fictional ownership. Do not report a real person, organization, or incident.",
        "A report is a shared, evidence-linked decision record with explicit scope and uncertainty.",
        "Reports can be copied out of context and cannot replace incident command or legal review.",
    ),
    Spec(
        90,
        "Project: Synthetic Breach Investigation",
        "This project combines response lifecycle, evidence handling, timelines, artifacts, email, network context, volatility planning, and reporting into one safe investigation of invented data.",
        "Investigate a synthetic case bundle and produce a report that distinguishes observations, hypotheses, and missing evidence.",
        "A case bundle is a bounded set of artifacts. A hypothesis is an explanation to test. A finding links evidence to a cautious conclusion.",
        (
            e(
                "Open the case index",
                "Start with scope and artifact list.",
                'case = {"id": "training-090", "artifacts": ["timeline.json", "email.txt", "flow.json"], "scope": "synthetic"}\nprint(case)',
                "The bundle is bounded.",
            ),
            e(
                "Verify artifacts",
                "Check manifest or digest before analysis.",
                'verified = {"timeline.json": True, "email.txt": True, "flow.json": True}\nprint(verified)',
                "All fixture artifacts pass the training check.",
            ),
            e(
                "Build hypotheses",
                "Hypotheses should be falsifiable and cautious.",
                'hypotheses = [{"text": "fixture rule triggered", "confidence": "medium"}, {"text": "real compromise", "confidence": "not assessed"}]\nprint(hypotheses)',
                "The second hypothesis is not asserted.",
            ),
            e(
                "Reference evidence",
                "Every assessment should cite a local artifact.",
                'finding = {"assessment": "needs review", "evidence": ["timeline.json:2", "flow.json:1"]}\nprint(finding)',
                "The report is traceable.",
            ),
            e(
                "Close the case",
                "Closure records learning and residual uncertainty.",
                'closure = {"state": "closed-training", "lesson": "add timestamp test", "unknowns": ["identity"]}\nprint(closure)',
                "The case closes without pretending certainty.",
            ),
        ),
        "The investigator preserves the bundle, verifies artifacts, builds hypotheses, tests them against local evidence, writes a report, and closes with lessons and unknowns.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| start with a story | evidence is selected to fit | start with index |\n| alter artifacts | reproducibility fails | work on copies |\n| hypothesis becomes fact | report overclaims | label confidence |\n| no unknowns | blind spots disappear | list missing evidence |\n| live response | scope and risk expand | synthetic-only |",
        "The project must remain synthetic, local, resettable, and non-operational. No real breach data, credentials, or response action is permitted.",
        "Investigation is a disciplined movement from preserved evidence to testable hypotheses to a bounded report.",
        "The project cannot teach all forensic disciplines, law, attribution, or production incident command.",
    ),
    Spec(
        91,
        "Rules of Engagement",
        "Authorized testing starts with permission, scope, timing, targets, techniques, stop conditions, and reporting—not with a tool command.",
        "Write a rules-of-engagement document for a local test service and show how a proposed action is checked before execution.",
        "Rules of engagement define permitted activity. Scope identifies targets. A stop condition ends testing. An escalation path handles unexpected impact.",
        (
            e(
                "Define target",
                "Name one local target and owner.",
                'roe = {"target": "127.0.0.1:8000", "owner": "course learner", "environment": "disposable"}\nprint(roe)',
                "The target is loopback and owned.",
            ),
            e(
                "Define allowed tests",
                "Technique names should be narrow and bounded.",
                'roe["allowed"] = ["health request", "invalid local input"]\nprint(roe)',
                "The test set is explicit.",
            ),
            e(
                "Define prohibited actions",
                "A prohibition prevents scope drift.",
                'roe["prohibited"] = ["credential guessing", "data deletion", "public scanning"]\nprint(roe)',
                "The dangerous expansions are named.",
            ),
            e(
                "Define stop conditions",
                "Stop when an impact signal appears.",
                'roe["stop_if"] = ["service instability", "unexpected target", "private data"]\nprint(roe)',
                "The tester has a stop rule.",
            ),
            e(
                "Approve a command",
                "A command is eligible only after all checks pass.",
                'proposal = {"target": "127.0.0.1:8000", "action": "health request"}\nprint(proposal["target"] == roe["target"] and proposal["action"] in roe["allowed"])',
                "`True` for the permitted proposal.",
            ),
        ),
        "The tester reads scope, compares target and action to allowlists, checks time and stop conditions, records approval, then performs only the local test and reports outcome.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| permission implied | target is guessed | require written scope |\n| scope by hostname only | redirects or aliases expand | define exact target |\n| no stop condition | impact continues | stop and escalate |\n| test first, document later | authorization is unclear | write ROE first |\n| keep credentials | sensitive data enters lab | use synthetic accounts |",
        "Use the local disposable service only. This lesson does not authorize vulnerability scanning, password attacks, exploitation, or public testing.",
        "Authorization is a prerequisite and a constraint; a tool command is never permission.",
        "Rules of engagement can be incomplete or superseded by policy; obtain current approval and stop when uncertain.",
    ),
    Spec(
        92,
        "Asset Inventory for Authorized Testing",
        "A test plan cannot be safe if the tester does not know what exists, who owns it, and which environment is in scope. Inventory is the foundation for bounded assessment.",
        "Create an inventory for a local application and classify each asset by owner, environment, data, and permitted action.",
        "An asset is a system or data resource. An owner is responsible for it. An environment is development, test, staging, or production. Scope is the allowed subset.",
        (
            e(
                "Model an asset",
                "Start with identity and owner.",
                'asset = {"id": "svc-92", "name": "training-api", "owner": "course", "environment": "test"}\nprint(asset)',
                "The asset is classified.",
            ),
            e(
                "Record data",
                "Data sensitivity affects test methods.",
                'asset["data"] = "synthetic case records"\nprint(asset)',
                "The data is non-production.",
            ),
            e(
                "Set scope",
                "An inventory item must say what is permitted.",
                'asset["allowed"] = ["read health", "invalid local input"]\nprint(asset)',
                "The allowed actions are narrow.",
            ),
            e(
                "Mark exclusions",
                "Explicit exclusions prevent accidental testing.",
                'asset["excluded"] = ["production", "real identities"]\nprint(asset)',
                "The exclusions are visible.",
            ),
            e(
                "Check inventory freshness",
                "Stale inventory can make a test target wrong.",
                'asset["last_verified"] = "2026-08-20"\nprint(asset["last_verified"])',
                "The date is recorded.",
            ),
        ),
        "The tester verifies asset identity, owner, environment, data classification, inclusion, exclusions, and freshness before planning any test.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| test by IP only | wrong asset is touched | use owner and asset id |\n| environment omitted | production is hit | classify environment |\n| stale list | retired target is tested | verify freshness |\n| data unknown | privacy risk | classify data |\n| inventory equals authorization | presence is not permission | require ROE |",
        "Use a repository inventory and local service fixture. Do not enumerate real networks or assets.",
        "An inventory answers what exists and who owns it; rules of engagement decide what may be tested.",
        "Inventories drift and may themselves contain sensitive infrastructure data.",
    ),
    Spec(
        93,
        "Safe Service Discovery",
        "Discovery can be useful in a disposable lab and dangerous on an unowned network. The safe pattern is to use a supplied target list and verify one endpoint rather than scan ranges.",
        "Check one approved local service from an explicit inventory and report unavailable versus closed without scanning.",
        "Discovery identifies reachable services. An allowlist is a fixed target set. A health check is a known request. A timeout limits waiting.",
        (
            e(
                "Read targets",
                "Discovery begins with approved inventory, not guesses.",
                'targets = [{"host": "127.0.0.1", "port": 8000, "purpose": "training"}]\nprint(targets)',
                "The target is explicit.",
            ),
            e(
                "Validate endpoint",
                "Reject targets outside the lab policy.",
                'target = targets[0]\nprint(target["host"] == "127.0.0.1")',
                "Only loopback passes this example.",
            ),
            e(
                "Check one service",
                "A connection attempt is still an authorized action.",
                'check = {"target": "127.0.0.1:8000", "timeout": 1, "request": "health"}\nprint(check)',
                "The operation is bounded.",
            ),
            e(
                "Classify result",
                "Unavailable and refused are different observations.",
                'print({"status": "unavailable", "meaning": "no conclusion about cause"})',
                "The interpretation is neutral.",
            ),
            e(
                "Stop after inventory",
                "Do not turn one check into a range scan.",
                'print({"targets_checked": 1, "range_scan": False})',
                "Scope is recorded.",
            ),
        ),
        "The tool loads an approved target, validates the host and port, performs one finite health check, records the transport result, and exits without expanding the target set.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| scan subnet | unauthorized reconnaissance | use one supplied target |\n| retry many ports | scope expands | fixed endpoint |\n| timeout means closed | cause is overclaimed | report unknown/unavailable |\n| follow redirects | target changes | revalidate or disable |\n| no log of scope | review cannot verify | record target count |",
        "Use loopback and a disposable service only. No range scans, port sweeps, banner grabbing, or public targets.",
        "Safe discovery is an approved inventory check with a finite target and neutral result interpretation.",
        "A failed connection can be caused by policy, routing, service state, or timeout; it does not reveal intent.",
    ),
    Spec(
        94,
        "CVE and Severity Reasoning",
        "A vulnerability identifier and a severity score are evidence inputs, not automatic remediation decisions. Engineers need affected version, exposure, exploitability, impact, and compensating controls.",
        "Evaluate a synthetic vulnerability record and produce a cautious local risk note.",
        "A vulnerability is a weakness. A CVE identifier names a published issue. Severity estimates impact and exploitability under a scoring model. Risk adds environment and business context.",
        (
            e(
                "Model a record",
                "A record needs affected component and version.",
                'vuln = {"id": "CVE-training", "component": "training-lib", "version": "1.0"}\nprint(vuln)',
                "The issue is synthetic.",
            ),
            e(
                "Separate severity and exposure",
                "A high severity issue may not be reachable in this environment.",
                'vuln.update({"severity": "high", "exposed": False})\nprint(vuln)',
                "The fields stay separate.",
            ),
            e(
                "Check applicability",
                "Affected version must be compared with the installed record.",
                'installed = "1.0"\nprint(installed == vuln["version"])',
                "Applicability is a separate fact.",
            ),
            e(
                "Record control",
                "A compensating control changes local risk, not the published severity.",
                'vuln["control"] = "loopback-only service"\nprint(vuln)',
                "The context is recorded.",
            ),
            e(
                "Choose action",
                "Action should include owner and deadline rather than panic.",
                'action = {"owner": "student", "next": "upgrade training dependency", "status": "planned"}\nprint(action)',
                "The response is actionable.",
            ),
        ),
        "The analyst verifies identity and version, assesses exposure and controls, separates published severity from local risk, and records an owned next action.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| score equals risk | environment is ignored | assess exposure and context |\n| name equals affected | version is not checked | verify applicability |\n| exploit immediately | testing exceeds authorization | remediate or use lab |\n| no source/date | record is stale | preserve provenance |\n| panic language | decision quality drops | write owner and next step |",
        "Use fictional vulnerability records and local dependencies. Do not download exploit code or test a public service.",
        "Vulnerability management connects published weakness, local applicability, exposure, controls, and ownership.",
        "Severity models vary and can be incomplete; legal, business, and operational risk need domain owners.",
    ),
    Spec(
        95,
        "Local Web Testing",
        "Testing a web service safely means checking explicit contracts on a local target, recording expected and unexpected behavior, and stopping at the rules of engagement.",
        "Test a local health endpoint for status, content type, and invalid input using a small fixture-driven test suite.",
        "A test case has setup, action, expected result, and cleanup. A negative test sends invalid input. A regression test protects a fixed behavior.",
        (
            e(
                "Define a case",
                "A test case should be a data object.",
                'case = {"name": "health", "method": "GET", "path": "/health", "expected": 200}\nprint(case)',
                "The test contract is explicit.",
            ),
            e(
                "Check content type",
                "Status alone does not prove response contract.",
                'response = {"status": 200, "content_type": "application/json"}\nprint(response)',
                "The response includes both fields.",
            ),
            e(
                "Add negative input",
                "Invalid input should be rejected predictably.",
                'negative = {"path": "/cases", "body": {"limit": -1}, "expected": 400}\nprint(negative)',
                "The boundary case is explicit.",
            ),
            e(
                "Record cleanup",
                "Testing must leave the local service reset.",
                'cleanup = {"created_records": 0, "output_deleted": True}\nprint(cleanup)',
                "No test data remains.",
            ),
            e(
                "Keep scope",
                "Tests should carry target and approval.",
                'metadata = {"target": "127.0.0.1:8000", "approved": True}\nprint(metadata)',
                "The target is local and approved.",
            ),
        ),
        "The runner loads cases, confirms target scope, performs one local request at a time, validates status/headers/body, records failures, and resets generated state.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| test public endpoint | unauthorized activity | loopback-only |\n| only happy path | validation failures hide | add negative tests |\n| no cleanup | state changes persist | reset fixture |\n| exploit instead of verify | risk grows | test contract minimally |\n| no evidence | finding cannot reproduce | record request and expected result safely |",
        "Use local service fixtures, synthetic identities, and harmless invalid inputs. No exploitation, credential guessing, or public scanning.",
        "Authorized testing is controlled experimentation against a known contract and target, with cleanup and evidence.",
        "A passing local test says little about production deployment, authentication integration, or unknown attack paths.",
    ),
    Spec(
        96,
        "Authorization Testing",
        "Authorization bugs often occur when a caller can access another object or perform an action outside its role. Testing should use synthetic identities and cases, not real accounts.",
        "Test object-level and action-level authorization with a small matrix of fictional users, roles, and cases.",
        "A subject is a fictional caller identity. An object is a resource. An action is an operation. An authorization matrix lists allowed and denied combinations.",
        (
            e(
                "Create identities",
                "Use labels rather than credentials.",
                'identities = {"alice": {"role": "analyst"}, "bob": {"role": "viewer"}}\nprint(identities)',
                "The identities are synthetic.",
            ),
            e(
                "Create objects",
                "Ownership or scope is a separate record.",
                'ownership = {"alice": {"case-1"}, "bob": {"case-2"}}\nprint(ownership)',
                "Each subject has object scope.",
            ),
            e(
                "Test an allow",
                "The expected result is part of the case.",
                'case = {"subject": "alice", "action": "read", "object": "case-1", "expected": True}\nprint(case)',
                "The allowed case is explicit.",
            ),
            e(
                "Test horizontal denial",
                "A caller should not read another subject’s object.",
                'case = {"subject": "alice", "action": "read", "object": "case-2", "expected": False}\nprint(case)',
                "The cross-object case is denied.",
            ),
            e(
                "Test action denial",
                "A role may read but not delete.",
                'policy = {"viewer": {"read"}}\nprint("delete" in policy["viewer"])',
                "The action is denied.",
            ),
        ),
        "The matrix supplies subject, role, action, and object; the service evaluates role and object scope; the test compares the result with expected allow/deny without using real authentication.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| role-only tests | object leak missed | add horizontal cases |\n| UI-only denial | API bypass | test service boundary |\n| real accounts | privacy and access risk | synthetic identities |\n| expected unspecified | failure is ambiguous | write matrix first |\n| denial leaks object | error reveals data | safe error responses |",
        "Use fictional identities and local cases. Do not test a real account or attempt to bypass access controls on a public service.",
        "Authorization testing asks whether each subject/action/object combination matches the written policy.",
        "A small matrix cannot cover every policy path, tenant rule, or deployment integration.",
    ),
    Spec(
        97,
        "Input Validation Testing",
        "Validation tests should prove that boundaries reject malformed, missing, oversized, and unexpected input while accepting valid data. The goal is predictable behavior, not payload theater.",
        "Create a table-driven validation suite for a synthetic case request.",
        "A boundary case is near an allowed limit. A negative case is invalid. A property is a behavior that should hold across many inputs.",
        (
            e(
                "Define valid input",
                "Start with the smallest accepted request.",
                'valid = {"case_id": "training-97", "limit": 10}\nprint(valid)',
                "The valid shape is known.",
            ),
            e(
                "List invalid cases",
                "Test categories rather than one magic string.",
                'invalid = [{}, {"limit": -1}, {"case_id": "x" * 10000}]\nprint(len(invalid))',
                "Three invalid classes are present.",
            ),
            e(
                "Test a boundary",
                "Allowed endpoints need explicit tests.",
                "for limit in [1, 100]:\n    print(limit, 1 <= limit <= 100)",
                "Both endpoints are accepted by this policy.",
            ),
            e(
                "Test a just-outside value",
                "Off-by-one bugs appear adjacent to the boundary.",
                "for limit in [0, 101]:\n    print(limit, 1 <= limit <= 100)",
                "Both are rejected.",
            ),
            e(
                "Return safe errors",
                "Tests should check error shape without exposing raw input.",
                'error = {"status": 400, "field": "limit", "message": "outside allowed range"}\nprint(error)',
                "The error is actionable and minimal.",
            ),
        ),
        "The suite arranges one case, validates it, compares accepted/rejected outcome and safe error schema, and repeats across a table of boundaries and malformed shapes.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| only valid tests | bad input reaches service | add categories |\n| huge payload in test | test itself consumes resources | small bounded representative |\n| assert raw error | secret input leaks | assert safe fields |\n| no property | one sample passes by accident | state invariant |\n| input test becomes exploit | scope changes | keep contract-focused |",
        "Use synthetic requests and a local handler. Test validation, not exploitation or bypass of a real application.",
        "Input validation testing turns the boundary contract into repeatable evidence.",
        "Tests can miss parser differentials, framework behavior, encoding edge cases, and integration failures.",
    ),
    Spec(
        98,
        "Bounded Fuzzing",
        "Fuzzing generates varied inputs to find crashes and contract violations. Without bounds and a resettable target, it can become an availability problem instead of a learning exercise.",
        "Generate small synthetic inputs, run them against a pure validator, and record crashes without unbounded loops or network traffic.",
        "Fuzzing varies input automatically. A seed makes a run reproducible. A corpus is a collection of inputs. A crash is an unexpected failure requiring minimization.",
        (
            e(
                "Create a seed",
                "Reproducibility begins with a fixed seed.",
                "import random\nrng = random.Random(98)\nprint([rng.randint(0, 9) for _ in range(5)])",
                "The sequence repeats for the same seed.",
            ),
            e(
                "Generate a bounded string",
                "Limit length and alphabet.",
                'alphabet = "abc012"\nvalue = "".join(rng.choice(alphabet) for _ in range(8))\nprint(value)',
                "The input is small and printable.",
            ),
            e(
                "Run a pure validator",
                "A pure function avoids external side effects.",
                "def accepts(text):\n    return len(text) <= 10 and text.isalnum()\nprint(accepts(value))",
                "The result is deterministic for the input.",
            ),
            e(
                "Record a failure",
                "A crash record needs the seed and input, not a secret dump.",
                'failure = {"seed": 98, "input": value, "error": "training failure"}\nprint(failure)',
                "The case is reproducible.",
            ),
            e(
                "Stop at a budget",
                "Runs need a finite case and time budget.",
                'budget = {"cases": 100, "seconds": 5}\nprint(budget)',
                "The fuzzer cannot run forever.",
            ),
        ),
        "The runner seeds the generator, creates bounded inputs, invokes a pure local validator, records exceptions with the seed, and stops at case/time limits.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| random unseeded | failure cannot reproduce | record seed |\n| unlimited cases | resource exhaustion | finite budget |\n| network target | accidental load | pure function or local fixture |\n| store all inputs | output grows | retain failing/minimized cases |\n| call crash vulnerability | finding is overclaimed | report reproducible behavior |",
        "Fuzz only pure course validators or a disposable local service with explicit approval and tiny budgets. Do not fuzz public services.",
        "Bounded fuzzing is reproducible variation under a finite resource and scope contract.",
        "Finding a crash does not automatically establish exploitability, impact, or root cause.",
    ),
    Spec(
        99,
        "Findings and Retesting",
        "A finding becomes useful when it states affected component, reproduction, impact, evidence, severity rationale, remediation, and retest result. Retesting should verify the original behavior without expanding scope.",
        "Write a synthetic finding, propose a fix, and record a retest that changes the status from open to verified or remains open.",
        "A finding is a documented issue. Reproduction is a minimal repeatable test. Remediation changes the control. Retest checks whether the original condition remains.",
        (
            e(
                "State a finding",
                "Start with a concise title and affected route.",
                'finding = {"title": "training endpoint accepts invalid limit", "route": "/cases", "status": "open"}\nprint(finding)',
                "The issue is scoped.",
            ),
            e(
                "Give reproduction",
                "A minimal case is easier to review.",
                'reproduction = {"input": {"limit": -1}, "expected": 400, "observed": 200}\nprint(reproduction)',
                "The behavior is concrete.",
            ),
            e(
                "Assess impact",
                "Impact must match evidence.",
                'finding["impact"] = {"scope": "synthetic API", "effect": "invalid data reaches service"}\nprint(finding)',
                "The impact is bounded.",
            ),
            e(
                "Record remediation",
                "A fix should name control and owner.",
                'remediation = {"control": "range validation", "owner": "student", "status": "planned"}\nprint(remediation)',
                "The action is actionable.",
            ),
            e(
                "Retest",
                "Retesting repeats the original case and records outcome.",
                'retest = {"input": {"limit": -1}, "observed": 400, "status": "verified"}\nprint(retest)',
                "The fixed behavior is documented.",
            ),
        ),
        "The finding records original evidence, remediation, and retest using the same bounded case. The status changes only when the expected behavior is observed.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| vague title | owner cannot act | name component and behavior |\n| no reproduction | finding cannot be checked | give minimal input and expected result |\n| severity without rationale | priority is arbitrary | explain impact and exposure |\n| retest different case | fix is not verified | repeat original behavior |\n| claim fixed from code review | runtime behavior unknown | run a safe retest |",
        "Use only synthetic local findings. Do not publish or weaponize a real vulnerability; follow the repository security policy for reports.",
        "A finding is a reproducible claim with bounded impact, owned remediation, and an evidence-linked retest.",
        "Retesting can miss variants and does not prove absence of all related bugs.",
    ),
    Spec(
        100,
        "Project: Authorized Local Assessment",
        "This project is the culmination of safe testing: scope, inventory, ROE, local web tests, validation checks, bounded fuzzing, findings, remediation, and retesting in one controlled assessment.",
        "Assess one disposable local service and produce an evidence-based report without scanning, exploitation, or real credentials.",
        "An assessment is a scoped evaluation. A test plan states cases and expected results. A finding is an observed contract failure. A closeout records limits and cleanup.",
        (
            e(
                "Load authorization",
                "The project begins with the signed or explicit local scope record.",
                'scope = {"target": "127.0.0.1:8000", "allowed": ["health", "validation"], "stop": ["instability"]}\nprint(scope)',
                "The target and limits are visible.",
            ),
            e(
                "Run inventory",
                "Check the target against the approved asset list.",
                'asset = {"target": "127.0.0.1:8000", "environment": "disposable", "owner": "course"}\nprint(asset["target"] == scope["target"])',
                "The asset matches scope.",
            ),
            e(
                "Run contract tests",
                "Use a small table of safe cases.",
                'tests = [{"path": "/health", "expected": 200}, {"path": "/cases", "input": {"limit": -1}, "expected": 400}]\nprint(tests)',
                "The cases are explicit.",
            ),
            e(
                "Create finding",
                "Only observed deviations become findings.",
                'finding = {"status": "none", "evidence": ["health-1", "validation-1"]}\nprint(finding)',
                "No issue is invented when tests pass.",
            ),
            e(
                "Close and reset",
                "The assessment ends with cleanup and limitations.",
                'closeout = {"reports_deleted": True, "service_stopped": True, "public_target": False, "limitations": ["local only"]}\nprint(closeout)',
                "The environment is reset.",
            ),
        ),
        "The assessment verifies authorization, matches one asset, executes only planned local cases, records evidence and findings, retests fixes, and closes with cleanup and limitations.",
        "| Mistake | Symptom | Correction |\n| --- | --- | --- |\n| scope after testing | authorization is unclear | load it first |\n| add scanning feature | project exceeds ROE | one local service |\n| report every difference | noise and overclaiming | require reproducible evidence |\n| no retest | remediation is unverified | repeat original case |\n| forget cleanup | local state persists | reset and document |",
        "The project is loopback-only, disposable, synthetic, read-only where possible, finite, and governed by explicit stop conditions. It must never test a public or third-party target.",
        "An authorized assessment is a controlled experiment whose strongest result is reproducible evidence within a documented boundary.",
        "This project cannot establish production security, legal compliance, exploitability, or absence of unknown vulnerabilities.",
    ),
]


def render(spec: Spec) -> str:
    prev_dir = DIRS[spec.day - 1]
    next_dir = DIRS[spec.day + 1]
    lines = [
        f"# Day {spec.day}: {spec.title}",
        "",
        f"[← Day {spec.day - 1}](../{prev_dir}/{prev_dir}.md) · [Day index](../DAY_INDEX.md) · [Day {spec.day + 1} →](../{next_dir}/{next_dir}.md)",
        "",
        "## Table of Contents",
        "",
        "- [Why this lesson exists](#why-this-lesson-exists)",
        "- [Prerequisites](#prerequisites)",
        "- [Outcomes](#outcomes)",
        "- [The problem](#the-problem)",
        "- [Security boundary](#security-boundary)",
        "- [Lesson](#lesson)",
        "- [Vocabulary](#vocabulary)",
        "- [Worked examples](#worked-examples)",
        "- [Execution trace](#execution-trace)",
        "- [Common mistakes](#common-mistakes)",
        "- [Security application](#security-application)",
        "- [Exercises](#exercises)",
        "- [Finish line](#finish-line)",
        "",
        "## Why this lesson exists",
        "",
        spec.why,
        "",
        "## Prerequisites",
        "",
        f"Complete Day {spec.day - 1}. Use only the local fixtures and explicit loopback assessment scope supplied by the course.",
        "",
        "## Outcomes",
        "",
        "By the end of this lesson, you can:",
        "",
        "- explain the concept before using a tool\n- run and modify every worked example\n- test normal, boundary, and failure behavior\n- state scope, evidence, and residual risk\n- complete the numbered exercises",
        "",
        "## The problem",
        "",
        spec.problem,
        "",
        "## Security boundary",
        "",
        "This lesson is educational and authorized-lab-only. It does not authorize public scanning, credential guessing, exploitation, interception, persistence, or changes to systems you do not own.",
        "",
        "## Lesson",
        "",
        "### Vocabulary",
        "",
        spec.vocabulary,
        "",
        "## Worked examples",
        "",
    ]
    for i, (title, teaching, code, result) in enumerate(spec.examples, 1):
        lines += [
            f"### Example {i}: {title}",
            "",
            teaching,
            "",
            "```python",
            code,
            "```",
            "",
            "**What to observe:**",
            "",
            result,
            "",
        ]
    lines += [
        "## Execution trace",
        "",
        spec.trace,
        "",
        "## Common mistakes",
        "",
        spec.mistakes,
        "",
        "## Security application",
        "",
        spec.security,
        "",
        "## Exercises",
        "",
        "Complete the numbered questions in [practice/exercises.md](practice/exercises.md) in order. Record the requested evidence, expected behavior, edge case, and limitation.",
        "",
        "## Finish line",
        "",
        f"Run `python -m course_days.day{spec.day:03d}`, pass the relevant tests, complete the numbered exercises, and explain one edge case aloud or in writing.",
        "",
        "## Mental model",
        "",
        f"> {spec.mental}",
        "",
        "## Limitations",
        "",
        spec.limits,
        "",
        f"[← Day {spec.day - 1}](../{prev_dir}/{prev_dir}.md) · [Day index](../DAY_INDEX.md) · [Day {spec.day + 1} →](../{next_dir}/{next_dir}.md)",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    for spec in SPECS:
        directory = ROOT / DIRS[spec.day]
        (directory / f"{directory.name}.md").write_text(render(spec), encoding="utf-8")
    print("Authored dense teaching chapters for Days 81–100.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
